manifestVersion: subsquid.io/v0.1
name: hydration-pools-hollar-testnet
slot: 101
description: Hydration pools indexer
build:
deploy:
  env:
    ORCHESTRATOR_QUEUE_REDIS_HOST: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_HOST }}
    ORCHESTRATOR_QUEUE_REDIS_PASS: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_PASS }}
    TS_REDIS_HOST: ${{ secrets.TS_REDIS_STAGING_HOST }}
    TS_REDIS_PASS: ${{ secrets.TS_REDIS_STAGING_PASS }}
  addons:
    postgres:
      config:
        statement_timeout: 30060000
        log_min_duration_statement: 60000
  processor:
    env:
      REAGGREGATION_PROCESSING_MODE: true
      STATE_SCHEMA_NAME: recalc_1754674239469

      CHAIN: 'hydration_paseo_next'
      INDEXER_ID: 100
      RPC_URL: 'wss://node.lark.hydration.cloud'
      RPC_URL_HTTPS: 'wss://node.lark.hydration.cloud'
      ORCHESTRATOR_QUEUE_REDIS_PORT: 6379
      TS_REDIS_PORT: 6377
      TS_REDIS_KEY_SPACE_ID: 5
      MAX_JOB_BATCH_SIZE: 10

      NODE_ENV: 'production'
      OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
      HOLLAR_CONTRACT_ADDRESS: '0xfdb15f9fe2252044b08230449d4278cfd4df52e1'
      UNIFIED_EVENTS_GENESIS_SPEC_VERSION: 1
      INDEXING_IS_PAUSED: false
      ALL_IN_ONE_PROCESSOR_MODE: true
      IS_CORE_PROCESSOR: false
      IS_SPOT_PRICES_PROCESSOR: false
      PERSIST_HIST_DATA_ONLY_ON_CHANGE: false
      USE_XYKPOOLS_DATA_IN_TRADE_ROUTER: false
      HISTORICAL_DATA_PROCESSING_SUB_BATCH_SIZE: 21

      PROCESS_FROM_BLOCK: 48800
      PROCESS_TO_BLOCK: 48800

      IGNORE_ARCHIVE_DATA_SOURCE: true
      USE_STORAGE_DICTIONARY: false
    cmd:
      - sqd
      - process:prod
  api:
    env:
      NODE_ENV: 'production'
      CHAIN: 'hydration_paseo_next'
      GQL_PORT: 8080
      INDEXER_ID: 100
      TS_REDIS_PORT: 6377
      TS_REDIS_KEY_SPACE_ID: 5
      SUBSCAN_PRO_API_SECRET: ${{ secrets.SUBSCAN_PRO_API_SECRET }}
      SUBSCAN_PROXY_API_CORS_ALLOWED_SUFFIXES: 'hydration.net::-hydra-app.netlify.app'
      SUBSCAN_PROXY_API_CORS_ALLOW_LOCALHOST: true

    cmd:
      - sqd
      - api:prod
scale:
  dedicated: false
  addons:
    postgres:
      profile: large
      storage: 180G
  processor:
    profile: large
  api:
    profile: small
