#manifestVersion: subsquid.io/v0.1
#name: hydration-pools
#slot: 728
#description: Hydration pools indexer
#build:
#deploy:
#  env:
#    ORCHESTRATOR_QUEUE_REDIS_HOST: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_HOST }}
#    ORCHESTRATOR_QUEUE_REDIS_PASS: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_PASS }}
#    TS_REDIS_HOST: ${{ secrets.TS_REDIS_HOST }}
#    TS_REDIS_PASS: ${{ secrets.TS_REDIS_PASS }}
#  addons:
#    postgres:
#      config:
#        statement_timeout: 30060000
#        log_min_duration_statement: 60000
#  processor:
#    env:
#      CHAIN: 'hydration'
#      INDEXER_ID: 728
#      RPC_URL: 'wss://node.kril.hydration.cloud'
#      GATEWAY_HYDRATION_HTTPS: 'https://v2.archive.subsquid.io/network/hydradx'
#      ORCHESTRATOR_QUEUE_REDIS_PORT: 6379
#      TS_REDIS_PORT: 6378
#      TS_REDIS_KEY_SPACE_ID: 4
#      MAX_JOB_BATCH_SIZE: 10
#
#      PROCESS_LBP_POOLS: true
#      PROCESS_XYK_POOLS: true
#      PROCESS_OMNIPOOLS: true
#      PROCESS_STABLEPOOLS: true
#      PROCESS_DCA: true
#      PROCESS_OTC: true
#      NODE_ENV: 'production'
#      OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
#      UNIFIED_EVENTS_GENESIS_SPEC_VERSION: 282
#      INDEXING_IS_PAUSED: false
#      ALL_IN_ONE_PROCESSOR_MODE: true
#      IS_CORE_PROCESSOR: false
#      IS_SPOT_PRICES_PROCESSOR: false
#      SAVE_ASSET_RELATED_HISTORICAL_DATA_ON_CHANGE: true
#      USE_XYKPOOLS_DATA_IN_TRADE_ROUTER: false
#      HISTORICAL_DATA_PROCESSING_SUB_BATCH_SIZE: 20
#
#      PROCESS_FROM_BLOCK: 7890000
#      PROCESS_TO_BLOCK: -1
#
#      USE_STORAGE_DICTIONARY: true
#      STORAGE_DICTIONARY_LBPPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:lbppool-v2/api/graphql'
#      STORAGE_DICTIONARY_XYKPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:xykpool-v2/api/graphql'
#      STORAGE_DICTIONARY_OMNIPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:omnipool-v2/api/graphql'
#      STORAGE_DICTIONARY_STABLEPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:stablepool-v2/api/graphql'
#      STORAGE_DICTIONARY_GEN_HIST_DATA_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:generic-data-v2/api/graphql'
#    cmd:
#      - sqd
#      - process:prod
#  api:
#    env:
#      NODE_ENV: 'production'
#      CHAIN: 'hydration'
#      GQL_PORT: 8080
#      INDEXER_ID: 728
#      TS_REDIS_PORT: 6378
#      TS_REDIS_KEY_SPACE_ID: 4
#      SUBSCAN_PRO_API_SECRET: ${{ secrets.SUBSCAN_PRO_API_SECRET }}
#      SUBSCAN_PROXY_API_CORS_ALLOWED_SUFFIXES: 'hydration.net::-hydra-app.netlify.app'
#      SUBSCAN_PROXY_API_CORS_ALLOW_LOCALHOST: true
#
#    cmd:
#      - sqd
#      - api:prod
#scale:
#  dedicated: false
#  addons:
#    postgres:
#      profile: large
#      storage: 250G
#  processor:
#    profile: large
#  api:
#    profile: large

manifestVersion: subsquid.io/v0.1
name: hydration-pools
slot: 729
description: Hydration pools indexer
build:
deploy:
  env:
    ORCHESTRATOR_QUEUE_REDIS_HOST: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_HOST }}
    ORCHESTRATOR_QUEUE_REDIS_PASS: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_PASS }}
    TS_REDIS_HOST: ${{ secrets.TS_REDIS_HOST }}
    TS_REDIS_PASS: ${{ secrets.TS_REDIS_PASS }}
  addons:
    postgres:
      config:
        statement_timeout: 30060000
        log_min_duration_statement: 60000
  processor:
    env:
      CHAIN: 'hydration'
      INDEXER_ID: 729
      RPC_URL: 'wss://node.kril.hydration.cloud'
      GATEWAY_HYDRATION_HTTPS: 'https://v2.archive.subsquid.io/network/hydradx'
      ORCHESTRATOR_QUEUE_REDIS_PORT: 6379
      TS_REDIS_PORT: 6378
      TS_REDIS_KEY_SPACE_ID: 4
      MAX_JOB_BATCH_SIZE: 10

      PROCESS_LBP_POOLS: true
      PROCESS_XYK_POOLS: true
      PROCESS_OMNIPOOLS: true
      PROCESS_STABLEPOOLS: true
      PROCESS_DCA: true
      PROCESS_OTC: true
      NODE_ENV: 'production'
      OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
      UNIFIED_EVENTS_GENESIS_SPEC_VERSION: 282
      INDEXING_IS_PAUSED: false
      ALL_IN_ONE_PROCESSOR_MODE: true
      IS_CORE_PROCESSOR: false
      IS_SPOT_PRICES_PROCESSOR: false
      SAVE_ASSET_RELATED_HISTORICAL_DATA_ON_CHANGE: true
      USE_XYKPOOLS_DATA_IN_TRADE_ROUTER: false
      HISTORICAL_DATA_PROCESSING_SUB_BATCH_SIZE: 20

      PROCESS_FROM_BLOCK: 7890000
      PROCESS_TO_BLOCK: -1

      USE_STORAGE_DICTIONARY: true
      STORAGE_DICTIONARY_LBPPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:lbppool-v2/api/graphql'
      STORAGE_DICTIONARY_XYKPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:xykpool-v2/api/graphql'
      STORAGE_DICTIONARY_OMNIPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:omnipool-v2/api/graphql'
      STORAGE_DICTIONARY_STABLEPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:stablepool-v2/api/graphql'
      STORAGE_DICTIONARY_GEN_HIST_DATA_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:generic-data-v2/api/graphql'
    cmd:
      - sqd
      - process:prod
  api:
    env:
      NODE_ENV: 'production'
      CHAIN: 'hydration'
      GQL_PORT: 8080
      INDEXER_ID: 729
      TS_REDIS_PORT: 6378
      TS_REDIS_KEY_SPACE_ID: 4
      SUBSCAN_PRO_API_SECRET: ${{ secrets.SUBSCAN_PRO_API_SECRET }}
      SUBSCAN_PROXY_API_CORS_ALLOWED_SUFFIXES: 'hydration.net::-hydra-app.netlify.app'
      SUBSCAN_PROXY_API_CORS_ALLOW_LOCALHOST: true

    cmd:
      - sqd
      - api:prod
scale:
  dedicated: false
  addons:
    postgres:
      profile: large
      storage: 250G
  processor:
    profile: large
  api:
    profile: large

#
#manifestVersion: subsquid.io/v0.1
#name: hydration-pools
#slot: 731
#description: Hydration pools indexer (Full history)
#build:
#deploy:
#  env:
#    ORCHESTRATOR_QUEUE_REDIS_HOST: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_HOST }}
#    ORCHESTRATOR_QUEUE_REDIS_PASS: ${{ secrets.ORCHESTRATOR_QUEUE_REDIS_PASS }}
#  addons:
#    postgres:
#      config:
#        statement_timeout: 30060000
#        log_min_duration_statement: 60000
#  processor:
#    env:
#      CHAIN: 'hydration'
#      INDEXER_ID: 731
#      RPC_URL: 'wss://node.kril.hydration.cloud'
#      GATEWAY_HYDRATION_HTTPS: 'https://v2.archive.subsquid.io/network/hydradx'
#      ORCHESTRATOR_QUEUE_REDIS_PORT: 6379
#      MAX_JOB_BATCH_SIZE: 10
#
#      PROCESS_LBP_POOLS: true
#      PROCESS_XYK_POOLS: true
#      PROCESS_OMNIPOOLS: true
#      PROCESS_STABLEPOOLS: true
#      PROCESS_DCA: true
#      PROCESS_OTC: true
#      NODE_ENV: 'production'
#      OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
#      UNIFIED_EVENTS_GENESIS_SPEC_VERSION: 282
#      INDEXING_IS_PAUSED: true
#      ALL_IN_ONE_PROCESSOR_MODE: true
#      IS_CORE_PROCESSOR: false
#      IS_SPOT_PRICES_PROCESSOR: false
#      SAVE_ASSET_RELATED_HISTORICAL_DATA_ON_CHANGE: true
#      USE_XYKPOOLS_DATA_IN_TRADE_ROUTER: false
#      HISTORICAL_DATA_PROCESSING_SUB_BATCH_SIZE: 20
#
#      PROCESS_FROM_BLOCK: 1439857
#      PROCESS_TO_BLOCK: -1
#
#      USE_STORAGE_DICTIONARY: true
#      STORAGE_DICTIONARY_LBPPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:lbppool-v2/api/graphql'
#      STORAGE_DICTIONARY_XYKPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:xykpool-v2/api/graphql'
#      STORAGE_DICTIONARY_OMNIPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:omnipool-v2/api/graphql'
#      STORAGE_DICTIONARY_STABLEPOOL_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:stablepool-v2/api/graphql'
#      STORAGE_DICTIONARY_GEN_HIST_DATA_URL: 'https://galacticcouncil.squids.live/hydration-storage-dictionary:generic-data-v2/api/graphql'
#    cmd:
#      - sqd
#      - process:prod
#  api:
#    env:
#      NODE_ENV: 'production'
#      CHAIN: 'hydration'
#      GQL_PORT: 8080
#      INDEXER_ID: 731
#      SUBSCAN_PRO_API_SECRET: ${{ secrets.SUBSCAN_PRO_API_SECRET }}
#      SUBSCAN_PROXY_API_CORS_ALLOWED_SUFFIXES: 'hydration.net::-hydra-app.netlify.app'
#      SUBSCAN_PROXY_API_CORS_ALLOW_LOCALHOST: true
#
#    cmd:
#      - sqd
#      - api:prod
#scale:
#  dedicated: false
#  addons:
#    postgres:
#      profile: large
#      storage: 300G
#  processor:
#    profile: small
#  api:
#    profile: small
