# ======================================================================================================================
# *** Common entities ***
# ======================================================================================================================

enum LiquidityActionEvent {
  Add
  Remove
}

type ProcessorStatus @entity {
  "processor state schema name"
  id: ID!
  assetsLastUpdatedAtBlock: Int!
  poolsDestroyedUpdatedAtBlock: Int
  initialIndexingStartedAt: DateTime!
  initialIndexingFinishedAt: DateTime
  latestProcessedBlock: Int!
  stableswapHistDataLatestBlock: Int
  omnipoolHistDataLatestBlock: Int
  xykpoolHistDataLatestBlock: Int
  aavepoolHistDataLatestBlock: Int
}

# ======================================================================================================================
# *** Preprocessed Data Heap ***
# ======================================================================================================================

type PreprocessedDataBucket @entity {
  "<uuid>"
  id: ID!
  processorId: String!
  paraBlockHeight: Int!
  entityName: String!
  data: JSON!
}

# ======================================================================================================================
# *** Asset ***
# ======================================================================================================================

enum AssetType {
  Bond
  External
  StableSwap
  Token
  XYK
  Erc20
  PoolShare
}
enum ResourceType {
  Underlying
  Collateral
  Debt
}

type Asset @entity {
  "assetRegistry ID or actual contract EVM address (e.g. 0xc64980e4eaf9a1151bd21712b9946b81e41e2b92 || 10)"
  id: ID!
  "Hydration AssetRegistry ID"
  assetRegistryId: String @index
  "real EVM contract address"
  evmAddress: String
  "list of all asset ids from current and other chains related with this Asset"
  multiLocationIds: [String]
  "list of all asset multi-locations from current and other chains related with this Asset"
  multiLocationsMetadata: [AssetMultiLocation]
  multiLocations: [AssetMultiLocation]

  underlyingAssetId: String
  aTokenId: String
  variableDebtTokenId: String
  bondUnderlyingAssetId: String

  assetType: AssetType!
  resourceType: ResourceType!
  name: String
  symbol: String
  decimals: Int
  xcmRateLimit: BigInt
  isSufficient: Boolean!
  existentialDeposit: BigInt!
  bondMaturity: BigInt

  # note: existentialDeposit is probably taken 1:1 from the runtime,
  # real existential deposit will be calculated realtime based on the current price
}

enum AssetMultiLocationsInteriorKind {
  AccountId32
  AccountIndex64
  AccountKey20
  GeneralIndex
  GeneralKey
  GlobalConsensus
  OnlyChild
  PalletInstance
  Parachain
  Plurality
}

type AssetMultiLocationsInterior {
  kind: AssetMultiLocationsInteriorKind!
  network: String
  id: String
  index: String
  key: String
  value: String
  valueJson: JSON
  data: String
  part: String
  nom: String
  denom: String
  count: String
  blockNumber: String
  blockHash: String
  chainId: String
}

type AssetMultiLocation {
  parents: Int!
  "Here | X1 | X2 | X3 | X4 | X5 | X6 | X7 | X8"
  hierarchyLevel: String!
  interior: [AssetMultiLocationsInterior!]!
}

type AssetVolumeHistoricalData @entity {
  "<assetId>-<paraBlockHeight>"
  id: ID!
  assetId: String!
  volumeIn: BigInt!
  volumeOut: BigInt!
  totalVolumeIn: BigInt!
  totalVolumeOut: BigInt!
  totalVolumeInNorm: String!
  totalVolumeOutNorm: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AssetSwapFeeHistoricalData @entity {
  "<assetId>-<paraBlockHeight>"
  id: ID!
  assetId: String!
  amount: BigInt!
  totalAmount: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AssetSpotPriceHistoricalData @entity {
  "<assetInId>-<assetOutId>-<paraBlockHeight>"
  id: ID!
  assetInHistData: AssetHistoricalData!
  assetInId: String!
  assetOutId: String!
  assetInAssetRegistryId: String
  assetOutAssetRegistryId: String

  assetOutDecimals: Int!
  price: BigInt!
  priceNormalised: String!
  #  priceRoute is a list of tupes with following values: pool address, pool type, assetIn, assetOut in appropriate order of swap
  #  [ [<pool_address>, <pool_type>, <asset_in_id>, <asset_out_id>] ]
  priceRoute: [[String!]!]!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AssetDynamicFee {
  assetFee: Int!
  protocolFee: Int!
  timestamp: Int!
}


type AssetHistoricalData @entity {
  "<assetId>-<paraBlockHeight>"
  id: ID!
  assetId: String!

  totalIssuance: BigInt!
  dynamicFee: AssetDynamicFee

  usdPriceNormalised: String!
  spotPrices: [AssetSpotPriceHistoricalData]!
    @derivedFrom(field: "assetInHistData")
  assetPairVolumes: [AssetAssetsPairVolume]!
    @derivedFrom(field: "assetHistoricalData")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AssetsPairVolumeHistoricalData @entity {
  "<assetAId>-<assetBId>-<paraBlockHeight>"
  id: ID!

  assetAId: String!
  assetRegistryAId: String!

  assetBId: String!
  assetRegistryBId: String!

  assetAVolume: BigInt!
  assetBVolume: BigInt!
  "totalVolumeNormalised is calculated in base asset (10:USDT) and normalised to decimal format"
  totalVolumeNormalised: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AssetAssetsPairVolume @entity {
  "<assetHistoricalDataId>-<assetsPairVolumeHistoricalData>-<paraBlockHeight>"
  id: ID!
  assetHistoricalData: AssetHistoricalData!
  assetsPairVolumeHistoricalData: AssetsPairVolumeHistoricalData!
  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Account ***
# ======================================================================================================================

enum AccountType {
  User
  Omnipool
  Stableswap
  Xykpool
  Lbppool
  Hsmpool
}

type AccountAssetBalanceHistoricalData @entity {
  "<address>-<assetId>-<paraBlockHeight>"
  id: ID!
  accountId: String!
  assetId: String!

  "free property in storage"
  transferable: BigInt!
  "reserved property in storage"
  totalLocked: BigInt!

  transferableInRefAssetNorm: String
  totalLockedInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AccountAssetBalanceLatest @entity {
  "<address>-<assetId>"
  id: ID!
  accountId: String! @index
  assetId: String! @index

  transferable: BigInt!
  totalLocked: BigInt!

  transferableInRefAssetNorm: String
  totalLockedInRefAssetNorm: String

  total: BigInt! @index

  paraBlockHeight: Int!
  blockId: String!
}

type AccountTotalBalanceHistoricalData @entity {
  "<address>-<paraBlockHeight>"
  id: ID!
  accountId: String!
  refAssetId: String!

  totalTransferableNorm: String!
  totalLockedNorm: String!
  totalDebtNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AccountMmPositionHistoricalData @entity {
  "<address>-<paraBlockHeight>"
  id: ID!
  accountId: String!
  accountBoundEvmAddress: String

  totalCollateralBase: String!
  totalDebtBase: String!
  availableBorrowsBase: String!
  currentLiquidationThreshold: String!
  ltv: String!
  healthFactor: String
  poolAddress: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type Account @entity {
  "<address>"
  id: ID!
  accountType: AccountType!

  boundEvmAddress: String
  evmAddressBoundEvent: Event

  lbppool: Lbppool
  xykpool: Xykpool
  omnipool: Omnipool
  stableswap: Stableswap
  hsmpool: Hsmpool

  initiatedActions: [ChainActivityTrace!] @derivedFrom(field: "originator")
  participatedActions: [AccountChainActivityTrace!]
    @derivedFrom(field: "account")

  dcaSchedules: [DcaSchedule!] @derivedFrom(field: "owner")
  otcOrders: [OtcOrder!] @derivedFrom(field: "owner")

  # TODO: add proxy and multisig tracking
}

type AccountAssetSwapFeeHistoricalData @entity {
  "<historicalAccountSwapFeeId>-<paraBlockHeight>"
  id: ID!
  collection: AccountSwapFeeHistoricalData!
  accountId: String!
  assetId: String!

  amount: BigInt!
  totalAmount: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AccountSwapFeeHistoricalData @entity {
  "<address>-<paraBlockHeight>"
  id: ID!
  accountId: String!
  fees: [AccountAssetSwapFeeHistoricalData!]! @derivedFrom(field: "collection")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** Chain Activity Tracing ***
# ======================================================================================================================

enum TraceEntityType {
  Swap
  Transfer
  StableswapLiquidityEvent
  OtcOrderEvent
  DcaSchedule
  DcaScheduleExecutionEvent
}

type Block @entity {
  "<blockHeight>-<blockHash prefix> e.g. 0003396328-70ca4"
  id: ID!
  extrinsics: [Extrinsic] @derivedFrom(field: "block")
  calls: [Call] @derivedFrom(field: "block")
  events: [Event] @derivedFrom(field: "block")
  chainActivityTraces: [ChainActivityTrace] @derivedFrom(field: "block")

  height: Int! @index
  hash: String! @index
  timestamp: DateTime! @index

  relayBlockHeight: Int!
}

type Extrinsic @entity {
  "<blockHeight>-<blockHash prefix>-<indexInBlock> e.g. 0000065722-4721a-000002"
  id: ID!
  hash: String!
  indexInBlock: Int!
  calls: [Call] @derivedFrom(field: "extrinsic")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  block: Block!
}

type Call @entity {
  # <blockHeight>-<blockHash prefix>-<extrinsicIndexInBlock>
  #     in case extrinsic contains single call without subcalls
  #     (e.g. 0000172149-553f2-000002)
  # or
  # <blockHeight>-<blockHash prefix>-<extrinsicIndexInBlock>-<callIndexInParentCall>
  #     in case extrinsic contains multiple calls or single call with sub-calls
  #     (e.g. 0000172149-553f2-000002-000000)
  id: ID!
  traceId: String!

  args: String
  success: Boolean
  name: String!
  originKind: String!
  originValueKind: String
  originValue: String
  entityTypes: [TraceEntityType]

  subcalls: [Call] @derivedFrom(field: "parent")
  events: [Event] @derivedFrom(field: "call")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  block: Block!
  extrinsic: Extrinsic!
  parent: Call
}

enum EventGroup {
  Extrinsic
  Initialization
  Finalization
  Buyback
  Dca
}

type Event @entity {
  "<blockHeight>-<blockHashPrefix>-<indexInBlock> (e.g. 0000059948-e5832-000007)"
  id: ID!
  traceId: String!

  args: String
  indexInBlock: Int!
  name: String!
  group: EventGroup
  phase: String!
  entityTypes: [TraceEntityType]

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  block: Block!
  call: Call
}

type ChainActivityTrace @entity {
  # "<extrinsicId> where particular ChainActivityTrace has bee initialised"
  # or
  # <blockHeight>-<TraceIdEventGroup> where eventGroup can be <ext | initForBlocksBatch | fin>
  id: ID!

  #  Batch:1419/Router:1420/Omnipool:1421
  #  Omnipool:20554
  operationIds: [String!]

  #  There is no id for specific entity. This trace id can be used for multiple DB entities.
  #  trace-id://context:<call>/<extrinsic_id>/<call_id>/<call_id>/<call_id>
  #  trace-id://context:<event>/<block_id>:<group_name>/<event_index>

  #  trace-id://context:call/0003396328-000002-70ca4/0003396328-000002-70ca4-000002/0003396328-000002-70ca4-000003/0003681428-fa806-000020
  #  trace-id://context:event/0003396328-70ca4:buyback/2
  traceIds: [String!]!

  # account who signed initial call of the extrinsic
  originator: Account

  #  list of participant addresses to particular ChainActivityTrace
  participants: [AccountChainActivityTrace!]!
    @derivedFrom(field: "chainActivityTrace")

  # Scope of all accounts involved into particular activity trace. Required for easier filtering on API side.
  participantAccounts: [String!]! # associatedAccountsFlat -> participantAccounts
  childTraces: [ChainActivityTraceRelation] @derivedFrom(field: "parentTrace")
  parentTraces: [ChainActivityTraceRelation] @derivedFrom(field: "childTrace")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  block: Block!
}

type AccountChainActivityTrace @entity {
  # <address>-<chainActivityTraceId>
  id: ID!
  account: Account!
  chainActivityTrace: ChainActivityTrace!
}

type ChainActivityTraceRelation @entity {
  "<parentTraceId>-<childTraceId>"
  id: ID!

  parentTrace: ChainActivityTrace!
  childTrace: ChainActivityTrace!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  block: Block!
}

# ======================================================================================================================
# *** Transfer ***
# ======================================================================================================================

type Transfer @entity {
  "<eventId> (e.g. 0000059948-e5832-000007)"
  id: ID!
  traceIds: [String!]

  assetId: String!
  assetType: AssetType!

  fromId: String! # from Account
  toId: String! # to Account
  amount: BigInt!
  txFee: BigInt!

  paraTimestamp: DateTime! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

# ======================================================================================================================
# *** Swapped - Unified Trade event ***
# ======================================================================================================================
enum SwapAssetBalanceType {
  Input
  Output
}

enum SwapFeeDestinationType {
  Account
  Burned
}

enum SwapFillerType {
  Omnipool
  Stableswap
  XYK
  LBP
  OTC
  AAVE
  HSM
}

enum TradeOperationType {
  ExactIn
  ExactOut
  ExactLimitIn
  ExactLimitOut
  LiquidityAdd
  LiquidityRemove
}

type SwapFee @entity {
  "<swapId>-<assetId>-<recipientId || destinationType> e.g. 0006516718-9965d-000107-0"
  id: ID!
  swap: Swap!
  assetId: String!
  amount: BigInt!
  destinationType: SwapFeeDestinationType!
  recipientId: String
}


type SwapAssetBalance @entity {
  "<swapId>-<assetId>-<SwapAssetBalanceType> e.g. 0006516718-9965d-000107-0-INPUT"
  id: ID!
  swap: Swap!
  assetBalanceType: SwapAssetBalanceType!
  assetId: String!
  amount: BigInt!
}

type Swap @entity {
  "<eventId> (e.g. 0006516718-9965d-000107)"
  id: ID!
  operationId: String
  traceIds: [String!]
  swapIndex: Int

  swapperId: String! # Account Id!
  fillerId: String! # Account Id!
  fillerType: SwapFillerType!
  operationType: TradeOperationType!

  inputs: [SwapAssetBalance!]! @derivedFrom(field: "swap")
  outputs: [SwapAssetBalance!]! @derivedFrom(field: "swap")
  fees: [SwapFee!]! @derivedFrom(field: "swap")

  "List of all asset IDs involved in the swap, including those used for fees."
  allInvolvedAssetIds: [String!]!
  allInvolvedAssetRegistryIds: [String!]!

  dcaScheduleExecutionEvent: DcaScheduleExecutionEvent
  otcOrderFulfillment: OtcOrderEvent
  routedTrade: RoutedTrade

  paraTimestamp: DateTime! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type RoutedTradeAssetBalance @entity {
  "<routeTradeId>-<assetId>-<SwapAssetBalanceType> e.g. 6516718-3094-0-INPUT"
  id: ID!
  routedTrade: RoutedTrade!
  assetBalanceType: SwapAssetBalanceType!
  assetId: String!
  amount: BigInt!
}

type RoutedTrade @entity {
  "<blockHeight>-<routerIncrementalId || swapId> (e.g. 6516718-3094 || 6516718-0006516718-9965d-000107)"
  id: ID!
  routeId: String
  inputs: [RoutedTradeAssetBalance] @derivedFrom(field: "routedTrade")
  outputs: [RoutedTradeAssetBalance] @derivedFrom(field: "routedTrade")

  inputAssetIds: [String!]!
  inputAssetRegistryIds: [String!]!
  outputAssetIds: [String!]!
  outputAssetRegistryIds: [String!]!

  allInvolvedAssetIds: [String!]!
  allInvolvedAssetRegistryIds: [String!]!
  participantSwappers: [String!]!
  participantFillers: [String!]!
  feeRecipients: [String!]!
  swaps: [Swap!]! @derivedFrom(field: "routedTrade")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** LBP Pool ***
# ======================================================================================================================

type Lbppool @entity {
  "<poolAccountAddress>"
  id: ID!

  accountId: String!
  assetAId: String!
  assetBId: String!
  assetABalance: BigInt!
  assetBBalance: BigInt!
  ownerId: String
  feeCollectorId: String
  startBlockNumber: Int
  endBlockNumber: Int
  initialWeight: Int
  finalWeight: Int
  fee: [Int]
  repayTarget: BigInt

  createdAtParaBlockHeight: Int! @index
  createdAtRelayBlockHeight: Int!
  createdAtBlockId: String
  isDestroyed: Boolean
  lifeStates: [LbppoolLifeState!]!

  historicalBlockPrices: [LbppoolPriceHistoricalData!]!
    @derivedFrom(field: "pool")
  historicalVolume: [LbppoolVolumeHistoricalData!]! @derivedFrom(field: "pool")
  historicalData: [LbppoolHistoricalData!]! @derivedFrom(field: "pool")
}

type LbppoolCreatedData {
  assetABalance: String!
  assetBBalance: String!
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}
type LbppoolDestroyedData {
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}

type LbppoolLifeState {
  created: LbppoolCreatedData!
  destroyed: LbppoolDestroyedData
}

type LbppoolPriceHistoricalData @entity {
  "<lbppoolId>-<paraBlockHeight>"
  id: ID!
  pool: Lbppool!
  assetAId: String!
  assetBId: String!
  assetABalance: BigInt!
  assetBBalance: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type LbppoolVolumeHistoricalData @entity {
  "PoolId-paraBlockHeight"
  id: ID!
  pool: Lbppool!

  assetAId: String!
  assetBId: String!
  averagePrice: Float!

  assetAVolIn: BigInt!
  assetAVolOut: BigInt!
  assetATotalVolIn: BigInt!
  assetATotalVolOut: BigInt!

  assetAFeeVol: BigInt!
  assetBFeeVol: BigInt!
  assetAFeesTotalVol: BigInt!
  assetBFeesTotalVol: BigInt!

  assetBVolIn: BigInt!
  assetBVolOut: BigInt!
  assetBTotalVolIn: BigInt!
  assetBTotalVolOut: BigInt!

  assetAVolInNorm: String!
  assetAVolOutNorm: String!
  assetBVolInNorm: String!
  assetBVolOutNorm: String!
  assetAFeeVolNorm: String!
  assetBFeeVolNorm: String!

  assetATotalVolInNorm: String!
  assetATotalVolOutNorm: String!
  assetBTotalVolInNorm: String!
  assetBTotalVolOutNorm: String!
  assetAFeesTotalVolNorm: String!
  assetBFeesTotalVolNorm: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

#
# BatchLbppoolHistVolsList is a support entity for the LbppoolVolumeHistoricalData API subscription.
# It contains all LBP pool IDs involved in volume aggregations (LbppoolVolumeHistoricalData)
# within a single indexer blocks batch, which may consist of one or more blocks. Since the processor saves all
# processed data from a batch of blocks in a single database transaction, this entity may include IDs from multiple
# blocks. This approach ensures that the subscription event is triggered only after all volume entities in the batch
# are saved, rather than after each individual volume aggregation, optimizing event handling and consistency.
#
type BatchLbppoolHistVolsList @entity {
  "<batchStartParaBlockHeight> (e.g. 101312)"
  id: ID!
  poolIds: [String!]

  batchStartParaBlockHeight: Int! @index
  batchEndParaBlockHeight: Int! @index
}

type LbppoolHistoricalData @entity {
  "poolAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Lbppool!

  assetAId: String!
  assetBId: String!
  assetABalance: BigInt!
  assetBBalance: BigInt!
  ownerId: String!
  feeCollectorId: String
  startBlockNumber: Int
  endBlockNumber: Int
  initialWeight: Int!
  finalWeight: Int!
  repayTarget: BigInt!
  weightCurve: String!
  fee: [Int!]!

  tvlInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** XYK Pool ***
# ======================================================================================================================

type Xykpool @entity {
  "<address>"
  id: ID!

  accountId: String!
  assetAId: String!
  assetBId: String!
  assetABalance: BigInt!
  assetBBalance: BigInt!
  shareTokenId: String!
  tvlInRefAssetNorm: String

  createdAtParaBlockHeight: Int! @index
  createdAtRelayBlockHeight: Int!
  createdAtBlockId: String
  isDestroyed: Boolean
  lifeStates: [XykpoolLifeState!]!

  historicalBlockPrices: [XykpoolPriceHistoricalData!]!
    @derivedFrom(field: "pool")
  historicalVolume: [XykpoolVolumeHistoricalData!]! @derivedFrom(field: "pool")
  historicalData: [XykpoolHistoricalData!]! @derivedFrom(field: "pool")
}

type XykpoolCreatedData {
  initialSharesAmount: String!
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}
type XykpoolDestroyedData {
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}

type XykpoolLifeState {
  created: XykpoolCreatedData!
  destroyed: XykpoolDestroyedData
}

type XykpoolPriceHistoricalData @entity {
  "PoolId-paraBlockHeight"
  id: ID!
  pool: Xykpool!
  assetAId: String!
  assetBId: String!
  assetABalance: BigInt!
  assetBBalance: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type XykpoolVolumeHistoricalData @entity {
  "PoolId-paraBlockHeight"
  id: ID!
  pool: Xykpool!

  assetAId: String!
  assetBId: String!
  averagePrice: Float!

  assetAVolIn: BigInt!
  assetAVolOut: BigInt!
  assetATotalVolIn: BigInt!
  assetATotalVolOut: BigInt!

  assetAFeeVol: BigInt!
  assetBFeeVol: BigInt!

  assetAFeesTotalVol: BigInt!
  assetBFeesTotalVol: BigInt!

  assetBVolIn: BigInt!
  assetBVolOut: BigInt!
  assetBTotalVolIn: BigInt!
  assetBTotalVolOut: BigInt!

  assetAVolInNorm: String!
  assetAVolOutNorm: String!
  assetBVolInNorm: String!
  assetBVolOutNorm: String!
  assetAFeeVolNorm: String!
  assetBFeeVolNorm: String!

  assetATotalVolInNorm: String!
  assetATotalVolOutNorm: String!
  assetBTotalVolInNorm: String!
  assetBTotalVolOutNorm: String!
  assetAFeesTotalVolNorm: String!
  assetBFeesTotalVolNorm: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

#
# BatchXykpoolHistVolsList is a support entity for the XykpoolVolumeHistoricalData API subscription.
# It contains all XYK pool IDs involved in volume aggregations (XykpoolVolumeHistoricalData)
# within a single indexer blocks batch, which may consist of one or more blocks. Since the processor saves all
# processed data from a batch of blocks in a single database transaction, this entity may include IDs from multiple
# blocks. This approach ensures that the subscription event is triggered only after all volume entities in the batch
# are saved, rather than after each individual volume aggregation, optimizing event handling and consistency.
#
type BatchXykpoolHistVolsList @entity {
  "<batchStartParaBlockHeight> (e.g. 101312)"
  id: ID!
  poolIds: [String!]

  batchStartParaBlockHeight: Int! @index
  batchEndParaBlockHeight: Int! @index
}

type XykpoolHistoricalData @entity {
  "poolAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Xykpool!

  assetAId: String!
  assetBId: String!
  assetABalance: BigInt!
  assetBBalance: BigInt!
  tvlInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** Omnipool ***
# ======================================================================================================================

type Omnipool @entity {
  id: ID!
  account: Account!

  isDestroyed: Boolean
  destroyedAtParaBlockHeight: Int

  assets: [OmnipoolAsset!]! @derivedFrom(field: "pool")
}

type OmnipoolAsset @entity {
  "<omnipoolId>-<assetId> (e.g. 0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000-100)"
  id: ID!

  pool: Omnipool!
  assetId: String!

  addedAtParaBlockHeight: Int! @index
  addedAtRelayBlockHeight: Int!
  isRemoved: Boolean
  addedAtBlockId: String
  lifeStates: [OmnipoolAssetLifeState!]

  historicalVolume: [OmnipoolAssetVolumeHistoricalData!]!
    @derivedFrom(field: "omnipoolAsset")
  historicalData: [OmnipoolAssetHistoricalData!]!
    @derivedFrom(field: "omnipoolAsset")
}

type OmnipoolAssetAddedData {
  initialAmount: String
  initialPrice: String
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}
type OmnipoolAssetRemovedData {
  removedAmount: String
  hubWithdrawn: String
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}

type OmnipoolAssetLifeState {
  added: OmnipoolAssetAddedData!
  removed: OmnipoolAssetRemovedData
}

type OmnipoolAssetVolumeHistoricalData @entity {
  "<omnipoolAssetId>-<paraBlockHeight> (e.g. 0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000-0-101312)"
  id: ID!
  omnipoolAsset: OmnipoolAsset!
  assetVolIn: BigInt!
  assetVolOut: BigInt!
  assetTotalVolIn: BigInt!
  assetTotalVolOut: BigInt!
  assetFeeVol: BigInt!
  assetTotalFeesVol: BigInt!

  assetVolInNorm: String!
  assetVolOutNorm: String!
  assetFeeVolNorm: String!
  assetTotalVolInNorm: String!
  assetTotalVolOutNorm: String!
  assetTotalFeesVolNorm: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

#
# BatchOmnipoolAssetHistVolsList is a support entity for the OmnipoolAssetHistoricalVolumeByPeriod API subscription.
# It contains all OmnipoolAsset IDs and Asset IDs involved in volume aggregations (OmnipoolAssetVolumeHistoricalData)
# within a single indexer blocks batch, which may consist of one or more blocks. Since the processor saves all
# processed data from a batch of blocks in a single database transaction, this entity may include IDs from multiple
# blocks. This approach ensures that the subscription event is triggered only after all volume entities in the batch
# are saved, rather than after each individual volume aggregation, optimizing event handling and consistency.
#
type BatchOmnipoolAssetHistVolsList @entity {
  "<batchStartParaBlockHeight> (e.g. 101312)"
  id: ID!
  omnipoolAssetIds: [String!]
  assetIds: [String!]

  batchStartParaBlockHeight: Int! @index
  batchEndParaBlockHeight: Int! @index
}

type OmnipoolHistoricalData @entity {
  "<omnipoolId>-<paraBlockHeight> (e.g. 0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000-101312)"
  id: ID!
  pool: Omnipool!
  assetsHistoricalData: [OmnipoolAssetHistoricalData!]!
    @derivedFrom(field: "poolHistoricalData")
  tvlTotalInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type OmnipoolAssetHistoricalData @entity {
  "<omnipoolAssetId>-<paraBlockHeight> (e.g. 0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000-0-101312)"
  id: ID!
  poolHistoricalData: OmnipoolHistoricalData!
  omnipoolAsset: OmnipoolAsset!
  assetId: String!

  assetCap: BigInt!
  assetShares: BigInt!
  assetHubReserve: BigInt!
  assetProtocolShares: BigInt!
  freeBalance: BigInt!
  tradable: Int!
  tvlInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** Stableswap ***
# ======================================================================================================================

type Stableswap @entity {
  "poolId - share token ID (e.g. 102)"
  id: ID!
  account: Account!
  shareTokenId: String!

  createdAtParaBlockHeight: Int! @index
  createdAtRelayBlockHeight: Int!
  createdAtBlockId: String
  isDestroyed: Boolean
  lifeStates: [StableswapLifeState!]!

  assets: [StableswapAsset!]! @derivedFrom(field: "pool")
}

type StableswapCreatedData {
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}
type StableswapDestroyedData {
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}

type StableswapLifeState {
  created: StableswapCreatedData!
  destroyed: StableswapDestroyedData
}

type StableswapAsset @entity {
  "<stableswapId>-<assetId> (e.g. 101-19)"
  id: ID!
  pool: Stableswap!
  assetId: String!
  amount: BigInt!
}

type StableswapVolumeHistoricalData @entity {
  "<stableswapId>-<paraBlockHeight>"
  id: ID!
  pool: Stableswap!
  assetVolumes: [StableswapAssetVolumeHistoricalData!]!
    @derivedFrom(field: "volumesCollection")

  poolVolInNorm: String!
  poolVolOutNorm: String!
  poolFeesVolNorm: String!
  poolTotalVolInNorm: String!
  poolTotalVolOutNorm: String!
  poolTotalFeesVolNorm: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type StableswapAssetVolumeHistoricalData @entity {
  "<stableswapId>-<assetId>-<paraBlockHeight> (e.g. 100-10-101332)"
  id: ID!
  volumesCollection: StableswapVolumeHistoricalData!
  assetId: String!

  assetFeeVol: BigInt!
  assetTotalFeesVol: BigInt!
  assetVolIn: BigInt!
  assetVolOut: BigInt!
  assetTotalVolIn: BigInt!
  assetTotalVolOut: BigInt!

  assetVolInNorm: String!
  assetVolOutNorm: String!
  assetFeeVolNorm: String!
  assetTotalVolInNorm: String!
  assetTotalVolOutNorm: String!
  assetTotalFeesVolNorm: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

#
# BatchStableswapHistVolsList is a support entity for the StableswapAssetVolumeHistoricalData API subscription.
# It contains all Stableswap pool IDs involved in volume aggregations (StableswapAssetVolumeHistoricalData)
# within a single indexer blocks batch, which may consist of one or more blocks. Since the processor saves all
# processed data from a batch of blocks in a single database transaction, this entity may include IDs from multiple
# blocks. This approach ensures that the subscription event is triggered only after all volume entities in the batch
# are saved, rather than after each individual volume aggregation, optimizing event handling and consistency.
#
type BatchStableswapHistVolsList @entity {
  "<batchStartParaBlockHeight> (e.g. 101312)"
  id: ID!
  poolIds: [String!]

  batchStartParaBlockHeight: Int! @index
  batchEndParaBlockHeight: Int! @index
}

type StableswapLiquidityEvent @entity {
  "<stableswapId>-<eventId>"
  id: ID!
  traceIds: [String!]

  pool: Stableswap!

  sharesAmount: BigInt!
  feeAmount: BigInt!
  assetAmounts: [StableswapAssetLiquidityAmount!]!
    @derivedFrom(field: "liquidityAction")
  actionType: LiquidityActionEvent!

  indexInBlock: Int! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type StableswapAssetLiquidityAmount @entity {
  "<stableswapId>-<eventId>-<assetId>"
  id: ID!
  liquidityAction: StableswapLiquidityEvent!
  assetId: String!
  amount: BigInt!
}

type StableswapPegsSource {
  sourceKind: String! # Oracle | Value
  oracleName: String
  oraclePeriod: EmaOraclePeriod
  oracleAsset: String
  valuePoints: [String!]
}

type StableswapHistoricalData @entity {
  "<stableswapId>-<paraBlockHeight>"
  id: ID!
  pool: Stableswap!
  assetsHistoricalData: [StableswapAssetHistoricalData!]!
    @derivedFrom(field: "poolHistoricalData")

  initialAmplification: Int!
  finalAmplification: Int!
  initialAmplificationChangeAtBlockHeight: Int!
  finalAmplificationChangeAtBlockHeight: Int!
  fee: Int!
  pegs: [[BigInt!]!]!
  maxPegUpdate: Int
  pegSources: [StableswapPegsSource!]
  tvlTotalInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type StableswapAssetHistoricalData @entity {
  "<stablepoolId>-<assetId>-<paraBlockHeight>"
  id: ID!
  assetId: String!
  stableswapAsset: StableswapAsset!
  poolHistoricalData: StableswapHistoricalData!
  freeBalance: BigInt!
  tradable: Int
  tvlInRefAssetNorm: String

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** HSM pool ***
# ======================================================================================================================

type Hsmpool @entity {
  "poolId"
  id: ID!
  account: Account!
  facilitator: AaveFacilitator!

  collaterals: [HsmCollateral!]! @derivedFrom(field: "pool")
}

type HsmCollateral @entity {
  "<hsmpool_address>-<colateral_id>"
  id: ID!
  pool: Hsmpool!
  assetId: String!
  stableswap: Stableswap!
  isRemoved: Boolean!
}

type HsmpoolHistoricalData @entity {
  "<hsm_collateral_id>-<block_height>"
  id: ID!
  pool: Hsmpool!

  bucketCapacity: BigInt!
  bucketLevel: BigInt!

  paraTimestamp: DateTime! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type HsmCollateralConfigHistoricalData @entity {
  "<hsm_collateral_id>-<block_height>"
  id: ID!
  collateral: HsmCollateral!

  purchaseFee: BigInt!
  maxBuyPriceCoefficient: BigInt!
  buybackRate: BigInt!
  buyBackFee: BigInt!
  maxInHolding: BigInt!

  paraTimestamp: DateTime! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type HsmpoolAssetHistoricalData @entity {
  "<asset_id>-<block_height>"
  id: ID!
  assetId: String!
  "Can be null if snapshot is for Hollar"
  collateral: HsmCollateral
  "Actual only for Hollar asset as Hsm pool doesn't have any balance of Hollar"
  facilitatorHistData: AaveFacilitatorHistoricalData

  "Can be 0 for Hollar as HSM pool "
  freeBalance: BigInt!
  tvlInRefAssetNorm: String

  assetVolIn: BigInt!
  assetVolOut: BigInt!
  assetFeeVol: BigInt!

  assetTotalVolIn: BigInt!
  assetTotalVolOut: BigInt!
  assetTotalFeesVol: BigInt!

  assetVolInNorm: String!
  assetVolOutNorm: String!
  assetFeeVolNorm: String!

  assetTotalVolInNorm: String!
  assetTotalVolOutNorm: String!
  assetTotalFeesVolNorm: String!

  paraTimestamp: DateTime! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type AaveFacilitator @entity {
  "<facilitator_h160_address>"
  id: ID!
  label: String!
  isRemoved: Boolean!
}

type AaveFacilitatorHistoricalData @entity {
  "<facilitator_h160_address>-<block_height>"
  id: ID!
  facilitator: AaveFacilitator!

  bucketCapacity: BigInt!
  bucketLevel: BigInt!

  paraTimestamp: DateTime! @index
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

#
# BatchHsmpoolAssetHistVolsList is a support entity for the OmnipoolAssetHistoricalVolumeByPeriod API subscription.
# It contains all OmnipoolAsset IDs and Asset IDs involved in volume aggregations (OmnipoolAssetVolumeHistoricalData)
# within a single indexer blocks batch, which may consist of one or more blocks. Since the processor saves all
# processed data from a batch of blocks in a single database transaction, this entity may include IDs from multiple
# blocks. This approach ensures that the subscription event is triggered only after all volume entities in the batch
# are saved, rather than after each individual volume aggregation, optimizing event handling and consistency.
#
type BatchHsmpoolAssetHistVolsList @entity {
  "<batchStartParaBlockHeight> (e.g. 101312)"
  id: ID!
  assetIds: [String!]

  batchStartParaBlockHeight: Int! @index
  batchEndParaBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Constants ***
# ======================================================================================================================

type DynamicFeesAssetFeeParameters {
  minFee: Int!
  maxFee: Int!
  decay: String!
  amplification: String!
}

type ConstantsHistoricalData @entity {
  "<paraBlockHeight>"
  id: ID!

  lbpRepayFee: [Int!]
  lbpMaxInRatio: BigInt
  lbpMaxOutRatio: BigInt
  lbpMinPoolLiquidity: BigInt
  lbpMinTradingLimit: BigInt

  omnipoolBurnProtocolFee: Int
  omnipoolHdxAssetId: Int
  omnipoolHubAssetId: Int
  omnipoolMaxInRatio: BigInt
  omnipoolMaxOutRatio: BigInt
  omnipoolMinimumPoolLiquidity: BigInt
  omnipoolMinimumTradingLimit: BigInt
  omnipoolMinWithdrawalFee: Int

  stableswapMinTradingLimit: BigInt
  stableswapMinPoolLiquidity: BigInt
  stableswapAmplificationRange: [Int!]

  xykGetExchangeFee: [Int!]
  xykMaxInRatio: BigInt
  xykMaxOutRatio: BigInt
  xykMinPoolLiquidity: BigInt
  xykMinTradingLimit: BigInt
  xykNativeAssetId: Int
  xykOracleSource: String

  dynamicFeesAssetFeeParameters: DynamicFeesAssetFeeParameters
  dynamicFeesProtocolFeeParameters: DynamicFeesAssetFeeParameters

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** Ema Oracle ***
# ======================================================================================================================

enum EmaOraclePeriod {
  Day
  Hour
  LastBlock
  Short
  TenMinutes
  Week
}

type EmaOracleEntryHistoricalData @entity {
  "<paraBlockHeight>-<assetAId>-<assetBId>-<source>-<period>"
  id: ID!

  assetAId: String!
  assetBId: String!

  assetAAssetRegistryId: String!
  assetBAssetRegistryId: String!

  source: String! @index
  period: EmaOraclePeriod!

  numeratorPrice: BigInt!
  denominatorPrice: BigInt!
  assetAInVolume: BigInt!
  assetAOutVolume: BigInt!
  assetBInVolume: BigInt!
  assetBOutVolume: BigInt!
  assetALiquidity: BigInt!
  assetBLiquidity: BigInt!

  updatedAtParaBlockHeight: Int!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** DCA ***
# ======================================================================================================================

enum DcaScheduleOrderType {
  Buy
  Sell
}

enum DcaScheduleStatus {
  Created
  Completed
  Terminated
}

enum DcaScheduleExecutionStatus {
  Planned
  Executed
  Failed
}

type DispatchError {
  kind: String
  index: Int
  error: String
}

type DcaSchedule @entity {
  "<scheduleId> - DCA schedule as a string"
  id: ID!
  operationId: String
  traceIds: [String!]

  status: DcaScheduleStatus @index
  owner: Account!
  startExecutionBlock: Int
  period: Int
  totalAmount: BigInt
  slippage: Int
  maxRetries: Int
  stabilityThreshold: Int

  totalExecutedAmountIn: BigInt
  totalExecutedAmountOut: BigInt

  assetInId: String
  amountIn: BigInt
  maxAmountIn: BigInt
  assetOutId: String
  amountOut: BigInt
  minAmountOut: BigInt
  orderType: DcaScheduleOrderType!
  orderRouteHops: [DcaScheduleOrderRouteHop] @derivedFrom(field: "schedule")
  executions: [DcaScheduleExecution] @derivedFrom(field: "schedule")
  events: [DcaScheduleEvent!]! @derivedFrom(field: "schedule")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type DcaScheduleOrderRouteHop @entity {
  "<dcaScheduleId>-<assetInId>-<assetOutId>"
  id: ID!
  schedule: DcaSchedule!
  poolKind: SwapFillerType
  assetInId: String
  assetOutId: String
}

type DcaScheduleEvent @entity {
  "<dcaScheduleId>-<eventId>"
  id: ID!
  traceIds: [String!]
  schedule: DcaSchedule!
  eventName: DcaScheduleStatus! @index
  errorState: DispatchError

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type DcaScheduleExecution @entity {
  "<dcaScheduleId>-<blockHeight>"
  id: ID!
  schedule: DcaSchedule!
  status: DcaScheduleExecutionStatus @index
  amountOut: BigInt
  amountIn: BigInt
  events: [DcaScheduleExecutionEvent] @derivedFrom(field: "scheduleExecution")
}

type DcaScheduleExecutionEvent @entity {
  "<dcaScheduleExecutionId>-<dcaScheduleExecutionStatus>"
  id: ID!
  operationIds: [String]
  traceIds: [String!]
  scheduleExecution: DcaScheduleExecution!

  swaps: [Swap] @derivedFrom(field: "dcaScheduleExecutionEvent")
  eventName: DcaScheduleExecutionStatus @index
  errorState: DispatchError

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

# ======================================================================================================================
# *** OTC ***
# ======================================================================================================================

enum OtcOrderStatus {
  Created
  Cancelled
  Filled
  PartiallyFilled
}

type OtcOrder @entity {
  "<orderId> as string"
  id: ID!

  owner: Account!
  assetInId: String!
  assetOutId: String!
  amountOut: BigInt!
  amountIn: BigInt!
  partiallyFillable: Boolean
  status: OtcOrderStatus @index

  totalFilledAmountIn: BigInt
  totalFilledAmountOut: BigInt

  events: [OtcOrderEvent] @derivedFrom(field: "order")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type OtcOrderEvent @entity {
  "<otc_order_id>-<event_id>"
  id: ID!
  operationId: String @index
  traceIds: [String!]
  order: OtcOrder!

  eventName: OtcOrderStatus @index
  amountIn: BigInt
  amountOut: BigInt
  fee: BigInt

  filler: Account
  swap: Swap

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

# ======================================================================================================================
# *** AAVE Pool ***
# ======================================================================================================================

# Fully synthetic entity to represent assets pair and their balances in AAVE protocol
type Aavepool @entity {
  "<address> - address is derived from reserve_asset_id + aToken_id"
  id: ID!

  reserveAssetId: String!
  aTokenId: String!
  moneyMarketReserve: MoneyMarketReserve

  historicalData: [AavepoolHistoricalData!]! @derivedFrom(field: "pool")
}

type AavepoolHistoricalData @entity {
  "<aavepoolId>-<paraBlockHeight>"
  id: ID!
  pool: Aavepool!

  reserveAssetId: String
  reserveAssetRegistryId: String
  aTokenId: String!
  aTokenRegistryId: String!

  liquidityIn: BigInt!
  liquidityOut: BigInt!

  "Ref asset value of liquidityIn property - what actual amount of collateral is locked in pool "
  tvlInRefAssetNorm: String

  aTokenTotalSupply: BigInt
  variableDebtTokenTotalSupply: BigInt

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** Money Market ***
# ======================================================================================================================

type MmSupply @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  assetId: String!
  account: Account!
  accountOnBehalfOf: Account!
  amount: BigInt
  referralCode: BigInt

  initiatedByTrade: RoutedTrade

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmWithdraw @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  assetId: String!
  accountFrom: Account!
  accountTo: Account!
  amount: BigInt

  initiatedByTrade: RoutedTrade

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmBorrow @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  asset: Asset!
  account: Account!
  accountOnBehalfOf: Account!
  amount: BigInt
  interestRateMode: Int
  borrowRate: BigInt
  referralCode: BigInt

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmUserEModeSet @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  account: Account!
  categoryId: Int

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmRepay @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  assetId: String!
  account: Account!
  repayerAccount: Account!
  amount: BigInt
  useATokens: Boolean

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmLiquidationCall @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  collateralAssetId: String!
  debtAssetId: String!
  account: Account!
  debtToCoverAmount: BigInt
  liquidatedCollateralAmount: BigInt
  liquidatorAccount: Account!
  receiveAToken: Boolean!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmReserveUsedAsCollateralEnabledEvent @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  account: Account!
  assetId: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MmReserveUsedAsCollateralDisabledEvent @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  account: Account!
  assetId: String!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

enum EvmEventName {
  Transfer
  Supply
  Withdraw
  Borrow
  Repay
  UserEModeSet
  LiquidationCall
  ReserveUsedAsCollateralEnabled
  ReserveUsedAsCollateralDisabled
  OracleUpdate
  ReserveDataUpdated
  FacilitatorAdded
  FacilitatorRemoved
  FacilitatorBucketCapacityUpdated
  FacilitatorBucketLevelUpdated
}
enum EvmContractName {
  AavePoolImpl
  AavePoolConfiguratorImpl
  AaveAToken
  DiaOracleV2
  HollarToken
}

type MoneyMarketEvent @entity {
  "<event_id>"
  id: ID!
  traceIds: [String!]

  contractName: EvmContractName
  eventName: EvmEventName

  allInvolvedAssetIds: [String!]!
  allInvolvedAssetRegistryIds: [String!]!
  allInvolvedAssetDetails: String @index
  allInvolvedParticipants: [String!]!

  transfer: Transfer
  supply: MmSupply
  withdraw: MmWithdraw
  borrow: MmBorrow
  repay: MmRepay
  userEModeSet: MmUserEModeSet
  liquidationCall: MmLiquidationCall
  reserveUsedAsCollateralEnabled: MmReserveUsedAsCollateralEnabledEvent
  reserveUsedAsCollateralDisabled: MmReserveUsedAsCollateralDisabledEvent

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type MoneyMarketReserve @entity {
  "<underlying_asset_address>"
  id: ID!
  aTokenId: String!
  underlyingAssetId: String!
  variableDebtTokenId: String!
  aavePool: Aavepool

  name: String!
  symbol: String!
  decimals: Int!

  indexesHistoricalData: [MmReserveIndexesHistoricalData]!
    @derivedFrom(field: "reserve")
  configHistoricalData: [MmReserveConfigHistoricalData]!
    @derivedFrom(field: "reserve")
}

type MmReserveConfigHistoricalData @entity {
  "<underlying_asset_address>-<para_block_height>"
  id: ID!
  reserve: MoneyMarketReserve!

  interestRateStrategyAddress: String!
  priceOracle: String
  reserveFactor: BigInt
  usageAsCollateralEnabled: Boolean
  borrowingEnabled: Boolean
  isActive: Boolean
  isFrozen: Boolean
  isPaused: Boolean
  isSiloedBorrowing: Boolean
  accruedToTreasury: BigInt
  unbacked: BigInt
  flashLoanEnabled: Boolean

  debtCeiling: BigInt
  debtCeilingDecimals: BigInt
  eModeCategoryId: Int
  borrowCap: BigInt
  supplyCap: BigInt
  borrowableInIsolation: Boolean
  baseLTVasCollateral: BigInt
  reserveLiquidationThreshold: BigInt
  reserveLiquidationBonus: BigInt
  variableRateSlope1: BigInt
  variableRateSlope2: BigInt
  baseVariableBorrowRate: BigInt
  optimalUsageRatio: BigInt

  lastUpdateTimestamp: DateTime

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

type MmReserveIndexesHistoricalData @entity {
  "<underlying_asset_address>-<para_block_height>"
  id: ID!
  reserve: MoneyMarketReserve!

  liquidityRate: BigInt
  variableBorrowRate: BigInt
  liquidityIndex: BigInt
  variableBorrowIndex: BigInt

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  blockId: String
}

# ======================================================================================================================
# *** NFT ***
# ======================================================================================================================

type NftCollection @entity {
  "collection ID "
  id: ID!
  collectionType: String! # must be reviewed
  owner: Account!
  issuer: Account!
  admin: Account!
  freezer: Account!
  totalDeposit: BigInt!
  freeHolding: Boolean!
  isFrozen: Boolean!
  items: Int!
  itemMetadatas: Int!
  attributes: Int!
  maxSupply: BigInt
}

type NftAsset @entity {
  "collection ID "
  id: ID!
  owner: Account!
  deposit: BigInt!
  isFrozen: Boolean!
}

# ======================================================================================================================
# *** Liquidity Providing and Farming ***
# ======================================================================================================================

#   --------------------------------------------------------------------------------------------------------------------
#       Farm generics
#   --------------------------------------------------------------------------------------------------------------------

enum FarmLifeStateEventName {
  GlobalFarmCreated
  GlobalFarmUpdated
  GlobalFarmTerminated
  YieldFarmCreated
  YieldFarmUpdated
  YieldFarmStopped
  YieldFarmResumed
  YieldFarmTerminated
}

type FarmLifeState {
  eventName: FarmLifeStateEventName!
  eventId: String
  paraBlockHeight: Int!
  relayBlockHeight: Int!
}

enum YieldFarmDepositStatus {
  SharesDeposited # probably can be renamed to DepositCreated
  DepositDestroyed
  SharesRedeposited
  SharesWithdrawn
  RewardClaimed
}

enum FarmState {
  Active
  Stopped
  Terminated
}

type YieldFarmLoyaltyCurve {
  initialRewardPercentage: String!
  scaleCoef: Int!
}

#   --------------------------------------------------------------------------------------------------------------------
#       Omnipool Liquidity Position
#   --------------------------------------------------------------------------------------------------------------------

enum OmnipoolLiquidityPositionStatus {
  PositionCreated
  PositionUpdated
  PositionDestroyed
  PositionLiquidityAdded
  PositionLiquidityRemoved
}

type OmnipoolLiquidityPositionEvent @entity {
  "event ID"
  id: ID!
  position: OmnipoolLiquidityPosition!
  eventName: OmnipoolLiquidityPositionStatus!

  account: Account
  asset: Asset
  amount: BigInt
  sharesAmount: BigInt
  price: BigInt
  fee: BigInt

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type OmnipoolLiquidityPosition @entity {
  "position ID"
  id: ID!
  account: Account!
  asset: Asset!
  omnipoolAsset: OmnipoolAsset!
  initialAmount: BigInt!
  amount: BigInt!
  sharesAmount: BigInt!
  positionNft: NftAsset!

  "should be either PositionCreated or PositionDestroyed"
  status: OmnipoolLiquidityPositionStatus!

  positionEvents: [OmnipoolLiquidityPositionEvent]!
    @derivedFrom(field: "position")

  #  Point of time of position creation for better sorting
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

#   --------------------------------------------------------------------------------------------------------------------
#       Omnipool Liquidity Farm
#   --------------------------------------------------------------------------------------------------------------------

type OmnipoolGlobalFarm @entity {
  "omnipool global farm ID "
  id: ID!
  owner: Account!

  updatedAtRelayBlock: Int!
  totalSharesZ: BigInt!
  accumulatedRpz: BigInt!
  rewardAsset: Asset!
  pendingRewards: BigInt!
  accumulatedPaidRewards: BigInt!
  yieldPerPeriod: BigInt!
  plannedYieldingPeriods: Int!
  blocksPerPeriod: Int!
  incentivizedAsset: Asset!
  maxRewardPerPeriod: Int!
  minDeposit: BigInt!
  liveYieldFarmsCount: Int!
  totalYieldFarmsCount: Int!
  priceAdjustment: BigInt!
  state: FarmState!
  lrnaPriceAdjustment: BigInt!
  totalRewards: BigInt!

  yieldFarms: [OmnipoolYieldFarm] @derivedFrom(field: "globalFarm")

  lifeStates: [FarmLifeState!]!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type OmnipoolYieldFarm @entity {
  "global farm ID"
  id: ID!
  globalFarm: OmnipoolGlobalFarm!
  asset: Asset!
  updatedAtRelayBlock: Int!
  totalShares: BigInt!
  totalValuedShares: BigInt!
  accumulatedRpvs: BigInt!
  accumulatedRpz: BigInt!
  multiplier: BigInt!
  state: FarmState!
  entriesCount: Int!
  leftToDistribute: BigInt!
  totalStopped: BigInt!
  loyaltyCurve: YieldFarmLoyaltyCurve

  lifeStates: [FarmLifeState!]!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event
}

#   --------------------------------------------------------------------------------------------------------------------
#       Omnipool Liquidity Farm Deposit
#   --------------------------------------------------------------------------------------------------------------------

type OmnipoolYieldFarmDeposit @entity {
  "deposit ID"
  id: ID!
  depositNft: NftAsset!
  globalFarm: OmnipoolGlobalFarm!
  yieldFarm: OmnipoolYieldFarm!
  position: OmnipoolLiquidityPosition!
  account: Account!
  asset: Asset!

  "should be either SharesDeposited or DepositDestroyed"
  status: YieldFarmDepositStatus!
  sharesAmount: BigInt!
  entries: [OmnipoolYieldFarmEntry!]! @derivedFrom(field: "deposit")
  depositEvents: [OmnipoolYieldFarmDepositEvent]! @derivedFrom(field: "deposit")

  #  Point of time of position creation for better sorting
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type OmnipoolYieldFarmEntry @entity {
  "<deposit_id>-<omnipool_global_farm_id>-<omnipool_yield_farm_id>"
  id: ID!
  deposit: OmnipoolYieldFarmDeposit!
  valuedShares: BigInt!
  accumulatedRpvs: BigInt!
  accumulatedClaimedRewards: BigInt!
  enteredAtRelayBlock: Int!
  updatedAtRelayBlock: Int!
  stoppedAtCreation: Int!
}

type OmnipoolYieldFarmDepositEvent @entity {
  "event_id"
  id: ID!
  deposit: OmnipoolYieldFarmDeposit!
  eventName: YieldFarmDepositStatus!

  # required for SharesDeposited, SharesRedeposited, RewardClaimed events
  globalFarm: OmnipoolGlobalFarm!
  yieldFarm: OmnipoolYieldFarm!

  asset: Asset
  account: Account
  position: OmnipoolLiquidityPosition
  sharesAmount: BigInt
  claimedAmount: BigInt
  rewardAsset: Asset

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

#   --------------------------------------------------------------------------------------------------------------------
#       XYK Liquidity Farm
#   --------------------------------------------------------------------------------------------------------------------

type XykGlobalFarm @entity {
  "XYK global farm ID "
  id: ID!
  owner: Account!

  updatedAtRelayBlock: Int
  totalSharesZ: BigInt
  totalRewards: BigInt
  accumulatedRpz: BigInt
  rewardAsset: Asset
  pendingRewards: BigInt
  accumulatedPaidRewards: BigInt
  yieldPerPeriod: Int
  plannedYieldingPeriods: Int
  blocksPerPeriod: Int
  incentivizedAsset: Asset
  maxRewardPerPeriod: BigInt
  minDeposit: BigInt
  liveYieldFarmsCount: Int
  totalYieldFarmsCount: Int
  priceAdjustment: BigInt
  state: FarmState!

  yieldFarms: [XykYieldFarm] @derivedFrom(field: "globalFarm")

  lifeStates: [FarmLifeState!]!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event
}

type XykYieldFarm @entity {
  "yield farm ID"
  id: ID!
  globalFarm: XykGlobalFarm!
  allInvolvedAssetIds: [String!]!
  allInvolvedAssetRegistryIds: [String!]!
  pool: Xykpool!

  state: FarmState!
  updatedAtRelayBlock: Int!
  totalShares: BigInt!
  totalValuedShares: BigInt!
  accumulatedRpvs: BigInt!
  accumulatedRpz: BigInt!
  multiplier: BigInt!
  entriesCount: Int!
  leftToDistribute: BigInt!
  totalStopped: BigInt!
  loyaltyCurve: YieldFarmLoyaltyCurve

  lifeStates: [FarmLifeState!]!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event
}

#   --------------------------------------------------------------------------------------------------------------------
#       XYK Liquidity Farm Deposit
#   --------------------------------------------------------------------------------------------------------------------

type XykYieldFarmDeposit @entity {
  "deposit ID"
  id: ID!
  depositNft: NftAsset!
  globalFarm: XykGlobalFarm!
  yieldFarm: XykYieldFarm!
  allInvolvedAssetIds: [String!]! # assets of used pool
  allInvolvedAssetRegistryIds: [String!]! # assets of used pool
  account: Account!
  lpAsset: Asset!
  sharesAmount: BigInt!

  "should be either SharesDeposited or DepositDestroyed"
  status: YieldFarmDepositStatus!
  entries: [XykYieldFarmEntry!]! @derivedFrom(field: "deposit")
  depositEvents: [XykYieldFarmDepositEvent]! @derivedFrom(field: "deposit")

  #  Point of time of position creation for better sorting
  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

type XykYieldFarmEntry @entity {
  "<deposit_id>-<xyk_global_farm_id>-<xyk_yield_farm_id>"
  id: ID!
  deposit: XykYieldFarmDeposit!
  valuedShares: BigInt!
  accumulatedRpvs: BigInt!
  accumulatedClaimedRewards: BigInt!
  enteredAtRelayBlock: Int!
  updatedAtRelayBlock: Int!
  stoppedAtCreation: Int!
}

type XykYieldFarmDepositEvent @entity {
  "event_id"
  id: ID!
  deposit: XykYieldFarmDeposit!
  eventName: YieldFarmDepositStatus!

  # required for SharesDeposited, SharesRedeposited, RewardClaimed events
  globalFarm: XykGlobalFarm!
  yieldFarm: XykYieldFarm!

  lpAsset: Asset
  account: Account
  amount: BigInt
  claimedAmount: BigInt
  rewardAsset: Asset

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  event: Event!
}

# ======================================================================================================================
# *** Transaction Payment ***
# ======================================================================================================================

type TransactionPaymentHistoricalData @entity {
  "block_height"
  id: ID!

  nextFeeMultiplier: BigInt

  paraBlockHeight: Int! @index
  relayBlockHeight: Int!
  block: Block!
}
