version: "3.7"

# ======================================================================================================================
# =============================================== V A R I A B L E S ====================================================
# ======================================================================================================================

x-chain-name: &chain-name "hydration"

x-dictionary-pg-db: &dictionary-pg-db "dictionary_indexer"
x-dictionary-pg-user: &dictionary-pg-user "postgres"
x-dictionary-pg-password: &dictionary-pg-password "postgres"
x-dictionary-pg-host: &dictionary-pg-host "db-dictionary-indexer"

x-gateway-hydration-url: &gateway-hydration-url "https://v2.archive.subsquid.io/network/hydradx"

x-dictionary-rpc-url-wss: &dictionary-rpc-url-wss "wss://node-subwhale-10.shellfish.hydration.cloud"
x-dictionary-rpc-url-https: &dictionary-rpc-url-https "https://node-subwhale-10.shellfish.hydration.cloud"

x-dictionary-indexer-image: &dictionary-indexer-image "ghcr.io/mckrava/storage-dictionary-indexer:wip-feat-improve-pools-historical-data-aggregation"

# ======================================================================================================================
# ======================================== C O N F I G   S E G M E N T S ===============================================
# ======================================================================================================================

# -------------------------------------- D I C T I O N A R Y   I N D E X E R -------------------------------------------

x-db-dictionary-creds: &db-dictionary-creds
  DB_PORT: 5432
  DB_NAME: *dictionary-pg-db
  DB_USER: *dictionary-pg-user
  DB_PASS: *dictionary-pg-password
  DB_HOST: *dictionary-pg-host

x-dictionary-proc-default-envs: &dictionary-proc-default-envs
  NODE_ENV: "self-hosted"
  CHAIN: *chain-name
  RPC_URL: *dictionary-rpc-url-wss
  RPC_URL_HTTPS: *dictionary-rpc-url-https
  IGNORE_ARCHIVE_DATA_SOURCE: "false"
  GATEWAY_HYDRATION_HTTPS: *gateway-hydration-url

  PROCESS_LBP_POOLS: "true"
  PROCESS_XYK_POOLS: "true"
  PROCESS_OMNIPOOLS: "true"
  PROCESS_STABLEPOOLS: "true"
  PROCESS_GENERIC_HIST_DATA: "true"
  PROCESS_ACCOUNTS: "true"

  INDEXER_MAX_SUB_BATCH_SIZE: 500
  SUB_BATCH_MAX_TIMEOUT_MS: 500
  RUNTIME_API_CALLS_CONCURRENCY: 5
  ASSETS_TRACKER_PROCESSOR: "true"
  PERSIST_HIST_DATA_ONLY_ON_CHANGE: "true"
  INDEXING_IS_PAUSED: "false"

x-dictionary-proc-default-config: &dictionary-proc-default-config
  image: *dictionary-indexer-image
  networks:
    - default
  command:
    - sh
    - -c
    - "sqd migration:apply && node lib/main.js"
  deploy:
    restart_policy:
      condition: on-failure

# ======================================================================================================================
# ============================================ S T A C K   C O N F I G =================================================
# ======================================================================================================================

networks:
  default:
    driver: overlay

volumes:
  db-aggregator-indexer:
    driver: local
  db-dictionary-indexer:
    driver: local
  db-ts-redis:
    driver: local

services:
  # -------------------------------------- D I C T I O N A R Y   I N D E X E R -------------------------------------------

  db-dictionary-indexer:
    image: postgres:15
    environment:
      POSTGRES_DB: *dictionary-pg-db
      POSTGRES_USER: *dictionary-pg-user
      POSTGRES_PASSWORD: *dictionary-pg-password
    command:
      - "postgres"
      - "-c"
      - "statement_timeout=3000000"
      - "-c"
      - "tcp_keepalives_idle=600"
      - "-c"
      - "tcp_keepalives_interval=30"
      - "-c"
      - "tcp_keepalives_count=3"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "idle_in_transaction_session_timeout=1800000"
      - "-c"
      - "log_disconnections=on"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=1000"
      - "-c"
      - "track_io_timing=on"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_rotation_size=100MB"
      - "-c"
      - "log_line_prefix=%t [%p]: [ %l-1 ] user=%u,db=%d,app=%a,client=%h"
      - "-c"
      - "log_checkpoints=on"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "log_temp_files=0"
    volumes:
      - "db-dictionary-indexer:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aggregator_indexer"]
      interval: 5s
      timeout: 3s
      retries: 20
    logging:
      driver: json-file
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure

  db-dictionary-pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      DB_HOST: db-dictionary-indexer
      DB_PORT: 5432
      DB_USER: *dictionary-pg-user
      DB_PASSWORD: *dictionary-pg-password
      DB_DBNAME: *dictionary-pg-db
      AUTH_TYPE: scram-sha-256
      DNS_MAX_TTL: 15
      DNS_NXDOMAIN_TTL: 15
      PGBOUNCER_LISTEN_PORT: 5433
      POOL_MODE: transaction
      SERVER_RESET_QUERY: DISCARD ALL
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      MIN_POOL_SIZE: 5
      RESERVE_POOL_SIZE: 5
      SERVER_LIFETIME: 3600
      SERVER_IDLE_TIMEOUT: 2400
    ports:
      - "5490:5432"
    depends_on:
      - db-dictionary-indexer
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure

  dictionary-processor:
    <<: *dictionary-proc-default-config
    depends_on:
      - db-dictionary-pgbouncer
    environment:
      <<: [*db-dictionary-creds, *dictionary-proc-default-envs]

      PROCESS_FROM_BLOCK: 9333143
      PROCESS_TO_BLOCK: -1

  dictionary-api:
    image: *dictionary-indexer-image
    depends_on:
      - db-dictionary-pgbouncer
    environment:
      <<: *db-dictionary-creds
      NODE_ENV: "self-hosted"
      CHAIN: *chain-name
      GQL_PORT: 8080
      #
      # Configuration settings for running the indexer in multiprocessor mode.
      #
      # Config for squidStatus API query to show statuses of all running processors with information about target
      # blocks range of each processor.
      SUB_PROCESSORS_RANGES: "squid_processor:9333143:-1"
    ports:
      - "8089:8080"
    networks:
      - default
    logging:
      driver: json-file
    command:
      - sh
      - -c
      - "sqd api:prod"
    deploy:
      restart_policy:
        condition: on-failure
