#!/bin/bash
# Save secondary indexes (IDX_*) to backup file
# Run this BEFORE dropping indexes

HARVESTER_DB_URL="${HARVESTER_DB_URL:-postgresql://localhost/harvester_db}"
BACKUP_FILE="${1:-indexes-backup.sql}"

echo "Saving secondary indexes to ${BACKUP_FILE}..."
echo "=============================================="
echo ""

# Check how many indexes will be saved
echo "Analyzing indexes..."
INDEX_COUNT=$(psql "$HARVESTER_DB_URL" -t -A -c "
SELECT COUNT(*)
FROM pg_indexes
WHERE schemaname = 'public'
  AND indexname LIKE 'IDX_%'
  AND indexname NOT LIKE 'pg_toast%';
")

if [ "$INDEX_COUNT" -eq 0 ]; then
  echo "No secondary indexes found to save."
  echo "Either they're already dropped or your schema doesn't use IDX_* naming."
  exit 0
fi

echo "Found $INDEX_COUNT secondary indexes (IDX_*)"
echo ""

# Save index definitions
{
  echo "-- Secondary indexes backup"
  echo "-- Generated by save-secondary-indexes.sh"
  echo "-- Schema: public"
  echo "-- Only IDX_* indexes (excludes PK_*, UQ_*, and constraint-backed indexes)"
  echo ""
  psql "$HARVESTER_DB_URL" -t -A << 'EOF'
SELECT
  indexdef || ';' as create_statement
FROM pg_indexes
WHERE schemaname = 'public'
  AND indexname LIKE 'IDX_%'
  AND indexname NOT LIKE 'pg_toast%'
ORDER BY tablename, indexname;
EOF
} > "$BACKUP_FILE"

# Count saved indexes
SAVED_COUNT=$(grep -c "CREATE INDEX" "$BACKUP_FILE" || echo "0")

echo "✓ Saved $SAVED_COUNT index definitions to: $BACKUP_FILE"
echo ""

# Show sample
echo "Sample indexes saved (first 5):"
psql "$HARVESTER_DB_URL" << 'EOF'
SELECT
  tablename,
  indexname,
  substring(indexdef from 1 for 80) || '...' as definition
FROM pg_indexes
WHERE schemaname = 'public'
  AND indexname LIKE 'IDX_%'
  AND indexname NOT LIKE 'pg_toast%'
ORDER BY tablename, indexname
LIMIT 5;
EOF

echo ""
echo "Next steps:"
echo "  1. Drop indexes:    ./scripts/drop-secondary-indexes.sh"
echo "  2. Run migration:   npm start"
echo "  3. Restore indexes: ./scripts/restore-secondary-indexes.sh"
