module.exports = class Data1744135040298 {
    name = 'Data1744135040298'

    async up(db) {
        await db.query(`CREATE TABLE "account_asset_swap_fee_historical_data" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "total_amount" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "collection_id" character varying, "account_id" character varying, "asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_1fd8dd689bfb71262a6acf9bce3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b30d302b150dd8a64a41fbcc31" ON "account_asset_swap_fee_historical_data" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_dc91da57d00673b3a22541d9ff" ON "account_asset_swap_fee_historical_data" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_4daa6ca61b0203e257b23e661b" ON "account_asset_swap_fee_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_3125addf0ec6edae3f7f1688c5" ON "account_asset_swap_fee_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_34eef4c0f57b49c1cc3ad4da73" ON "account_asset_swap_fee_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "account_swap_fee_historical_data" ("id" character varying NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "account_id" character varying, "block_id" character varying, CONSTRAINT "PK_846ad9772ff380a9a8ed8105a09" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8eb25578b444331b850be33de5" ON "account_swap_fee_historical_data" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_93085ea424bc6596a31c0fb155" ON "account_swap_fee_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_201988571dcb26b9d84b19a3cb" ON "account_swap_fee_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "lbppool_price_historical_data" ("id" character varying NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "pool_id" character varying, "asset_a_id" character varying, "asset_b_id" character varying, "block_id" character varying, CONSTRAINT "PK_6757dd3bfc218ad75e5d6358a75" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9de871ec5024a9bd17d80b4cad" ON "lbppool_price_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_14ebbeb430083d0ef16da4f302" ON "lbppool_price_historical_data" ("asset_a_id") `)
        await db.query(`CREATE INDEX "IDX_1aa76857e5e4832e79fc590d10" ON "lbppool_price_historical_data" ("asset_b_id") `)
        await db.query(`CREATE INDEX "IDX_cbbb85c6f7ea860e4d779ea964" ON "lbppool_price_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_418c98ec85af9e0962041d6dd5" ON "lbppool_price_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "lbppool_volume_historical_data" ("id" character varying NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "pool_id" character varying, "asset_a_id" character varying, "asset_b_id" character varying, "block_id" character varying, CONSTRAINT "PK_e706f2862f6f116f258368231b8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f0cb04556654295e8c94d2d279" ON "lbppool_volume_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_34b7417acbc0b648e1c693b473" ON "lbppool_volume_historical_data" ("asset_a_id") `)
        await db.query(`CREATE INDEX "IDX_e136c969bf662136d7f24236bd" ON "lbppool_volume_historical_data" ("asset_b_id") `)
        await db.query(`CREATE INDEX "IDX_f1f3527cd1b64576cba832ae4b" ON "lbppool_volume_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_223200f0ef1154407c7cadc9a5" ON "lbppool_volume_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "xykpool_price_historical_data" ("id" character varying NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "pool_id" character varying, "asset_a_id" character varying, "asset_b_id" character varying, "block_id" character varying, CONSTRAINT "PK_d4b1506014bf0e0d605ecc029f2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4763a96a985c9220833e0ac05f" ON "xykpool_price_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_3ec6b702f931d345dd8c82fd23" ON "xykpool_price_historical_data" ("asset_a_id") `)
        await db.query(`CREATE INDEX "IDX_b5ab1453eade38546689eb0e69" ON "xykpool_price_historical_data" ("asset_b_id") `)
        await db.query(`CREATE INDEX "IDX_2ac12e019f0bbd5f96606bc63f" ON "xykpool_price_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_45f9a0424f316f1abfbff64a42" ON "xykpool_price_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "xykpool_volume_historical_data" ("id" character varying NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "pool_id" character varying, "asset_a_id" character varying, "asset_b_id" character varying, "block_id" character varying, CONSTRAINT "PK_5e9897240ab6568b70895781934" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3a2f1feb022d71f7e51819c74f" ON "xykpool_volume_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_ddb63d0e9b0bc8afcbe81058c0" ON "xykpool_volume_historical_data" ("asset_a_id") `)
        await db.query(`CREATE INDEX "IDX_d30268c8d4ba0f5c4592187f59" ON "xykpool_volume_historical_data" ("asset_b_id") `)
        await db.query(`CREATE INDEX "IDX_8389630d49684f2546ea455854" ON "xykpool_volume_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_591340e948710c56ba681beafc" ON "xykpool_volume_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "omnipool_asset_volume_historical_data" ("id" character varying NOT NULL, "asset_volume_in" numeric NOT NULL, "asset_volume_out" numeric NOT NULL, "asset_total_volume_in" numeric NOT NULL, "asset_total_volume_out" numeric NOT NULL, "asset_fee" numeric NOT NULL, "asset_total_fees" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "omnipool_asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_138304dc740307c0c8dea9df008" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d0697e336fe62440e81cc058aa" ON "omnipool_asset_volume_historical_data" ("omnipool_asset_id") `)
        await db.query(`CREATE INDEX "IDX_5aff44890a69dcd6c6efb00e73" ON "omnipool_asset_volume_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_bb6182bbe3a9812746db2b8bac" ON "omnipool_asset_volume_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "asset_volume_historical_data" ("id" character varying NOT NULL, "volume_in" numeric NOT NULL, "volume_out" numeric NOT NULL, "total_volume_in" numeric NOT NULL, "total_volume_out" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_4578b4a7577d2f68238579463fa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_42c215301a7e4ae28dc108606d" ON "asset_volume_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_21f7e4003ecc26871f370f34bb" ON "asset_volume_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_76bf4e3deef7a52ca998062336" ON "asset_volume_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "asset_swap_fee_historical_data" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "total_amount" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_700d55bbd28ec496a8bfa680a38" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ea6635c9167c3ebc60e8ff5a66" ON "asset_swap_fee_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_37f92b940599ef379fa2f69214" ON "asset_swap_fee_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_aeda4e63f834e2e91e767fabc7" ON "asset_swap_fee_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "asset_historical_data" ("id" character varying NOT NULL, "total_issuance" numeric NOT NULL, "existential_deposit" numeric NOT NULL, "spot_prices" jsonb NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_d2c0807b36c45771c8b9efe6a20" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_bbb9a36dd61646de9e108ab7ce" ON "asset_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_950584f39612b44c0e3719f19c" ON "asset_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_6f49f36e0bf52b7011e3662b23" ON "asset_historical_data" ("relay_block_height") `)
        await db.query(`CREATE INDEX "IDX_8276de0b73bc0c330b95494376" ON "asset_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "omnipool_historical_data" ("id" character varying NOT NULL, "max_in_ratio" numeric NOT NULL, "max_out_ratio" numeric NOT NULL, "min_trading_limit" numeric NOT NULL, "min_pool_liquidity" numeric NOT NULL, "min_withdrawal_fee" numeric NOT NULL, "burn_protocol_fee" integer NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "pool_id" character varying, "hdx_asset_id" character varying, "hub_asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_7756f403ce61b63e6b9b896d2d6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e82e08fa51052f4b9917e35ff8" ON "omnipool_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_c77d9e0e4375033af2c11499c3" ON "omnipool_historical_data" ("hdx_asset_id") `)
        await db.query(`CREATE INDEX "IDX_73b8a0272b5639da26c81ed620" ON "omnipool_historical_data" ("hub_asset_id") `)
        await db.query(`CREATE INDEX "IDX_240b99e438ec14ebdc7201dd10" ON "omnipool_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_5783931d1cd2b1b6bf6f4a3faa" ON "omnipool_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "stableswap_asset_volume_historical_data" ("id" character varying NOT NULL, "swap_fee" numeric NOT NULL, "swap_total_fees" numeric NOT NULL, "swap_volume_in" numeric NOT NULL, "swap_volume_out" numeric NOT NULL, "swap_total_volume_in" numeric NOT NULL, "swap_total_volume_out" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "volumes_collection_id" character varying, "asset_id" character varying, "block_id" character varying, CONSTRAINT "PK_9b6517a82ec252fde3d6f0f9985" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c398a52d189798e0bd8f1904fd" ON "stableswap_asset_volume_historical_data" ("volumes_collection_id") `)
        await db.query(`CREATE INDEX "IDX_8c6a607a067384eb5118df08a7" ON "stableswap_asset_volume_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_8a5204006a608d67f7ad2660e1" ON "stableswap_asset_volume_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_046b394a68bb579be487004ac1" ON "stableswap_asset_volume_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "stableswap_volume_historical_data" ("id" character varying NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "pool_id" character varying, "block_id" character varying, CONSTRAINT "PK_9290c14b4642ce8e7b1e7c9ca58" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e78b665a80da948e04604b6a1f" ON "stableswap_volume_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_06da11cebeb7bae2011b758f64" ON "stableswap_volume_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_e7701d65c9c30b20fe572328b7" ON "stableswap_volume_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "nft_collection" ("id" character varying NOT NULL, "collection_type" text NOT NULL, "total_deposit" numeric NOT NULL, "free_holding" boolean NOT NULL, "is_frozen" boolean NOT NULL, "items" integer NOT NULL, "item_metadatas" integer NOT NULL, "attributes" integer NOT NULL, "max_supply" numeric, "owner_id" character varying, "issuer_id" character varying, "admin_id" character varying, "freezer_id" character varying, CONSTRAINT "PK_ffe58aa05707db77c2f20ecdbc3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a44ae247ba071997b3849ec571" ON "nft_collection" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_ac41ce5c2e28effcf644a9cd6d" ON "nft_collection" ("issuer_id") `)
        await db.query(`CREATE INDEX "IDX_87594e37d5ad67fcc3cefeaf78" ON "nft_collection" ("admin_id") `)
        await db.query(`CREATE INDEX "IDX_a48062517a5dbd5c41b32f3fe7" ON "nft_collection" ("freezer_id") `)
        await db.query(`CREATE TABLE "nft_asset" ("id" character varying NOT NULL, "deposit" numeric NOT NULL, "is_frozen" boolean NOT NULL, "owner_id" character varying, CONSTRAINT "PK_cc8df03c45b7811002d0d907e70" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_16a702920b053f7b2413623d3b" ON "nft_asset" ("owner_id") `)
        await db.query(`CREATE TABLE "omnipool_liquidity_position" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "shares_amount" numeric NOT NULL, "status" character varying(24) NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "account_id" character varying, "asset_id" character varying, "omnipool_asset_id" character varying, "position_nft_id" character varying, "event_id" character varying, CONSTRAINT "PK_5f309e1addac179100ff683dafc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f816c476852b85c944f259c191" ON "omnipool_liquidity_position" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_d12df3bccbcaddeaac47495611" ON "omnipool_liquidity_position" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_0f5c220cb8646cbfcf1950e588" ON "omnipool_liquidity_position" ("omnipool_asset_id") `)
        await db.query(`CREATE INDEX "IDX_1be50ca81a78674cc43383d83e" ON "omnipool_liquidity_position" ("position_nft_id") `)
        await db.query(`CREATE INDEX "IDX_a43f6c5ad23ad480ddbeb15022" ON "omnipool_liquidity_position" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_f81f7a760ac213555a9c997417" ON "omnipool_liquidity_position" ("event_id") `)
        await db.query(`CREATE TABLE "omnipool_liquidity_position_event" ("id" character varying NOT NULL, "event_name" character varying(24) NOT NULL, "amount" numeric, "shares_amount" numeric, "price" numeric, "fee" numeric, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "position_id" character varying, "account_id" character varying, "asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_f81f7a760ac213555a9c997417a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e54a2859eecbfc565585d212da" ON "omnipool_liquidity_position_event" ("position_id") `)
        await db.query(`CREATE INDEX "IDX_18abc60d4dd8aa4030b9ec0dcb" ON "omnipool_liquidity_position_event" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_d66b73603b1e154183583eb56d" ON "omnipool_liquidity_position_event" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_e57457b7b90f0d5ce572b75690" ON "omnipool_liquidity_position_event" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_6e33c50e491b94215a0c98c2a8" ON "omnipool_liquidity_position_event" ("event_id") `)
        await db.query(`CREATE TABLE "omnipool_yield_farm" ("id" character varying NOT NULL, "updated_at_relay_block" integer NOT NULL, "total_shares" numeric NOT NULL, "total_valued_shares" numeric NOT NULL, "accumulated_rpvs" numeric NOT NULL, "accumulated_rpz" numeric NOT NULL, "multiplier" numeric NOT NULL, "state" character varying(10) NOT NULL, "entries_count" integer NOT NULL, "left_to_distribute" numeric NOT NULL, "total_stopped" numeric NOT NULL, "loyalty_curve" jsonb, "life_states" jsonb NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "global_farm_id" character varying, "asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_31fef43691fbae0801e0e36c63b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0b6f78b84f47632516f572fa0e" ON "omnipool_yield_farm" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_9ef2c568aa0cded05a4c0e0e2e" ON "omnipool_yield_farm" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_5fe4ff8082e40a075ad28d6c87" ON "omnipool_yield_farm" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_c983662d30c3980cc117e30e27" ON "omnipool_yield_farm" ("event_id") `)
        await db.query(`CREATE TABLE "omnipool_global_farm" ("id" character varying NOT NULL, "updated_at_relay_block" integer NOT NULL, "total_shares_z" numeric NOT NULL, "accumulated_rpz" numeric NOT NULL, "pending_rewards" numeric NOT NULL, "accumulated_paid_rewards" numeric NOT NULL, "yield_per_period" numeric NOT NULL, "planned_yielding_periods" integer NOT NULL, "blocks_per_period" integer NOT NULL, "max_reward_per_period" integer NOT NULL, "min_deposit" numeric NOT NULL, "live_yield_farms_count" integer NOT NULL, "total_yield_farms_count" integer NOT NULL, "price_adjustment" numeric NOT NULL, "state" character varying(10) NOT NULL, "lrna_price_adjustment" numeric NOT NULL, "total_rewards" numeric NOT NULL, "life_states" jsonb NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "owner_id" character varying, "reward_asset_id" character varying, "incentivized_asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_b21070085e0e2adbfa536525377" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5b69fe58f6596426fc2ee099c3" ON "omnipool_global_farm" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_04429e739ed0f17d3c4d9a86b1" ON "omnipool_global_farm" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_2c8b3b3cfa3d027d5e32d81854" ON "omnipool_global_farm" ("incentivized_asset_id") `)
        await db.query(`CREATE INDEX "IDX_acdadfd385ba5c9629ff3b2826" ON "omnipool_global_farm" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_75d8823c9cf9def602880d33e0" ON "omnipool_global_farm" ("event_id") `)
        await db.query(`CREATE TABLE "omnipool_yield_farm_entry" ("id" character varying NOT NULL, "valued_shares" numeric NOT NULL, "accumulated_rpvs" numeric NOT NULL, "accumulated_claimed_rewards" numeric NOT NULL, "entered_at_relay_block" integer NOT NULL, "updated_at_relay_block" integer NOT NULL, "stopped_at_creation" integer NOT NULL, "deposit_id" character varying, CONSTRAINT "PK_0ca80e3d22138ddc6e779c3524a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2984ce28c6a9459ad8d76dc430" ON "omnipool_yield_farm_entry" ("deposit_id") `)
        await db.query(`CREATE TABLE "omnipool_yield_farm_deposit_event" ("id" character varying NOT NULL, "event_name" character varying(17) NOT NULL, "shares_amount" numeric, "claimed_amount" numeric, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "deposit_id" character varying, "global_farm_id" character varying, "yield_farm_id" character varying, "asset_id" character varying, "account_id" character varying, "position_id" character varying, "reward_asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_a289981cbcf7295bb41d7e41140" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a707ae8f047454dbd57488d1a9" ON "omnipool_yield_farm_deposit_event" ("deposit_id") `)
        await db.query(`CREATE INDEX "IDX_d4a457308c3b0b9d3b5348c5eb" ON "omnipool_yield_farm_deposit_event" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_4c4a794ee14067843b0966f793" ON "omnipool_yield_farm_deposit_event" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_3d80b5514b0d5c1b6e2fd13e9b" ON "omnipool_yield_farm_deposit_event" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_fa90ed456670dc1608740e1b0e" ON "omnipool_yield_farm_deposit_event" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_76ff447e674048e52489571e03" ON "omnipool_yield_farm_deposit_event" ("position_id") `)
        await db.query(`CREATE INDEX "IDX_4987a6af190a40b2e3a5d718e1" ON "omnipool_yield_farm_deposit_event" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_e12a0e63748bb897bbc8b4f629" ON "omnipool_yield_farm_deposit_event" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_3d4e54f35e319ff41b24c8a8c4" ON "omnipool_yield_farm_deposit_event" ("event_id") `)
        await db.query(`CREATE TABLE "omnipool_yield_farm_deposit" ("id" character varying NOT NULL, "status" character varying(17) NOT NULL, "shares_amount" numeric NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "deposit_nft_id" character varying, "global_farm_id" character varying, "yield_farm_id" character varying, "position_id" character varying, "account_id" character varying, "asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_7962ef0a1fd2ce11a29068b0c8d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_da27e8df2a7638f2cd586f40db" ON "omnipool_yield_farm_deposit" ("deposit_nft_id") `)
        await db.query(`CREATE INDEX "IDX_30b4e6a736cda6ed420bb65a83" ON "omnipool_yield_farm_deposit" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_340180c5200878abbf0f181fde" ON "omnipool_yield_farm_deposit" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_d5f3c8eca4debf29322d84322d" ON "omnipool_yield_farm_deposit" ("position_id") `)
        await db.query(`CREATE INDEX "IDX_12611a74c4fda79d26a2c3cecc" ON "omnipool_yield_farm_deposit" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_7b066907d0661d82f5818d33b4" ON "omnipool_yield_farm_deposit" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_4b51ac4f2442e2e942073b238c" ON "omnipool_yield_farm_deposit" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_a289981cbcf7295bb41d7e4114" ON "omnipool_yield_farm_deposit" ("event_id") `)
        await db.query(`CREATE TABLE "xyk_yield_farm" ("id" character varying NOT NULL, "all_involved_assets" text array NOT NULL, "state" character varying(10) NOT NULL, "updated_at_relay_block" integer NOT NULL, "total_shares" numeric NOT NULL, "total_valued_shares" numeric NOT NULL, "accumulated_rpvs" numeric NOT NULL, "accumulated_rpz" numeric NOT NULL, "multiplier" numeric NOT NULL, "entries_count" integer NOT NULL, "left_to_distribute" numeric NOT NULL, "total_stopped" numeric NOT NULL, "loyalty_curve" jsonb, "life_states" jsonb NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "global_farm_id" character varying, "pool_id" character varying, "event_id" character varying, CONSTRAINT "PK_29ff7bc1710a1d1b9c3baf9aae0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5c7814912e39921e576fac2803" ON "xyk_yield_farm" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_fbbd0867069024cd2d607c1195" ON "xyk_yield_farm" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_1e2744f1756d4cbe41bfaa6446" ON "xyk_yield_farm" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_8bb2c27bb66cca4cf38813a208" ON "xyk_yield_farm" ("event_id") `)
        await db.query(`CREATE TABLE "xyk_global_farm" ("id" character varying NOT NULL, "updated_at_relay_block" integer, "total_shares_z" numeric, "total_rewards" numeric, "accumulated_rpz" numeric, "pending_rewards" numeric, "accumulated_paid_rewards" numeric, "yield_per_period" integer, "planned_yielding_periods" integer, "blocks_per_period" integer, "max_reward_per_period" numeric, "min_deposit" numeric, "live_yield_farms_count" integer, "total_yield_farms_count" integer, "price_adjustment" numeric, "state" character varying(10) NOT NULL, "life_states" jsonb NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "owner_id" character varying, "reward_asset_id" character varying, "incentivized_asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_8fea3b64946a6c85260b6b031d0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_06eb6464419a36c1d135f6c0f3" ON "xyk_global_farm" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_7652051f556fe9619509b73595" ON "xyk_global_farm" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_abdc30cf737392a69dd3ceba09" ON "xyk_global_farm" ("incentivized_asset_id") `)
        await db.query(`CREATE INDEX "IDX_1e47870ce30e2ba0ceaad75cb9" ON "xyk_global_farm" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_da5d1f67b416086e09b8021acc" ON "xyk_global_farm" ("event_id") `)
        await db.query(`CREATE TABLE "xyk_yield_farm_entry" ("id" character varying NOT NULL, "valued_shares" numeric NOT NULL, "accumulated_rpvs" numeric NOT NULL, "accumulated_claimed_rewards" numeric NOT NULL, "entered_at_relay_block" integer NOT NULL, "updated_at_relay_block" integer NOT NULL, "stopped_at_creation" integer NOT NULL, "deposit_id" character varying, CONSTRAINT "PK_cfd44572ae4fef9a29e4ab4e2f3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a4d9e0c71da74ffd1a52f51c3b" ON "xyk_yield_farm_entry" ("deposit_id") `)
        await db.query(`CREATE TABLE "xyk_yield_farm_deposit_event" ("id" character varying NOT NULL, "event_name" character varying(17) NOT NULL, "amount" numeric, "claimed_amount" numeric, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "deposit_id" character varying, "global_farm_id" character varying, "yield_farm_id" character varying, "lp_asset_id" character varying, "account_id" character varying, "reward_asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_e9998cb14c035a5279c52ee420b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_18bf95c5e40a82e1a8133fe2d2" ON "xyk_yield_farm_deposit_event" ("deposit_id") `)
        await db.query(`CREATE INDEX "IDX_1eb723cdb014f96c0801040e0a" ON "xyk_yield_farm_deposit_event" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_a785574ddd9cc531b7671369f5" ON "xyk_yield_farm_deposit_event" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_e012578b4e6b35f529c3fd0dc7" ON "xyk_yield_farm_deposit_event" ("lp_asset_id") `)
        await db.query(`CREATE INDEX "IDX_2622762d09b3d72009c0f85a16" ON "xyk_yield_farm_deposit_event" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_8563aa7d75d95a711472096a47" ON "xyk_yield_farm_deposit_event" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_78f2882309fee6e552cf5d8380" ON "xyk_yield_farm_deposit_event" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_d73a010919f9180f1e25634ab3" ON "xyk_yield_farm_deposit_event" ("event_id") `)
        await db.query(`CREATE TABLE "xyk_yield_farm_deposit" ("id" character varying NOT NULL, "all_involved_assets" text array NOT NULL, "shares_amount" numeric NOT NULL, "status" character varying(17) NOT NULL, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "deposit_nft_id" character varying, "global_farm_id" character varying, "yield_farm_id" character varying, "account_id" character varying, "lp_asset_id" character varying, "event_id" character varying, CONSTRAINT "PK_a38d86b8b0b83741a4ed9407357" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_51fd4a5c99ee0de678a3d7eb1d" ON "xyk_yield_farm_deposit" ("deposit_nft_id") `)
        await db.query(`CREATE INDEX "IDX_7a2d2bf54f3310ccb450013be3" ON "xyk_yield_farm_deposit" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_283e4ca1617c9d2c272de0c29e" ON "xyk_yield_farm_deposit" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_dae4631f1949d8a3553f1e919d" ON "xyk_yield_farm_deposit" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_a440b07505f45a0d22160cb3cc" ON "xyk_yield_farm_deposit" ("lp_asset_id") `)
        await db.query(`CREATE INDEX "IDX_a089edfb95807e5fa9faf2d878" ON "xyk_yield_farm_deposit" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_e9998cb14c035a5279c52ee420" ON "xyk_yield_farm_deposit" ("event_id") `)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" DROP COLUMN "decorated_free"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" DROP COLUMN "decorated_locked"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ADD "transferable" numeric NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ADD "total_locked" numeric NOT NULL`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD "repay_fee" integer array NOT NULL`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD "max_in_ratio" numeric NOT NULL`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD "max_out_ratio" numeric NOT NULL`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD "min_pool_liquidity" numeric NOT NULL`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD "min_trading_limit" numeric NOT NULL`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "exchange_fee" integer array NOT NULL`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "max_in_ratio" numeric`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "max_out_ratio" numeric`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "min_pool_liquidity" numeric`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "min_trading_limit" numeric`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "oracle_source" text`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "native_asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" ADD "tradable" integer NOT NULL`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" ADD "tradable" integer`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" ADD "peg" text array NOT NULL`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD "max_in_ratio" numeric NOT NULL`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD "max_out_ratio" numeric NOT NULL`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD "min_trading_limit" numeric NOT NULL`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD "amplification_range" integer array NOT NULL`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD "min_pool_liquidity" numeric NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "free" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "locked" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "flags" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "frozen" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "reserved" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "fee_frozen" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "misc_frozen" DROP NOT NULL`)
        await db.query(`CREATE INDEX "IDX_d9402be34d864b02108cc3a8db" ON "xykpool_historical_data" ("native_asset_id") `)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" ADD CONSTRAINT "FK_b30d302b150dd8a64a41fbcc31e" FOREIGN KEY ("collection_id") REFERENCES "account_swap_fee_historical_data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" ADD CONSTRAINT "FK_dc91da57d00673b3a22541d9ff9" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" ADD CONSTRAINT "FK_4daa6ca61b0203e257b23e661b9" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" ADD CONSTRAINT "FK_34eef4c0f57b49c1cc3ad4da73a" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" ADD CONSTRAINT "FK_8eb25578b444331b850be33de54" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" ADD CONSTRAINT "FK_201988571dcb26b9d84b19a3cbd" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" ADD CONSTRAINT "FK_9de871ec5024a9bd17d80b4cade" FOREIGN KEY ("pool_id") REFERENCES "lbppool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" ADD CONSTRAINT "FK_14ebbeb430083d0ef16da4f302b" FOREIGN KEY ("asset_a_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" ADD CONSTRAINT "FK_1aa76857e5e4832e79fc590d10d" FOREIGN KEY ("asset_b_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" ADD CONSTRAINT "FK_418c98ec85af9e0962041d6dd55" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" ADD CONSTRAINT "FK_f0cb04556654295e8c94d2d2799" FOREIGN KEY ("pool_id") REFERENCES "lbppool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" ADD CONSTRAINT "FK_34b7417acbc0b648e1c693b473c" FOREIGN KEY ("asset_a_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" ADD CONSTRAINT "FK_e136c969bf662136d7f24236bd7" FOREIGN KEY ("asset_b_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" ADD CONSTRAINT "FK_223200f0ef1154407c7cadc9a52" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" ADD CONSTRAINT "FK_4763a96a985c9220833e0ac05fb" FOREIGN KEY ("pool_id") REFERENCES "xykpool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" ADD CONSTRAINT "FK_3ec6b702f931d345dd8c82fd235" FOREIGN KEY ("asset_a_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" ADD CONSTRAINT "FK_b5ab1453eade38546689eb0e696" FOREIGN KEY ("asset_b_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" ADD CONSTRAINT "FK_45f9a0424f316f1abfbff64a425" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" ADD CONSTRAINT "FK_3a2f1feb022d71f7e51819c74fc" FOREIGN KEY ("pool_id") REFERENCES "xykpool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" ADD CONSTRAINT "FK_ddb63d0e9b0bc8afcbe81058c07" FOREIGN KEY ("asset_a_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" ADD CONSTRAINT "FK_d30268c8d4ba0f5c4592187f591" FOREIGN KEY ("asset_b_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" ADD CONSTRAINT "FK_591340e948710c56ba681beafce" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD CONSTRAINT "FK_d9402be34d864b02108cc3a8dbd" FOREIGN KEY ("native_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" ADD CONSTRAINT "FK_d0697e336fe62440e81cc058aab" FOREIGN KEY ("omnipool_asset_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" ADD CONSTRAINT "FK_bb6182bbe3a9812746db2b8bac2" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ADD CONSTRAINT "FK_42c215301a7e4ae28dc108606d4" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ADD CONSTRAINT "FK_76bf4e3deef7a52ca9980623361" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" ADD CONSTRAINT "FK_ea6635c9167c3ebc60e8ff5a66e" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" ADD CONSTRAINT "FK_aeda4e63f834e2e91e767fabc77" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_historical_data" ADD CONSTRAINT "FK_bbb9a36dd61646de9e108ab7ce3" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_historical_data" ADD CONSTRAINT "FK_8276de0b73bc0c330b954943768" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_historical_data" ADD CONSTRAINT "FK_e82e08fa51052f4b9917e35ff8c" FOREIGN KEY ("pool_id") REFERENCES "omnipool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_historical_data" ADD CONSTRAINT "FK_c77d9e0e4375033af2c11499c3d" FOREIGN KEY ("hdx_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_historical_data" ADD CONSTRAINT "FK_73b8a0272b5639da26c81ed6205" FOREIGN KEY ("hub_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_historical_data" ADD CONSTRAINT "FK_5783931d1cd2b1b6bf6f4a3faaa" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" ADD CONSTRAINT "FK_c398a52d189798e0bd8f1904fd2" FOREIGN KEY ("volumes_collection_id") REFERENCES "stableswap_volume_historical_data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" ADD CONSTRAINT "FK_8c6a607a067384eb5118df08a70" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" ADD CONSTRAINT "FK_046b394a68bb579be487004ac1f" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" ADD CONSTRAINT "FK_e78b665a80da948e04604b6a1f6" FOREIGN KEY ("pool_id") REFERENCES "stableswap"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" ADD CONSTRAINT "FK_e7701d65c9c30b20fe572328b7e" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_a44ae247ba071997b3849ec5717" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_ac41ce5c2e28effcf644a9cd6d1" FOREIGN KEY ("issuer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_87594e37d5ad67fcc3cefeaf787" FOREIGN KEY ("admin_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_a48062517a5dbd5c41b32f3fe71" FOREIGN KEY ("freezer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_asset" ADD CONSTRAINT "FK_16a702920b053f7b2413623d3b0" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_f816c476852b85c944f259c1913" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_d12df3bccbcaddeaac47495611d" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_0f5c220cb8646cbfcf1950e5884" FOREIGN KEY ("omnipool_asset_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_1be50ca81a78674cc43383d83ed" FOREIGN KEY ("position_nft_id") REFERENCES "nft_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_f81f7a760ac213555a9c997417a" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_e54a2859eecbfc565585d212daf" FOREIGN KEY ("position_id") REFERENCES "omnipool_liquidity_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_18abc60d4dd8aa4030b9ec0dcb5" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_d66b73603b1e154183583eb56d5" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_6e33c50e491b94215a0c98c2a83" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD CONSTRAINT "FK_0b6f78b84f47632516f572fa0eb" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD CONSTRAINT "FK_9ef2c568aa0cded05a4c0e0e2ea" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD CONSTRAINT "FK_c983662d30c3980cc117e30e278" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_5b69fe58f6596426fc2ee099c34" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_04429e739ed0f17d3c4d9a86b1d" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_2c8b3b3cfa3d027d5e32d818544" FOREIGN KEY ("incentivized_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_75d8823c9cf9def602880d33e06" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_entry" ADD CONSTRAINT "FK_2984ce28c6a9459ad8d76dc4304" FOREIGN KEY ("deposit_id") REFERENCES "omnipool_yield_farm_deposit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_a707ae8f047454dbd57488d1a98" FOREIGN KEY ("deposit_id") REFERENCES "omnipool_yield_farm_deposit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_d4a457308c3b0b9d3b5348c5eb2" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_4c4a794ee14067843b0966f7935" FOREIGN KEY ("yield_farm_id") REFERENCES "omnipool_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_3d80b5514b0d5c1b6e2fd13e9bf" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_fa90ed456670dc1608740e1b0ee" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_76ff447e674048e52489571e039" FOREIGN KEY ("position_id") REFERENCES "omnipool_liquidity_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_4987a6af190a40b2e3a5d718e1e" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_3d4e54f35e319ff41b24c8a8c40" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_da27e8df2a7638f2cd586f40db7" FOREIGN KEY ("deposit_nft_id") REFERENCES "nft_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_30b4e6a736cda6ed420bb65a839" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_340180c5200878abbf0f181fde3" FOREIGN KEY ("yield_farm_id") REFERENCES "omnipool_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_d5f3c8eca4debf29322d84322db" FOREIGN KEY ("position_id") REFERENCES "omnipool_liquidity_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_12611a74c4fda79d26a2c3cecc0" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_7b066907d0661d82f5818d33b42" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_a289981cbcf7295bb41d7e41140" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD CONSTRAINT "FK_5c7814912e39921e576fac2803c" FOREIGN KEY ("global_farm_id") REFERENCES "xyk_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD CONSTRAINT "FK_fbbd0867069024cd2d607c1195c" FOREIGN KEY ("pool_id") REFERENCES "xykpool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD CONSTRAINT "FK_8bb2c27bb66cca4cf38813a2085" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_06eb6464419a36c1d135f6c0f37" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_7652051f556fe9619509b735954" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_abdc30cf737392a69dd3ceba09f" FOREIGN KEY ("incentivized_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_da5d1f67b416086e09b8021acc3" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_entry" ADD CONSTRAINT "FK_a4d9e0c71da74ffd1a52f51c3ba" FOREIGN KEY ("deposit_id") REFERENCES "xyk_yield_farm_deposit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_18bf95c5e40a82e1a8133fe2d2e" FOREIGN KEY ("deposit_id") REFERENCES "xyk_yield_farm_deposit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_1eb723cdb014f96c0801040e0ad" FOREIGN KEY ("global_farm_id") REFERENCES "xyk_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_a785574ddd9cc531b7671369f51" FOREIGN KEY ("yield_farm_id") REFERENCES "xyk_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_e012578b4e6b35f529c3fd0dc7e" FOREIGN KEY ("lp_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_2622762d09b3d72009c0f85a16e" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_8563aa7d75d95a711472096a47a" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_d73a010919f9180f1e25634ab30" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_51fd4a5c99ee0de678a3d7eb1dd" FOREIGN KEY ("deposit_nft_id") REFERENCES "nft_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_7a2d2bf54f3310ccb450013be38" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_283e4ca1617c9d2c272de0c29e7" FOREIGN KEY ("yield_farm_id") REFERENCES "omnipool_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_dae4631f1949d8a3553f1e919d4" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_a440b07505f45a0d22160cb3cc5" FOREIGN KEY ("lp_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_e9998cb14c035a5279c52ee420b" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "account_asset_swap_fee_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_b30d302b150dd8a64a41fbcc31"`)
        await db.query(`DROP INDEX "public"."IDX_dc91da57d00673b3a22541d9ff"`)
        await db.query(`DROP INDEX "public"."IDX_4daa6ca61b0203e257b23e661b"`)
        await db.query(`DROP INDEX "public"."IDX_3125addf0ec6edae3f7f1688c5"`)
        await db.query(`DROP INDEX "public"."IDX_34eef4c0f57b49c1cc3ad4da73"`)
        await db.query(`DROP TABLE "account_swap_fee_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_8eb25578b444331b850be33de5"`)
        await db.query(`DROP INDEX "public"."IDX_93085ea424bc6596a31c0fb155"`)
        await db.query(`DROP INDEX "public"."IDX_201988571dcb26b9d84b19a3cb"`)
        await db.query(`DROP TABLE "lbppool_price_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_9de871ec5024a9bd17d80b4cad"`)
        await db.query(`DROP INDEX "public"."IDX_14ebbeb430083d0ef16da4f302"`)
        await db.query(`DROP INDEX "public"."IDX_1aa76857e5e4832e79fc590d10"`)
        await db.query(`DROP INDEX "public"."IDX_cbbb85c6f7ea860e4d779ea964"`)
        await db.query(`DROP INDEX "public"."IDX_418c98ec85af9e0962041d6dd5"`)
        await db.query(`DROP TABLE "lbppool_volume_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_f0cb04556654295e8c94d2d279"`)
        await db.query(`DROP INDEX "public"."IDX_34b7417acbc0b648e1c693b473"`)
        await db.query(`DROP INDEX "public"."IDX_e136c969bf662136d7f24236bd"`)
        await db.query(`DROP INDEX "public"."IDX_f1f3527cd1b64576cba832ae4b"`)
        await db.query(`DROP INDEX "public"."IDX_223200f0ef1154407c7cadc9a5"`)
        await db.query(`DROP TABLE "xykpool_price_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_4763a96a985c9220833e0ac05f"`)
        await db.query(`DROP INDEX "public"."IDX_3ec6b702f931d345dd8c82fd23"`)
        await db.query(`DROP INDEX "public"."IDX_b5ab1453eade38546689eb0e69"`)
        await db.query(`DROP INDEX "public"."IDX_2ac12e019f0bbd5f96606bc63f"`)
        await db.query(`DROP INDEX "public"."IDX_45f9a0424f316f1abfbff64a42"`)
        await db.query(`DROP TABLE "xykpool_volume_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_3a2f1feb022d71f7e51819c74f"`)
        await db.query(`DROP INDEX "public"."IDX_ddb63d0e9b0bc8afcbe81058c0"`)
        await db.query(`DROP INDEX "public"."IDX_d30268c8d4ba0f5c4592187f59"`)
        await db.query(`DROP INDEX "public"."IDX_8389630d49684f2546ea455854"`)
        await db.query(`DROP INDEX "public"."IDX_591340e948710c56ba681beafc"`)
        await db.query(`DROP TABLE "omnipool_asset_volume_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_d0697e336fe62440e81cc058aa"`)
        await db.query(`DROP INDEX "public"."IDX_5aff44890a69dcd6c6efb00e73"`)
        await db.query(`DROP INDEX "public"."IDX_bb6182bbe3a9812746db2b8bac"`)
        await db.query(`DROP TABLE "asset_volume_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_42c215301a7e4ae28dc108606d"`)
        await db.query(`DROP INDEX "public"."IDX_21f7e4003ecc26871f370f34bb"`)
        await db.query(`DROP INDEX "public"."IDX_76bf4e3deef7a52ca998062336"`)
        await db.query(`DROP TABLE "asset_swap_fee_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_ea6635c9167c3ebc60e8ff5a66"`)
        await db.query(`DROP INDEX "public"."IDX_37f92b940599ef379fa2f69214"`)
        await db.query(`DROP INDEX "public"."IDX_aeda4e63f834e2e91e767fabc7"`)
        await db.query(`DROP TABLE "asset_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_bbb9a36dd61646de9e108ab7ce"`)
        await db.query(`DROP INDEX "public"."IDX_950584f39612b44c0e3719f19c"`)
        await db.query(`DROP INDEX "public"."IDX_6f49f36e0bf52b7011e3662b23"`)
        await db.query(`DROP INDEX "public"."IDX_8276de0b73bc0c330b95494376"`)
        await db.query(`DROP TABLE "omnipool_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_e82e08fa51052f4b9917e35ff8"`)
        await db.query(`DROP INDEX "public"."IDX_c77d9e0e4375033af2c11499c3"`)
        await db.query(`DROP INDEX "public"."IDX_73b8a0272b5639da26c81ed620"`)
        await db.query(`DROP INDEX "public"."IDX_240b99e438ec14ebdc7201dd10"`)
        await db.query(`DROP INDEX "public"."IDX_5783931d1cd2b1b6bf6f4a3faa"`)
        await db.query(`DROP TABLE "stableswap_asset_volume_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_c398a52d189798e0bd8f1904fd"`)
        await db.query(`DROP INDEX "public"."IDX_8c6a607a067384eb5118df08a7"`)
        await db.query(`DROP INDEX "public"."IDX_8a5204006a608d67f7ad2660e1"`)
        await db.query(`DROP INDEX "public"."IDX_046b394a68bb579be487004ac1"`)
        await db.query(`DROP TABLE "stableswap_volume_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_e78b665a80da948e04604b6a1f"`)
        await db.query(`DROP INDEX "public"."IDX_06da11cebeb7bae2011b758f64"`)
        await db.query(`DROP INDEX "public"."IDX_e7701d65c9c30b20fe572328b7"`)
        await db.query(`DROP TABLE "nft_collection"`)
        await db.query(`DROP INDEX "public"."IDX_a44ae247ba071997b3849ec571"`)
        await db.query(`DROP INDEX "public"."IDX_ac41ce5c2e28effcf644a9cd6d"`)
        await db.query(`DROP INDEX "public"."IDX_87594e37d5ad67fcc3cefeaf78"`)
        await db.query(`DROP INDEX "public"."IDX_a48062517a5dbd5c41b32f3fe7"`)
        await db.query(`DROP TABLE "nft_asset"`)
        await db.query(`DROP INDEX "public"."IDX_16a702920b053f7b2413623d3b"`)
        await db.query(`DROP TABLE "omnipool_liquidity_position"`)
        await db.query(`DROP INDEX "public"."IDX_f816c476852b85c944f259c191"`)
        await db.query(`DROP INDEX "public"."IDX_d12df3bccbcaddeaac47495611"`)
        await db.query(`DROP INDEX "public"."IDX_0f5c220cb8646cbfcf1950e588"`)
        await db.query(`DROP INDEX "public"."IDX_1be50ca81a78674cc43383d83e"`)
        await db.query(`DROP INDEX "public"."IDX_a43f6c5ad23ad480ddbeb15022"`)
        await db.query(`DROP INDEX "public"."IDX_f81f7a760ac213555a9c997417"`)
        await db.query(`DROP TABLE "omnipool_liquidity_position_event"`)
        await db.query(`DROP INDEX "public"."IDX_e54a2859eecbfc565585d212da"`)
        await db.query(`DROP INDEX "public"."IDX_18abc60d4dd8aa4030b9ec0dcb"`)
        await db.query(`DROP INDEX "public"."IDX_d66b73603b1e154183583eb56d"`)
        await db.query(`DROP INDEX "public"."IDX_e57457b7b90f0d5ce572b75690"`)
        await db.query(`DROP INDEX "public"."IDX_6e33c50e491b94215a0c98c2a8"`)
        await db.query(`DROP TABLE "omnipool_yield_farm"`)
        await db.query(`DROP INDEX "public"."IDX_0b6f78b84f47632516f572fa0e"`)
        await db.query(`DROP INDEX "public"."IDX_9ef2c568aa0cded05a4c0e0e2e"`)
        await db.query(`DROP INDEX "public"."IDX_5fe4ff8082e40a075ad28d6c87"`)
        await db.query(`DROP INDEX "public"."IDX_c983662d30c3980cc117e30e27"`)
        await db.query(`DROP TABLE "omnipool_global_farm"`)
        await db.query(`DROP INDEX "public"."IDX_5b69fe58f6596426fc2ee099c3"`)
        await db.query(`DROP INDEX "public"."IDX_04429e739ed0f17d3c4d9a86b1"`)
        await db.query(`DROP INDEX "public"."IDX_2c8b3b3cfa3d027d5e32d81854"`)
        await db.query(`DROP INDEX "public"."IDX_acdadfd385ba5c9629ff3b2826"`)
        await db.query(`DROP INDEX "public"."IDX_75d8823c9cf9def602880d33e0"`)
        await db.query(`DROP TABLE "omnipool_yield_farm_entry"`)
        await db.query(`DROP INDEX "public"."IDX_2984ce28c6a9459ad8d76dc430"`)
        await db.query(`DROP TABLE "omnipool_yield_farm_deposit_event"`)
        await db.query(`DROP INDEX "public"."IDX_a707ae8f047454dbd57488d1a9"`)
        await db.query(`DROP INDEX "public"."IDX_d4a457308c3b0b9d3b5348c5eb"`)
        await db.query(`DROP INDEX "public"."IDX_4c4a794ee14067843b0966f793"`)
        await db.query(`DROP INDEX "public"."IDX_3d80b5514b0d5c1b6e2fd13e9b"`)
        await db.query(`DROP INDEX "public"."IDX_fa90ed456670dc1608740e1b0e"`)
        await db.query(`DROP INDEX "public"."IDX_76ff447e674048e52489571e03"`)
        await db.query(`DROP INDEX "public"."IDX_4987a6af190a40b2e3a5d718e1"`)
        await db.query(`DROP INDEX "public"."IDX_e12a0e63748bb897bbc8b4f629"`)
        await db.query(`DROP INDEX "public"."IDX_3d4e54f35e319ff41b24c8a8c4"`)
        await db.query(`DROP TABLE "omnipool_yield_farm_deposit"`)
        await db.query(`DROP INDEX "public"."IDX_da27e8df2a7638f2cd586f40db"`)
        await db.query(`DROP INDEX "public"."IDX_30b4e6a736cda6ed420bb65a83"`)
        await db.query(`DROP INDEX "public"."IDX_340180c5200878abbf0f181fde"`)
        await db.query(`DROP INDEX "public"."IDX_d5f3c8eca4debf29322d84322d"`)
        await db.query(`DROP INDEX "public"."IDX_12611a74c4fda79d26a2c3cecc"`)
        await db.query(`DROP INDEX "public"."IDX_7b066907d0661d82f5818d33b4"`)
        await db.query(`DROP INDEX "public"."IDX_4b51ac4f2442e2e942073b238c"`)
        await db.query(`DROP INDEX "public"."IDX_a289981cbcf7295bb41d7e4114"`)
        await db.query(`DROP TABLE "xyk_yield_farm"`)
        await db.query(`DROP INDEX "public"."IDX_5c7814912e39921e576fac2803"`)
        await db.query(`DROP INDEX "public"."IDX_fbbd0867069024cd2d607c1195"`)
        await db.query(`DROP INDEX "public"."IDX_1e2744f1756d4cbe41bfaa6446"`)
        await db.query(`DROP INDEX "public"."IDX_8bb2c27bb66cca4cf38813a208"`)
        await db.query(`DROP TABLE "xyk_global_farm"`)
        await db.query(`DROP INDEX "public"."IDX_06eb6464419a36c1d135f6c0f3"`)
        await db.query(`DROP INDEX "public"."IDX_7652051f556fe9619509b73595"`)
        await db.query(`DROP INDEX "public"."IDX_abdc30cf737392a69dd3ceba09"`)
        await db.query(`DROP INDEX "public"."IDX_1e47870ce30e2ba0ceaad75cb9"`)
        await db.query(`DROP INDEX "public"."IDX_da5d1f67b416086e09b8021acc"`)
        await db.query(`DROP TABLE "xyk_yield_farm_entry"`)
        await db.query(`DROP INDEX "public"."IDX_a4d9e0c71da74ffd1a52f51c3b"`)
        await db.query(`DROP TABLE "xyk_yield_farm_deposit_event"`)
        await db.query(`DROP INDEX "public"."IDX_18bf95c5e40a82e1a8133fe2d2"`)
        await db.query(`DROP INDEX "public"."IDX_1eb723cdb014f96c0801040e0a"`)
        await db.query(`DROP INDEX "public"."IDX_a785574ddd9cc531b7671369f5"`)
        await db.query(`DROP INDEX "public"."IDX_e012578b4e6b35f529c3fd0dc7"`)
        await db.query(`DROP INDEX "public"."IDX_2622762d09b3d72009c0f85a16"`)
        await db.query(`DROP INDEX "public"."IDX_8563aa7d75d95a711472096a47"`)
        await db.query(`DROP INDEX "public"."IDX_78f2882309fee6e552cf5d8380"`)
        await db.query(`DROP INDEX "public"."IDX_d73a010919f9180f1e25634ab3"`)
        await db.query(`DROP TABLE "xyk_yield_farm_deposit"`)
        await db.query(`DROP INDEX "public"."IDX_51fd4a5c99ee0de678a3d7eb1d"`)
        await db.query(`DROP INDEX "public"."IDX_7a2d2bf54f3310ccb450013be3"`)
        await db.query(`DROP INDEX "public"."IDX_283e4ca1617c9d2c272de0c29e"`)
        await db.query(`DROP INDEX "public"."IDX_dae4631f1949d8a3553f1e919d"`)
        await db.query(`DROP INDEX "public"."IDX_a440b07505f45a0d22160cb3cc"`)
        await db.query(`DROP INDEX "public"."IDX_a089edfb95807e5fa9faf2d878"`)
        await db.query(`DROP INDEX "public"."IDX_e9998cb14c035a5279c52ee420"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ADD "decorated_free" numeric NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ADD "decorated_locked" numeric NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" DROP COLUMN "transferable"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" DROP COLUMN "total_locked"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP COLUMN "repay_fee"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP COLUMN "max_in_ratio"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP COLUMN "max_out_ratio"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP COLUMN "min_pool_liquidity"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP COLUMN "min_trading_limit"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "exchange_fee"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "max_in_ratio"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "max_out_ratio"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "min_pool_liquidity"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "min_trading_limit"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "oracle_source"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "native_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" DROP COLUMN "tradable"`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" DROP COLUMN "tradable"`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" DROP COLUMN "peg"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP COLUMN "max_in_ratio"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP COLUMN "max_out_ratio"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP COLUMN "min_trading_limit"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP COLUMN "amplification_range"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP COLUMN "min_pool_liquidity"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "free" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "locked" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "flags" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "frozen" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "reserved" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "fee_frozen" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ALTER COLUMN "misc_frozen" SET NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_d9402be34d864b02108cc3a8db"`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" DROP CONSTRAINT "FK_b30d302b150dd8a64a41fbcc31e"`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" DROP CONSTRAINT "FK_dc91da57d00673b3a22541d9ff9"`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" DROP CONSTRAINT "FK_4daa6ca61b0203e257b23e661b9"`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" DROP CONSTRAINT "FK_34eef4c0f57b49c1cc3ad4da73a"`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" DROP CONSTRAINT "FK_8eb25578b444331b850be33de54"`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" DROP CONSTRAINT "FK_201988571dcb26b9d84b19a3cbd"`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" DROP CONSTRAINT "FK_9de871ec5024a9bd17d80b4cade"`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" DROP CONSTRAINT "FK_14ebbeb430083d0ef16da4f302b"`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" DROP CONSTRAINT "FK_1aa76857e5e4832e79fc590d10d"`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" DROP CONSTRAINT "FK_418c98ec85af9e0962041d6dd55"`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" DROP CONSTRAINT "FK_f0cb04556654295e8c94d2d2799"`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" DROP CONSTRAINT "FK_34b7417acbc0b648e1c693b473c"`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" DROP CONSTRAINT "FK_e136c969bf662136d7f24236bd7"`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" DROP CONSTRAINT "FK_223200f0ef1154407c7cadc9a52"`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" DROP CONSTRAINT "FK_4763a96a985c9220833e0ac05fb"`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" DROP CONSTRAINT "FK_3ec6b702f931d345dd8c82fd235"`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" DROP CONSTRAINT "FK_b5ab1453eade38546689eb0e696"`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" DROP CONSTRAINT "FK_45f9a0424f316f1abfbff64a425"`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" DROP CONSTRAINT "FK_3a2f1feb022d71f7e51819c74fc"`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" DROP CONSTRAINT "FK_ddb63d0e9b0bc8afcbe81058c07"`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" DROP CONSTRAINT "FK_d30268c8d4ba0f5c4592187f591"`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" DROP CONSTRAINT "FK_591340e948710c56ba681beafce"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP CONSTRAINT "FK_d9402be34d864b02108cc3a8dbd"`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" DROP CONSTRAINT "FK_d0697e336fe62440e81cc058aab"`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" DROP CONSTRAINT "FK_bb6182bbe3a9812746db2b8bac2"`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" DROP CONSTRAINT "FK_42c215301a7e4ae28dc108606d4"`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" DROP CONSTRAINT "FK_76bf4e3deef7a52ca9980623361"`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" DROP CONSTRAINT "FK_ea6635c9167c3ebc60e8ff5a66e"`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" DROP CONSTRAINT "FK_aeda4e63f834e2e91e767fabc77"`)
        await db.query(`ALTER TABLE "asset_historical_data" DROP CONSTRAINT "FK_bbb9a36dd61646de9e108ab7ce3"`)
        await db.query(`ALTER TABLE "asset_historical_data" DROP CONSTRAINT "FK_8276de0b73bc0c330b954943768"`)
        await db.query(`ALTER TABLE "omnipool_historical_data" DROP CONSTRAINT "FK_e82e08fa51052f4b9917e35ff8c"`)
        await db.query(`ALTER TABLE "omnipool_historical_data" DROP CONSTRAINT "FK_c77d9e0e4375033af2c11499c3d"`)
        await db.query(`ALTER TABLE "omnipool_historical_data" DROP CONSTRAINT "FK_73b8a0272b5639da26c81ed6205"`)
        await db.query(`ALTER TABLE "omnipool_historical_data" DROP CONSTRAINT "FK_5783931d1cd2b1b6bf6f4a3faaa"`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" DROP CONSTRAINT "FK_c398a52d189798e0bd8f1904fd2"`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" DROP CONSTRAINT "FK_8c6a607a067384eb5118df08a70"`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" DROP CONSTRAINT "FK_046b394a68bb579be487004ac1f"`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" DROP CONSTRAINT "FK_e78b665a80da948e04604b6a1f6"`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" DROP CONSTRAINT "FK_e7701d65c9c30b20fe572328b7e"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_a44ae247ba071997b3849ec5717"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_ac41ce5c2e28effcf644a9cd6d1"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_87594e37d5ad67fcc3cefeaf787"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_a48062517a5dbd5c41b32f3fe71"`)
        await db.query(`ALTER TABLE "nft_asset" DROP CONSTRAINT "FK_16a702920b053f7b2413623d3b0"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_f816c476852b85c944f259c1913"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_d12df3bccbcaddeaac47495611d"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_0f5c220cb8646cbfcf1950e5884"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_1be50ca81a78674cc43383d83ed"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_f81f7a760ac213555a9c997417a"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_e54a2859eecbfc565585d212daf"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_18abc60d4dd8aa4030b9ec0dcb5"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_d66b73603b1e154183583eb56d5"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_6e33c50e491b94215a0c98c2a83"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP CONSTRAINT "FK_0b6f78b84f47632516f572fa0eb"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP CONSTRAINT "FK_9ef2c568aa0cded05a4c0e0e2ea"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP CONSTRAINT "FK_c983662d30c3980cc117e30e278"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_5b69fe58f6596426fc2ee099c34"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_04429e739ed0f17d3c4d9a86b1d"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_2c8b3b3cfa3d027d5e32d818544"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_75d8823c9cf9def602880d33e06"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_entry" DROP CONSTRAINT "FK_2984ce28c6a9459ad8d76dc4304"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_a707ae8f047454dbd57488d1a98"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_d4a457308c3b0b9d3b5348c5eb2"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_4c4a794ee14067843b0966f7935"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_3d80b5514b0d5c1b6e2fd13e9bf"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_fa90ed456670dc1608740e1b0ee"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_76ff447e674048e52489571e039"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_4987a6af190a40b2e3a5d718e1e"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_3d4e54f35e319ff41b24c8a8c40"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_da27e8df2a7638f2cd586f40db7"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_30b4e6a736cda6ed420bb65a839"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_340180c5200878abbf0f181fde3"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_d5f3c8eca4debf29322d84322db"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_12611a74c4fda79d26a2c3cecc0"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_7b066907d0661d82f5818d33b42"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_a289981cbcf7295bb41d7e41140"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP CONSTRAINT "FK_5c7814912e39921e576fac2803c"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP CONSTRAINT "FK_fbbd0867069024cd2d607c1195c"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP CONSTRAINT "FK_8bb2c27bb66cca4cf38813a2085"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_06eb6464419a36c1d135f6c0f37"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_7652051f556fe9619509b735954"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_abdc30cf737392a69dd3ceba09f"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_da5d1f67b416086e09b8021acc3"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_entry" DROP CONSTRAINT "FK_a4d9e0c71da74ffd1a52f51c3ba"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_18bf95c5e40a82e1a8133fe2d2e"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_1eb723cdb014f96c0801040e0ad"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_a785574ddd9cc531b7671369f51"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_e012578b4e6b35f529c3fd0dc7e"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_2622762d09b3d72009c0f85a16e"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_8563aa7d75d95a711472096a47a"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_d73a010919f9180f1e25634ab30"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_51fd4a5c99ee0de678a3d7eb1dd"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_7a2d2bf54f3310ccb450013be38"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_283e4ca1617c9d2c272de0c29e7"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_dae4631f1949d8a3553f1e919d4"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_a440b07505f45a0d22160cb3cc5"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_e9998cb14c035a5279c52ee420b"`)
    }
}
