apiVersion: 1
datasources:
  - name: Local GraphQL via JSON API
    type: marcusolsson-json-datasource
    access: proxy
    url: ${GRAPHQL_URL}   # e.g. http://host.docker.internal:4000/graphql
    jsonData:
      timeout: 60

  - name: Remote GraphQL via JSON API
    type: marcusolsson-json-datasource
    access: proxy
    url: ${GRAPHQL_REMOTE_URL}
    jsonData:
      timeout: 60