apiVersion: 1
datasources:
  - name: Local Postgres (App DB)
    type: postgres
    access: proxy
    isDefault: true
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: ${DB_NAME}
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
