type _ProcessorStatus {
  name: String!
  height: Int!
  hash: String!
  batchBlockFrom: Int!
  batchBlockTo: Int!
}

type SquidStatusSubscriptionPayload {
  event: String!
  node: _ProcessorStatus!
}

"""The root query type which gives access points into the data universe."""
type Query {
  """
  Exposes the root query type nested one level down. This is helpful for Relay 1
  which can only query top level fields if they are in a particular form.
  """
  query: Query!
  _squidStatus: [_ProcessorStatus!]!
  _apiSupport: ApiSupportResponse
}

"""
The root subscription type: contains realtime events you can subscribe to with the `subscription` operation.
"""
type Subscription {
  squidStatus: SquidStatusSubscriptionPayload
}

type AccountBalances {
  free: BigInt!
  reserved: BigInt!
  miscFrozen: BigInt
  feeFrozen: BigInt
  frozen: BigInt
  flags: BigInt
}

"""
A signed eight-byte integer. The upper big integer values are greater than the
max value for a JavaScript number. Therefore all big integers will be output as
strings and not numbers.
"""
scalar BigInt

type Tradability {
  bits: Int!
}

type OmnipoolAssetState {
  hubReserve: BigInt!
  shares: BigInt!
  protocolShares: BigInt!
  cap: BigInt!
  tradable: Tradability
}

type ApiSupportResponse {
  accountBalances: AccountBalances
  tradability: Tradability
  omnipoolAssetState: OmnipoolAssetState
}
