module.exports = class Data1753801551569 {
    name = 'Data1753801551569'

    async up(db) {
        await db.query(`CREATE TABLE "money_market_reserve_historical_data" ("id" character varying NOT NULL, "liquidity_rate" numeric, "variable_borrow_rate" numeric, "liquidity_index" numeric, "variable_borrow_index" numeric, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "reserve_id" character varying, "block_id" character varying, CONSTRAINT "PK_c9a52c21226847cac4d9a16f0c7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7e75bd6f6d595bba2011d4435b" ON "money_market_reserve_historical_data" ("reserve_id") `)
        await db.query(`CREATE INDEX "IDX_5e51dc6cffc0875c5c4c1f0d5c" ON "money_market_reserve_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_5f8d782978196b080856d0d1f4" ON "money_market_reserve_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "money_market_reserve" ("id" character varying NOT NULL, "name" text NOT NULL, "symbol" text NOT NULL, "decimals" text NOT NULL, "interest_rate_strategy_address" text NOT NULL, "is_paused" boolean, "is_siloed_borrowing" boolean, "a_token_id" character varying, "underlying_asset_id" character varying, "variable_debt_token_id" character varying, CONSTRAINT "PK_d562d71cb7574568b15bb07d3ce" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d702501d106754d95d9eb9024b" ON "money_market_reserve" ("a_token_id") `)
        await db.query(`CREATE INDEX "IDX_cab25445a4be005816c84f6a94" ON "money_market_reserve" ("underlying_asset_id") `)
        await db.query(`CREATE INDEX "IDX_1a7c44de187a45c57aa6b13210" ON "money_market_reserve" ("variable_debt_token_id") `)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "reserve_asset_registry_id" text`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "a_token_registry_id" text`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "a_token_total_supply" numeric`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "variable_debt_token_total_supply" numeric`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "reserve_asset_id" character varying`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "a_token_id" character varying`)
        await db.query(`CREATE INDEX "IDX_d044a1d141d519d186fb7f48ba" ON "aavepool_historical_data" ("reserve_asset_id") `)
        await db.query(`CREATE INDEX "IDX_7097dab4c6322068521cb628f6" ON "aavepool_historical_data" ("a_token_id") `)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD CONSTRAINT "FK_d044a1d141d519d186fb7f48baa" FOREIGN KEY ("reserve_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD CONSTRAINT "FK_7097dab4c6322068521cb628f6c" FOREIGN KEY ("a_token_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "money_market_reserve_historical_data" ADD CONSTRAINT "FK_7e75bd6f6d595bba2011d4435b1" FOREIGN KEY ("reserve_id") REFERENCES "money_market_reserve"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "money_market_reserve_historical_data" ADD CONSTRAINT "FK_5f8d782978196b080856d0d1f4f" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD CONSTRAINT "FK_d702501d106754d95d9eb9024b5" FOREIGN KEY ("a_token_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD CONSTRAINT "FK_cab25445a4be005816c84f6a949" FOREIGN KEY ("underlying_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD CONSTRAINT "FK_1a7c44de187a45c57aa6b132104" FOREIGN KEY ("variable_debt_token_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "money_market_reserve_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_7e75bd6f6d595bba2011d4435b"`)
        await db.query(`DROP INDEX "public"."IDX_5e51dc6cffc0875c5c4c1f0d5c"`)
        await db.query(`DROP INDEX "public"."IDX_5f8d782978196b080856d0d1f4"`)
        await db.query(`DROP TABLE "money_market_reserve"`)
        await db.query(`DROP INDEX "public"."IDX_d702501d106754d95d9eb9024b"`)
        await db.query(`DROP INDEX "public"."IDX_cab25445a4be005816c84f6a94"`)
        await db.query(`DROP INDEX "public"."IDX_1a7c44de187a45c57aa6b13210"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "reserve_asset_registry_id"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "a_token_registry_id"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "a_token_total_supply"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "variable_debt_token_total_supply"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "reserve_asset_id"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "a_token_id"`)
        await db.query(`DROP INDEX "public"."IDX_d044a1d141d519d186fb7f48ba"`)
        await db.query(`DROP INDEX "public"."IDX_7097dab4c6322068521cb628f6"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP CONSTRAINT "FK_d044a1d141d519d186fb7f48baa"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP CONSTRAINT "FK_7097dab4c6322068521cb628f6c"`)
        await db.query(`ALTER TABLE "money_market_reserve_historical_data" DROP CONSTRAINT "FK_7e75bd6f6d595bba2011d4435b1"`)
        await db.query(`ALTER TABLE "money_market_reserve_historical_data" DROP CONSTRAINT "FK_5f8d782978196b080856d0d1f4f"`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP CONSTRAINT "FK_d702501d106754d95d9eb9024b5"`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP CONSTRAINT "FK_cab25445a4be005816c84f6a949"`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP CONSTRAINT "FK_1a7c44de187a45c57aa6b132104"`)
    }
}
