module.exports = class Data1753973102590 {
    name = 'Data1753973102590'

    async up(db) {
        await db.query(`CREATE TABLE "mm_reserve_indexes_historical_data" ("id" character varying NOT NULL, "liquidity_rate" numeric, "variable_borrow_rate" numeric, "liquidity_index" numeric, "variable_borrow_index" numeric, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "reserve_id" character varying, "block_id" character varying, CONSTRAINT "PK_68630dee5ca4012e569bdc139a8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_31be250211fef14ca5b2912357" ON "mm_reserve_indexes_historical_data" ("reserve_id") `)
        await db.query(`CREATE INDEX "IDX_173dc8dbb83b7629827b9b17c8" ON "mm_reserve_indexes_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_12f2a4b1c22923db48a3389aad" ON "mm_reserve_indexes_historical_data" ("block_id") `)
        await db.query(`CREATE TABLE "mm_reserve_config_historical_data" ("id" character varying NOT NULL, "interest_rate_strategy_address" text NOT NULL, "price_oracle" text, "reserve_factor" numeric, "usage_as_collateral_enabled" boolean, "borrowing_enabled" boolean, "is_active" boolean, "is_frozen" boolean, "is_paused" boolean, "is_siloed_borrowing" boolean, "accrued_to_treasury" numeric, "unbacked" numeric, "flash_loan_enabled" boolean, "debt_ceiling" numeric, "debt_ceiling_decimals" numeric, "e_mode_category_id" integer, "borrow_cap" numeric, "supply_cap" numeric, "borrowable_in_isolation" boolean, "base_lt_vas_collateral" numeric, "reserve_liquidation_threshold" numeric, "reserve_liquidation_bonus" numeric, "variable_rate_slope1" numeric, "variable_rate_slope2" numeric, "base_variable_borrow_rate" numeric, "optimal_usage_ratio" numeric, "last_update_timestamp" TIMESTAMP WITH TIME ZONE, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "reserve_id" character varying, "block_id" character varying, CONSTRAINT "PK_c5134f8bffd19582e6e920184ae" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5d6690e9f25d7e5dc3e5575b47" ON "mm_reserve_config_historical_data" ("reserve_id") `)
        await db.query(`CREATE INDEX "IDX_937e18718ecccaef8cdbea1616" ON "mm_reserve_config_historical_data" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_3ad59d8a7a9997646f5d11bd9b" ON "mm_reserve_config_historical_data" ("block_id") `)
        await db.query(`ALTER TABLE "money_market_reserve" DROP COLUMN "interest_rate_strategy_address"`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP COLUMN "is_siloed_borrowing"`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP COLUMN "is_paused"`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD "aave_pool_id" character varying`)
        await db.query(`ALTER TABLE "aavepool" ADD "money_market_reserve_id" character varying`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP COLUMN "decimals"`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD "decimals" integer NOT NULL`)
        await db.query(`ALTER TABLE "money_market_event" DROP COLUMN "contract_name"`)
        await db.query(`ALTER TABLE "money_market_event" ADD "contract_name" character varying(24)`)
        await db.query(`CREATE INDEX "IDX_349b9def6844db4407e2abbba5" ON "money_market_reserve" ("aave_pool_id") `)
        await db.query(`CREATE INDEX "IDX_50218a357bb16db3279d205f40" ON "aavepool" ("money_market_reserve_id") `)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" ADD CONSTRAINT "FK_31be250211fef14ca5b2912357e" FOREIGN KEY ("reserve_id") REFERENCES "money_market_reserve"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" ADD CONSTRAINT "FK_12f2a4b1c22923db48a3389aad2" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" ADD CONSTRAINT "FK_5d6690e9f25d7e5dc3e5575b471" FOREIGN KEY ("reserve_id") REFERENCES "money_market_reserve"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" ADD CONSTRAINT "FK_3ad59d8a7a9997646f5d11bd9bc" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD CONSTRAINT "FK_349b9def6844db4407e2abbba5f" FOREIGN KEY ("aave_pool_id") REFERENCES "aavepool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "aavepool" ADD CONSTRAINT "FK_50218a357bb16db3279d205f405" FOREIGN KEY ("money_market_reserve_id") REFERENCES "money_market_reserve"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "mm_reserve_indexes_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_31be250211fef14ca5b2912357"`)
        await db.query(`DROP INDEX "public"."IDX_173dc8dbb83b7629827b9b17c8"`)
        await db.query(`DROP INDEX "public"."IDX_12f2a4b1c22923db48a3389aad"`)
        await db.query(`DROP TABLE "mm_reserve_config_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_5d6690e9f25d7e5dc3e5575b47"`)
        await db.query(`DROP INDEX "public"."IDX_937e18718ecccaef8cdbea1616"`)
        await db.query(`DROP INDEX "public"."IDX_3ad59d8a7a9997646f5d11bd9b"`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD "interest_rate_strategy_address" text NOT NULL`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD "is_siloed_borrowing" boolean`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD "is_paused" boolean`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP COLUMN "aave_pool_id"`)
        await db.query(`ALTER TABLE "aavepool" DROP COLUMN "money_market_reserve_id"`)
        await db.query(`ALTER TABLE "money_market_reserve" ADD "decimals" text NOT NULL`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP COLUMN "decimals"`)
        await db.query(`ALTER TABLE "money_market_event" ADD "contract_name" character varying(12)`)
        await db.query(`ALTER TABLE "money_market_event" DROP COLUMN "contract_name"`)
        await db.query(`DROP INDEX "public"."IDX_349b9def6844db4407e2abbba5"`)
        await db.query(`DROP INDEX "public"."IDX_50218a357bb16db3279d205f40"`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" DROP CONSTRAINT "FK_31be250211fef14ca5b2912357e"`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" DROP CONSTRAINT "FK_12f2a4b1c22923db48a3389aad2"`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" DROP CONSTRAINT "FK_5d6690e9f25d7e5dc3e5575b471"`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" DROP CONSTRAINT "FK_3ad59d8a7a9997646f5d11bd9bc"`)
        await db.query(`ALTER TABLE "money_market_reserve" DROP CONSTRAINT "FK_349b9def6844db4407e2abbba5f"`)
        await db.query(`ALTER TABLE "aavepool" DROP CONSTRAINT "FK_50218a357bb16db3279d205f405"`)
    }
}
