module.exports = class Data1761742897472 {
    name = 'Data1761742897472'

    async up(db) {
        await db.query(`ALTER TABLE "asset_volume_historical_data" DROP CONSTRAINT "FK_76bf4e3deef7a52ca9980623361"`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" DROP CONSTRAINT "FK_aeda4e63f834e2e91e767fabc77"`)
        await db.query(`ALTER TABLE "assets_pair_volume_historical_data" DROP CONSTRAINT "FK_aff7b6b05a7d8e6d3fe3edef077"`)
        await db.query(`ALTER TABLE "asset_historical_data" DROP CONSTRAINT "FK_8276de0b73bc0c330b954943768"`)
        await db.query(`ALTER TABLE "asset_spot_price_historical_data" DROP CONSTRAINT "FK_5aa5ad5a22a798dfea0e2c1f433"`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" DROP CONSTRAINT "FK_34eef4c0f57b49c1cc3ad4da73a"`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" DROP CONSTRAINT "FK_201988571dcb26b9d84b19a3cbd"`)
        await db.query(`ALTER TABLE "account_mm_position_historical_data" DROP CONSTRAINT "FK_05c671451b27bdea5ca504c4f19"`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" DROP CONSTRAINT "FK_418c98ec85af9e0962041d6dd55"`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" DROP CONSTRAINT "FK_223200f0ef1154407c7cadc9a52"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP CONSTRAINT "FK_7d345ec49fbe97a755a0409e793"`)
        await db.query(`ALTER TABLE "lbppool" DROP CONSTRAINT "FK_bbeec5bd5431644a6c9ab0b54ff"`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" DROP CONSTRAINT "FK_45f9a0424f316f1abfbff64a425"`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" DROP CONSTRAINT "FK_591340e948710c56ba681beafce"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP CONSTRAINT "FK_ee9d433f4d16b251761992bfb14"`)
        await db.query(`ALTER TABLE "xykpool" DROP CONSTRAINT "FK_a90de0b2a1a64b39eab0d402e78"`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" DROP CONSTRAINT "FK_bb6182bbe3a9812746db2b8bac2"`)
        await db.query(`ALTER TABLE "omnipool_historical_data" DROP CONSTRAINT "FK_5783931d1cd2b1b6bf6f4a3faaa"`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" DROP CONSTRAINT "FK_2dd1572de3b31974213e8c504ae"`)
        await db.query(`ALTER TABLE "omnipool_asset" DROP CONSTRAINT "FK_9035cef995f06d573d714464c6e"`)
        await db.query(`ALTER TABLE "omnipool" DROP CONSTRAINT "FK_986fad48a1339471367c330dfc5"`)
        await db.query(`ALTER TABLE "stableswap" DROP CONSTRAINT "FK_31e1bc79a20cb196bb5a6d7f22e"`)
        await db.query(`ALTER TABLE "otc_order" DROP CONSTRAINT "FK_3cd6d4024f40ac8c356542bdd2a"`)
        await db.query(`ALTER TABLE "routed_trade" DROP CONSTRAINT "FK_0b608193c1aa6e23be045d7073c"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" DROP CONSTRAINT "FK_15de08c10cf55031657e4487e3f"`)
        await db.query(`ALTER TABLE "account_total_balance_historical_data" DROP CONSTRAINT "FK_82cb468fb3bcebd1dde8fd8fead"`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" DROP CONSTRAINT "FK_046b394a68bb579be487004ac1f"`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" DROP CONSTRAINT "FK_e7701d65c9c30b20fe572328b7e"`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" DROP CONSTRAINT "FK_ec2c0f6217b1b5cf88d6d2a3bd2"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP CONSTRAINT "FK_9fb871d6d5a0ccc7889a4ec7114"`)
        await db.query(`ALTER TABLE "hsmpool_historical_data" DROP CONSTRAINT "FK_b59ed3133cf853aa0e47711ac08"`)
        await db.query(`ALTER TABLE "hsm_collateral_config_historical_data" DROP CONSTRAINT "FK_49a3c312e70a8991db2a6ed12a0"`)
        await db.query(`ALTER TABLE "aave_facilitator_historical_data" DROP CONSTRAINT "FK_5a5e67cf83c6bf95faacf49853e"`)
        await db.query(`ALTER TABLE "hsmpool_asset_historical_data" DROP CONSTRAINT "FK_30cc0a22679b0ed5f2d40649277"`)
        await db.query(`ALTER TABLE "constants_historical_data" DROP CONSTRAINT "FK_de9f533e177766f7c05c7793731"`)
        await db.query(`ALTER TABLE "ema_oracle_entry_historical_data" DROP CONSTRAINT "FK_69eb79053dfeebef94f290d6199"`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" DROP CONSTRAINT "FK_12f2a4b1c22923db48a3389aad2"`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" DROP CONSTRAINT "FK_3ad59d8a7a9997646f5d11bd9bc"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP CONSTRAINT "FK_5f8d8d09b192511e30ad6de9179"`)
        await db.query(`DROP INDEX "public"."IDX_76bf4e3deef7a52ca998062336"`)
        await db.query(`DROP INDEX "public"."IDX_aeda4e63f834e2e91e767fabc7"`)
        await db.query(`DROP INDEX "public"."IDX_aff7b6b05a7d8e6d3fe3edef07"`)
        await db.query(`DROP INDEX "public"."IDX_8276de0b73bc0c330b95494376"`)
        await db.query(`DROP INDEX "public"."idx_asset_historical_data_asset_id_para_block_height"`)
        await db.query(`DROP INDEX "public"."IDX_5aa5ad5a22a798dfea0e2c1f43"`)
        await db.query(`DROP INDEX "public"."idx_asset_spot_price_historical_data_assets_para_block_height"`)
        await db.query(`DROP INDEX "public"."IDX_34eef4c0f57b49c1cc3ad4da73"`)
        await db.query(`DROP INDEX "public"."IDX_201988571dcb26b9d84b19a3cb"`)
        await db.query(`DROP INDEX "public"."IDX_05c671451b27bdea5ca504c4f1"`)
        await db.query(`DROP INDEX "public"."IDX_418c98ec85af9e0962041d6dd5"`)
        await db.query(`DROP INDEX "public"."IDX_223200f0ef1154407c7cadc9a5"`)
        await db.query(`DROP INDEX "public"."IDX_7d345ec49fbe97a755a0409e79"`)
        await db.query(`DROP INDEX "public"."IDX_bbeec5bd5431644a6c9ab0b54f"`)
        await db.query(`DROP INDEX "public"."IDX_45f9a0424f316f1abfbff64a42"`)
        await db.query(`DROP INDEX "public"."IDX_591340e948710c56ba681beafc"`)
        await db.query(`DROP INDEX "public"."IDX_ee9d433f4d16b251761992bfb1"`)
        await db.query(`DROP INDEX "public"."IDX_a90de0b2a1a64b39eab0d402e7"`)
        await db.query(`DROP INDEX "public"."IDX_bb6182bbe3a9812746db2b8bac"`)
        await db.query(`DROP INDEX "public"."IDX_5783931d1cd2b1b6bf6f4a3faa"`)
        await db.query(`DROP INDEX "public"."IDX_2dd1572de3b31974213e8c504a"`)
        await db.query(`DROP INDEX "public"."IDX_9035cef995f06d573d714464c6"`)
        await db.query(`DROP INDEX "public"."IDX_986fad48a1339471367c330dfc"`)
        await db.query(`DROP INDEX "public"."IDX_31e1bc79a20cb196bb5a6d7f22"`)
        await db.query(`DROP INDEX "public"."IDX_3cd6d4024f40ac8c356542bdd2"`)
        await db.query(`DROP INDEX "public"."IDX_0b608193c1aa6e23be045d7073"`)
        await db.query(`DROP INDEX "public"."IDX_15de08c10cf55031657e4487e3"`)
        await db.query(`DROP INDEX "public"."aabhd_latest_pos_idx"`)
        await db.query(`DROP INDEX "public"."IDX_82cb468fb3bcebd1dde8fd8fea"`)
        await db.query(`DROP INDEX "public"."IDX_046b394a68bb579be487004ac1"`)
        await db.query(`DROP INDEX "public"."IDX_e7701d65c9c30b20fe572328b7"`)
        await db.query(`DROP INDEX "public"."IDX_ec2c0f6217b1b5cf88d6d2a3bd"`)
        await db.query(`DROP INDEX "public"."IDX_9fb871d6d5a0ccc7889a4ec711"`)
        await db.query(`DROP INDEX "public"."IDX_b59ed3133cf853aa0e47711ac0"`)
        await db.query(`DROP INDEX "public"."IDX_49a3c312e70a8991db2a6ed12a"`)
        await db.query(`DROP INDEX "public"."IDX_5a5e67cf83c6bf95faacf49853"`)
        await db.query(`DROP INDEX "public"."IDX_30cc0a22679b0ed5f2d4064927"`)
        await db.query(`DROP INDEX "public"."IDX_de9f533e177766f7c05c779373"`)
        await db.query(`DROP INDEX "public"."IDX_69eb79053dfeebef94f290d619"`)
        await db.query(`DROP INDEX "public"."IDX_12f2a4b1c22923db48a3389aad"`)
        await db.query(`DROP INDEX "public"."IDX_3ad59d8a7a9997646f5d11bd9b"`)
        await db.query(`DROP INDEX "public"."IDX_5f8d8d09b192511e30ad6de917"`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "assets_pair_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "asset_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "asset_spot_price_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "account_mm_position_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "lbppool_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "lbppool" DROP COLUMN "created_at_block_id"`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "xykpool_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "xykpool" DROP COLUMN "created_at_block_id"`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "omnipool_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "omnipool_asset" DROP COLUMN "added_at_block_id"`)
        await db.query(`ALTER TABLE "omnipool" DROP COLUMN "destroyed_at_block_id"`)
        await db.query(`ALTER TABLE "stableswap" DROP COLUMN "created_at_block_id"`)
        await db.query(`ALTER TABLE "otc_order" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "routed_trade" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "account_total_balance_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "stableswap_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "hsmpool_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "hsm_collateral_config_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "aave_facilitator_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "hsmpool_asset_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "constants_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "ema_oracle_entry_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "aavepool_historical_data" DROP COLUMN "block_id"`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ALTER COLUMN "total_volume_in_norm" DROP DEFAULT`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ALTER COLUMN "total_volume_out_norm" DROP DEFAULT`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "asset_volume_historical_data" ADD CONSTRAINT "FK_76bf4e3deef7a52ca9980623361" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" ADD CONSTRAINT "FK_aeda4e63f834e2e91e767fabc77" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "assets_pair_volume_historical_data" ADD CONSTRAINT "FK_aff7b6b05a7d8e6d3fe3edef077" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_historical_data" ADD CONSTRAINT "FK_8276de0b73bc0c330b954943768" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_spot_price_historical_data" ADD CONSTRAINT "FK_5aa5ad5a22a798dfea0e2c1f433" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" ADD CONSTRAINT "FK_34eef4c0f57b49c1cc3ad4da73a" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" ADD CONSTRAINT "FK_201988571dcb26b9d84b19a3cbd" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_mm_position_historical_data" ADD CONSTRAINT "FK_05c671451b27bdea5ca504c4f19" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" ADD CONSTRAINT "FK_418c98ec85af9e0962041d6dd55" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" ADD CONSTRAINT "FK_223200f0ef1154407c7cadc9a52" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD CONSTRAINT "FK_7d345ec49fbe97a755a0409e793" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbppool" ADD CONSTRAINT "FK_bbeec5bd5431644a6c9ab0b54ff" FOREIGN KEY ("created_at_block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" ADD CONSTRAINT "FK_45f9a0424f316f1abfbff64a425" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" ADD CONSTRAINT "FK_591340e948710c56ba681beafce" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD CONSTRAINT "FK_ee9d433f4d16b251761992bfb14" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xykpool" ADD CONSTRAINT "FK_a90de0b2a1a64b39eab0d402e78" FOREIGN KEY ("created_at_block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" ADD CONSTRAINT "FK_bb6182bbe3a9812746db2b8bac2" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_historical_data" ADD CONSTRAINT "FK_5783931d1cd2b1b6bf6f4a3faaa" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" ADD CONSTRAINT "FK_2dd1572de3b31974213e8c504ae" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset" ADD CONSTRAINT "FK_9035cef995f06d573d714464c6e" FOREIGN KEY ("added_at_block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool" ADD CONSTRAINT "FK_986fad48a1339471367c330dfc5" FOREIGN KEY ("destroyed_at_block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap" ADD CONSTRAINT "FK_31e1bc79a20cb196bb5a6d7f22e" FOREIGN KEY ("created_at_block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "otc_order" ADD CONSTRAINT "FK_3cd6d4024f40ac8c356542bdd2a" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "routed_trade" ADD CONSTRAINT "FK_0b608193c1aa6e23be045d7073c" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ADD CONSTRAINT "FK_15de08c10cf55031657e4487e3f" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_total_balance_historical_data" ADD CONSTRAINT "FK_82cb468fb3bcebd1dde8fd8fead" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" ADD CONSTRAINT "FK_046b394a68bb579be487004ac1f" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" ADD CONSTRAINT "FK_e7701d65c9c30b20fe572328b7e" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" ADD CONSTRAINT "FK_ec2c0f6217b1b5cf88d6d2a3bd2" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD CONSTRAINT "FK_9fb871d6d5a0ccc7889a4ec7114" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "hsmpool_historical_data" ADD CONSTRAINT "FK_b59ed3133cf853aa0e47711ac08" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "hsm_collateral_config_historical_data" ADD CONSTRAINT "FK_49a3c312e70a8991db2a6ed12a0" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "aave_facilitator_historical_data" ADD CONSTRAINT "FK_5a5e67cf83c6bf95faacf49853e" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "hsmpool_asset_historical_data" ADD CONSTRAINT "FK_30cc0a22679b0ed5f2d40649277" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "constants_historical_data" ADD CONSTRAINT "FK_de9f533e177766f7c05c7793731" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "ema_oracle_entry_historical_data" ADD CONSTRAINT "FK_69eb79053dfeebef94f290d6199" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" ADD CONSTRAINT "FK_12f2a4b1c22923db48a3389aad2" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" ADD CONSTRAINT "FK_3ad59d8a7a9997646f5d11bd9bc" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD CONSTRAINT "FK_5f8d8d09b192511e30ad6de9179" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`CREATE INDEX "IDX_76bf4e3deef7a52ca998062336" ON "asset_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_aeda4e63f834e2e91e767fabc7" ON "asset_swap_fee_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_aff7b6b05a7d8e6d3fe3edef07" ON "assets_pair_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_8276de0b73bc0c330b95494376" ON "asset_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "idx_asset_historical_data_asset_id_para_block_height" ON "asset_historical_data" ("para_block_height", "asset_id") `)
        await db.query(`CREATE INDEX "IDX_5aa5ad5a22a798dfea0e2c1f43" ON "asset_spot_price_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "idx_asset_spot_price_historical_data_assets_para_block_height" ON "asset_spot_price_historical_data" ("para_block_height", "asset_in_id", "asset_out_id") `)
        await db.query(`CREATE INDEX "IDX_34eef4c0f57b49c1cc3ad4da73" ON "account_asset_swap_fee_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_201988571dcb26b9d84b19a3cb" ON "account_swap_fee_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_05c671451b27bdea5ca504c4f1" ON "account_mm_position_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_418c98ec85af9e0962041d6dd5" ON "lbppool_price_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_223200f0ef1154407c7cadc9a5" ON "lbppool_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_7d345ec49fbe97a755a0409e79" ON "lbppool_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_bbeec5bd5431644a6c9ab0b54f" ON "lbppool" ("created_at_block_id") `)
        await db.query(`CREATE INDEX "IDX_45f9a0424f316f1abfbff64a42" ON "xykpool_price_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_591340e948710c56ba681beafc" ON "xykpool_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_ee9d433f4d16b251761992bfb1" ON "xykpool_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_a90de0b2a1a64b39eab0d402e7" ON "xykpool" ("created_at_block_id") `)
        await db.query(`CREATE INDEX "IDX_bb6182bbe3a9812746db2b8bac" ON "omnipool_asset_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_5783931d1cd2b1b6bf6f4a3faa" ON "omnipool_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_2dd1572de3b31974213e8c504a" ON "omnipool_asset_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_9035cef995f06d573d714464c6" ON "omnipool_asset" ("added_at_block_id") `)
        await db.query(`CREATE INDEX "IDX_986fad48a1339471367c330dfc" ON "omnipool" ("destroyed_at_block_id") `)
        await db.query(`CREATE INDEX "IDX_31e1bc79a20cb196bb5a6d7f22" ON "stableswap" ("created_at_block_id") `)
        await db.query(`CREATE INDEX "IDX_3cd6d4024f40ac8c356542bdd2" ON "otc_order" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_0b608193c1aa6e23be045d7073" ON "routed_trade" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_15de08c10cf55031657e4487e3" ON "account_asset_balance_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "aabhd_latest_pos_idx" ON "account_asset_balance_historical_data" ("transferable", "total_locked", "para_block_height", "account_id", "asset_id") WHERE ((transferable + total_locked) > (0)::numeric)`)
        await db.query(`CREATE INDEX "IDX_82cb468fb3bcebd1dde8fd8fea" ON "account_total_balance_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_046b394a68bb579be487004ac1" ON "stableswap_asset_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_e7701d65c9c30b20fe572328b7" ON "stableswap_volume_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_ec2c0f6217b1b5cf88d6d2a3bd" ON "stableswap_asset_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_9fb871d6d5a0ccc7889a4ec711" ON "stableswap_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_b59ed3133cf853aa0e47711ac0" ON "hsmpool_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_49a3c312e70a8991db2a6ed12a" ON "hsm_collateral_config_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_5a5e67cf83c6bf95faacf49853" ON "aave_facilitator_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_30cc0a22679b0ed5f2d4064927" ON "hsmpool_asset_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_de9f533e177766f7c05c779373" ON "constants_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_69eb79053dfeebef94f290d619" ON "ema_oracle_entry_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_12f2a4b1c22923db48a3389aad" ON "mm_reserve_indexes_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_3ad59d8a7a9997646f5d11bd9b" ON "mm_reserve_config_historical_data" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_5f8d8d09b192511e30ad6de917" ON "aavepool_historical_data" ("block_id") `)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "asset_swap_fee_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "assets_pair_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "asset_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "asset_spot_price_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "account_asset_swap_fee_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "account_swap_fee_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "account_mm_position_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "lbppool_price_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "lbppool_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "lbppool_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "lbppool" ADD "created_at_block_id" character varying`)
        await db.query(`ALTER TABLE "xykpool_price_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "xykpool_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "xykpool_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "xykpool" ADD "created_at_block_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_asset_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_asset" ADD "added_at_block_id" character varying`)
        await db.query(`ALTER TABLE "omnipool" ADD "destroyed_at_block_id" character varying`)
        await db.query(`ALTER TABLE "stableswap" ADD "created_at_block_id" character varying`)
        await db.query(`ALTER TABLE "otc_order" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "routed_trade" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "account_asset_balance_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "account_total_balance_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "stableswap_asset_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "stableswap_volume_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "stableswap_asset_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "stableswap_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "hsmpool_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "hsm_collateral_config_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "aave_facilitator_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "hsmpool_asset_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "constants_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "ema_oracle_entry_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "mm_reserve_indexes_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "mm_reserve_config_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "aavepool_historical_data" ADD "block_id" character varying`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ALTER COLUMN "total_volume_in_norm" SET DEFAULT '0'`)
        await db.query(`ALTER TABLE "asset_volume_historical_data" ALTER COLUMN "total_volume_out_norm" SET DEFAULT '0'`)
    }
}
