module.exports = class Data1762365672378 {
    name = 'Data1762365672378'

    async up(db) {
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_18abc60d4dd8aa4030b9ec0dcb5"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_d66b73603b1e154183583eb56d5"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP CONSTRAINT "FK_6e33c50e491b94215a0c98c2a83"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_d12df3bccbcaddeaac47495611d"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_0f5c220cb8646cbfcf1950e5884"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_1be50ca81a78674cc43383d83ed"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP CONSTRAINT "FK_f81f7a760ac213555a9c997417a"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_5b69fe58f6596426fc2ee099c34"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_04429e739ed0f17d3c4d9a86b1d"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_2c8b3b3cfa3d027d5e32d818544"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP CONSTRAINT "FK_75d8823c9cf9def602880d33e06"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP CONSTRAINT "FK_0b6f78b84f47632516f572fa0eb"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP CONSTRAINT "FK_9ef2c568aa0cded05a4c0e0e2ea"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP CONSTRAINT "FK_c983662d30c3980cc117e30e278"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_d4a457308c3b0b9d3b5348c5eb2"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_4c4a794ee14067843b0966f7935"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_3d80b5514b0d5c1b6e2fd13e9bf"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_fa90ed456670dc1608740e1b0ee"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_76ff447e674048e52489571e039"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_4987a6af190a40b2e3a5d718e1e"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_3d4e54f35e319ff41b24c8a8c40"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_da27e8df2a7638f2cd586f40db7"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_30b4e6a736cda6ed420bb65a839"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_340180c5200878abbf0f181fde3"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_7b066907d0661d82f5818d33b42"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_a289981cbcf7295bb41d7e41140"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP CONSTRAINT "FK_fbbd0867069024cd2d607c1195c"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP CONSTRAINT "FK_8bb2c27bb66cca4cf38813a2085"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_06eb6464419a36c1d135f6c0f37"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_7652051f556fe9619509b735954"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_abdc30cf737392a69dd3ceba09f"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP CONSTRAINT "FK_da5d1f67b416086e09b8021acc3"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_1eb723cdb014f96c0801040e0ad"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_a785574ddd9cc531b7671369f51"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_e012578b4e6b35f529c3fd0dc7e"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_2622762d09b3d72009c0f85a16e"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_8563aa7d75d95a711472096a47a"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_d73a010919f9180f1e25634ab30"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_51fd4a5c99ee0de678a3d7eb1dd"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_7a2d2bf54f3310ccb450013be38"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_283e4ca1617c9d2c272de0c29e7"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_a440b07505f45a0d22160cb3cc5"`)
        await db.query(`DROP INDEX "public"."IDX_18abc60d4dd8aa4030b9ec0dcb"`)
        await db.query(`DROP INDEX "public"."IDX_d66b73603b1e154183583eb56d"`)
        await db.query(`DROP INDEX "public"."IDX_6e33c50e491b94215a0c98c2a8"`)
        await db.query(`DROP INDEX "public"."IDX_d12df3bccbcaddeaac47495611"`)
        await db.query(`DROP INDEX "public"."IDX_0f5c220cb8646cbfcf1950e588"`)
        await db.query(`DROP INDEX "public"."IDX_1be50ca81a78674cc43383d83e"`)
        await db.query(`DROP INDEX "public"."IDX_f81f7a760ac213555a9c997417"`)
        await db.query(`DROP INDEX "public"."IDX_5b69fe58f6596426fc2ee099c3"`)
        await db.query(`DROP INDEX "public"."IDX_04429e739ed0f17d3c4d9a86b1"`)
        await db.query(`DROP INDEX "public"."IDX_2c8b3b3cfa3d027d5e32d81854"`)
        await db.query(`DROP INDEX "public"."IDX_75d8823c9cf9def602880d33e0"`)
        await db.query(`DROP INDEX "public"."IDX_0b6f78b84f47632516f572fa0e"`)
        await db.query(`DROP INDEX "public"."IDX_9ef2c568aa0cded05a4c0e0e2e"`)
        await db.query(`DROP INDEX "public"."IDX_c983662d30c3980cc117e30e27"`)
        await db.query(`DROP INDEX "public"."IDX_d4a457308c3b0b9d3b5348c5eb"`)
        await db.query(`DROP INDEX "public"."IDX_4c4a794ee14067843b0966f793"`)
        await db.query(`DROP INDEX "public"."IDX_3d80b5514b0d5c1b6e2fd13e9b"`)
        await db.query(`DROP INDEX "public"."IDX_fa90ed456670dc1608740e1b0e"`)
        await db.query(`DROP INDEX "public"."IDX_76ff447e674048e52489571e03"`)
        await db.query(`DROP INDEX "public"."IDX_4987a6af190a40b2e3a5d718e1"`)
        await db.query(`DROP INDEX "public"."IDX_3d4e54f35e319ff41b24c8a8c4"`)
        await db.query(`DROP INDEX "public"."IDX_da27e8df2a7638f2cd586f40db"`)
        await db.query(`DROP INDEX "public"."IDX_30b4e6a736cda6ed420bb65a83"`)
        await db.query(`DROP INDEX "public"."IDX_340180c5200878abbf0f181fde"`)
        await db.query(`DROP INDEX "public"."IDX_7b066907d0661d82f5818d33b4"`)
        await db.query(`DROP INDEX "public"."IDX_a289981cbcf7295bb41d7e4114"`)
        await db.query(`DROP INDEX "public"."IDX_fbbd0867069024cd2d607c1195"`)
        await db.query(`DROP INDEX "public"."IDX_8bb2c27bb66cca4cf38813a208"`)
        await db.query(`DROP INDEX "public"."IDX_06eb6464419a36c1d135f6c0f3"`)
        await db.query(`DROP INDEX "public"."IDX_7652051f556fe9619509b73595"`)
        await db.query(`DROP INDEX "public"."IDX_abdc30cf737392a69dd3ceba09"`)
        await db.query(`DROP INDEX "public"."IDX_da5d1f67b416086e09b8021acc"`)
        await db.query(`DROP INDEX "public"."IDX_1eb723cdb014f96c0801040e0a"`)
        await db.query(`DROP INDEX "public"."IDX_a785574ddd9cc531b7671369f5"`)
        await db.query(`DROP INDEX "public"."IDX_e012578b4e6b35f529c3fd0dc7"`)
        await db.query(`DROP INDEX "public"."IDX_2622762d09b3d72009c0f85a16"`)
        await db.query(`DROP INDEX "public"."IDX_8563aa7d75d95a711472096a47"`)
        await db.query(`DROP INDEX "public"."IDX_d73a010919f9180f1e25634ab3"`)
        await db.query(`DROP INDEX "public"."IDX_51fd4a5c99ee0de678a3d7eb1d"`)
        await db.query(`DROP INDEX "public"."IDX_7a2d2bf54f3310ccb450013be3"`)
        await db.query(`DROP INDEX "public"."IDX_283e4ca1617c9d2c272de0c29e"`)
        await db.query(`DROP INDEX "public"."IDX_a440b07505f45a0d22160cb3cc"`)
        await db.query(`CREATE TABLE "omnipool_asset_liquidity_event" ("id" character varying NOT NULL, "trace_ids" text array, "asset_id" text NOT NULL, "action_type" character varying(6) NOT NULL, "account_id" text NOT NULL, "position_id" text NOT NULL, "amount" numeric NOT NULL, "fee" numeric, "para_block_height" integer NOT NULL, "relay_block_height" integer NOT NULL, "event_id" text NOT NULL, "position_event_id" character varying, CONSTRAINT "PK_e43c15884f3a1469aff7d3122fc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_55dd880363c1800cf708e84045" ON "omnipool_asset_liquidity_event" ("position_event_id") `)
        await db.query(`CREATE INDEX "IDX_db7c075ead4bbc0256255baaf2" ON "omnipool_asset_liquidity_event" ("para_block_height") `)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "fee"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "lrna_price_adjustment"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "total_rewards"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "owner_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP COLUMN "pool_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "owner_id"`)
        await db.query(`ALTER TABLE "nft_asset" ADD "collection_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "trace_ids" text array`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "price" numeric`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "owner_account_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "event" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD "xykpool_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "owner_account_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "account_id" text`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "asset_id" text`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "event_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "asset_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "omnipool_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "omnipool_asset_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "position_nft_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "position_nft_id" text`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "event_id" text`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "reward_asset_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "incentivized_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "incentivized_asset_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "max_reward_per_period"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "max_reward_per_period" numeric NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "event_id" text`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD "asset_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD "event_id" text`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "position_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "position_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "yield_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "asset_id" text`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "account_id" text`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "reward_asset_id" text`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "event_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "deposit_nft_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "deposit_nft_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "yield_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "asset_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD "event_id" text`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "reward_asset_id" text`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "incentivized_asset_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "incentivized_asset_id" text`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "event_id" text`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "yield_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "lp_asset_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "lp_asset_id" text`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "account_id" text`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "reward_asset_id" text`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "event_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "deposit_nft_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "deposit_nft_id" text`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "yield_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "lp_asset_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "lp_asset_id" text NOT NULL`)
        await db.query(`CREATE INDEX "IDX_4c1b9f9057fad88ea4f82a615d" ON "nft_asset" ("collection_id") `)
        await db.query(`ALTER TABLE "nft_asset" ADD CONSTRAINT "FK_4c1b9f9057fad88ea4f82a615dd" FOREIGN KEY ("collection_id") REFERENCES "nft_collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_liquidity_event" ADD CONSTRAINT "FK_55dd880363c1800cf708e840450" FOREIGN KEY ("position_event_id") REFERENCES "omnipool_liquidity_position_event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_18abc60d4dd8aa4030b9ec0dcb5" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_d66b73603b1e154183583eb56d5" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD CONSTRAINT "FK_6e33c50e491b94215a0c98c2a83" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_d12df3bccbcaddeaac47495611d" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_0f5c220cb8646cbfcf1950e5884" FOREIGN KEY ("omnipool_asset_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_1be50ca81a78674cc43383d83ed" FOREIGN KEY ("position_nft_id") REFERENCES "nft_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD CONSTRAINT "FK_f81f7a760ac213555a9c997417a" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_5b69fe58f6596426fc2ee099c34" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_04429e739ed0f17d3c4d9a86b1d" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_2c8b3b3cfa3d027d5e32d818544" FOREIGN KEY ("incentivized_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD CONSTRAINT "FK_75d8823c9cf9def602880d33e06" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD CONSTRAINT "FK_0b6f78b84f47632516f572fa0eb" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD CONSTRAINT "FK_9ef2c568aa0cded05a4c0e0e2ea" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD CONSTRAINT "FK_c983662d30c3980cc117e30e278" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_d4a457308c3b0b9d3b5348c5eb2" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_4c4a794ee14067843b0966f7935" FOREIGN KEY ("yield_farm_id") REFERENCES "omnipool_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_3d80b5514b0d5c1b6e2fd13e9bf" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_fa90ed456670dc1608740e1b0ee" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_76ff447e674048e52489571e039" FOREIGN KEY ("position_id") REFERENCES "omnipool_liquidity_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_4987a6af190a40b2e3a5d718e1e" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_3d4e54f35e319ff41b24c8a8c40" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_da27e8df2a7638f2cd586f40db7" FOREIGN KEY ("deposit_nft_id") REFERENCES "nft_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_30b4e6a736cda6ed420bb65a839" FOREIGN KEY ("global_farm_id") REFERENCES "omnipool_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_340180c5200878abbf0f181fde3" FOREIGN KEY ("yield_farm_id") REFERENCES "omnipool_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_7b066907d0661d82f5818d33b42" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_a289981cbcf7295bb41d7e41140" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD CONSTRAINT "FK_fbbd0867069024cd2d607c1195c" FOREIGN KEY ("pool_id") REFERENCES "xykpool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD CONSTRAINT "FK_8bb2c27bb66cca4cf38813a2085" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_06eb6464419a36c1d135f6c0f37" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_7652051f556fe9619509b735954" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_abdc30cf737392a69dd3ceba09f" FOREIGN KEY ("incentivized_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD CONSTRAINT "FK_da5d1f67b416086e09b8021acc3" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_1eb723cdb014f96c0801040e0ad" FOREIGN KEY ("global_farm_id") REFERENCES "xyk_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_a785574ddd9cc531b7671369f51" FOREIGN KEY ("yield_farm_id") REFERENCES "xyk_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_e012578b4e6b35f529c3fd0dc7e" FOREIGN KEY ("lp_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_2622762d09b3d72009c0f85a16e" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_8563aa7d75d95a711472096a47a" FOREIGN KEY ("reward_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_d73a010919f9180f1e25634ab30" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_51fd4a5c99ee0de678a3d7eb1dd" FOREIGN KEY ("deposit_nft_id") REFERENCES "nft_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_7a2d2bf54f3310ccb450013be38" FOREIGN KEY ("global_farm_id") REFERENCES "xyk_global_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_283e4ca1617c9d2c272de0c29e7" FOREIGN KEY ("yield_farm_id") REFERENCES "xyk_yield_farm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_a440b07505f45a0d22160cb3cc5" FOREIGN KEY ("lp_asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`CREATE INDEX "IDX_18abc60d4dd8aa4030b9ec0dcb" ON "omnipool_liquidity_position_event" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_d66b73603b1e154183583eb56d" ON "omnipool_liquidity_position_event" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_6e33c50e491b94215a0c98c2a8" ON "omnipool_liquidity_position_event" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_d12df3bccbcaddeaac47495611" ON "omnipool_liquidity_position" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_0f5c220cb8646cbfcf1950e588" ON "omnipool_liquidity_position" ("omnipool_asset_id") `)
        await db.query(`CREATE INDEX "IDX_1be50ca81a78674cc43383d83e" ON "omnipool_liquidity_position" ("position_nft_id") `)
        await db.query(`CREATE INDEX "IDX_f81f7a760ac213555a9c997417" ON "omnipool_liquidity_position" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_5b69fe58f6596426fc2ee099c3" ON "omnipool_global_farm" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_04429e739ed0f17d3c4d9a86b1" ON "omnipool_global_farm" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_2c8b3b3cfa3d027d5e32d81854" ON "omnipool_global_farm" ("incentivized_asset_id") `)
        await db.query(`CREATE INDEX "IDX_75d8823c9cf9def602880d33e0" ON "omnipool_global_farm" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_0b6f78b84f47632516f572fa0e" ON "omnipool_yield_farm" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_9ef2c568aa0cded05a4c0e0e2e" ON "omnipool_yield_farm" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_c983662d30c3980cc117e30e27" ON "omnipool_yield_farm" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_d4a457308c3b0b9d3b5348c5eb" ON "omnipool_yield_farm_deposit_event" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_4c4a794ee14067843b0966f793" ON "omnipool_yield_farm_deposit_event" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_3d80b5514b0d5c1b6e2fd13e9b" ON "omnipool_yield_farm_deposit_event" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_fa90ed456670dc1608740e1b0e" ON "omnipool_yield_farm_deposit_event" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_76ff447e674048e52489571e03" ON "omnipool_yield_farm_deposit_event" ("position_id") `)
        await db.query(`CREATE INDEX "IDX_4987a6af190a40b2e3a5d718e1" ON "omnipool_yield_farm_deposit_event" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_3d4e54f35e319ff41b24c8a8c4" ON "omnipool_yield_farm_deposit_event" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_da27e8df2a7638f2cd586f40db" ON "omnipool_yield_farm_deposit" ("deposit_nft_id") `)
        await db.query(`CREATE INDEX "IDX_30b4e6a736cda6ed420bb65a83" ON "omnipool_yield_farm_deposit" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_340180c5200878abbf0f181fde" ON "omnipool_yield_farm_deposit" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_7b066907d0661d82f5818d33b4" ON "omnipool_yield_farm_deposit" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_a289981cbcf7295bb41d7e4114" ON "omnipool_yield_farm_deposit" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_fbbd0867069024cd2d607c1195" ON "xyk_yield_farm" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_8bb2c27bb66cca4cf38813a208" ON "xyk_yield_farm" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_06eb6464419a36c1d135f6c0f3" ON "xyk_global_farm" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_7652051f556fe9619509b73595" ON "xyk_global_farm" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_abdc30cf737392a69dd3ceba09" ON "xyk_global_farm" ("incentivized_asset_id") `)
        await db.query(`CREATE INDEX "IDX_da5d1f67b416086e09b8021acc" ON "xyk_global_farm" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_1eb723cdb014f96c0801040e0a" ON "xyk_yield_farm_deposit_event" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_a785574ddd9cc531b7671369f5" ON "xyk_yield_farm_deposit_event" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_e012578b4e6b35f529c3fd0dc7" ON "xyk_yield_farm_deposit_event" ("lp_asset_id") `)
        await db.query(`CREATE INDEX "IDX_2622762d09b3d72009c0f85a16" ON "xyk_yield_farm_deposit_event" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_8563aa7d75d95a711472096a47" ON "xyk_yield_farm_deposit_event" ("reward_asset_id") `)
        await db.query(`CREATE INDEX "IDX_d73a010919f9180f1e25634ab3" ON "xyk_yield_farm_deposit_event" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_51fd4a5c99ee0de678a3d7eb1d" ON "xyk_yield_farm_deposit" ("deposit_nft_id") `)
        await db.query(`CREATE INDEX "IDX_7a2d2bf54f3310ccb450013be3" ON "xyk_yield_farm_deposit" ("global_farm_id") `)
        await db.query(`CREATE INDEX "IDX_283e4ca1617c9d2c272de0c29e" ON "xyk_yield_farm_deposit" ("yield_farm_id") `)
        await db.query(`CREATE INDEX "IDX_a440b07505f45a0d22160cb3cc" ON "xyk_yield_farm_deposit" ("lp_asset_id") `)
        await db.query(`DROP TABLE "omnipool_asset_liquidity_event"`)
        await db.query(`DROP INDEX "public"."IDX_55dd880363c1800cf708e84045"`)
        await db.query(`DROP INDEX "public"."IDX_db7c075ead4bbc0256255baaf2"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "fee" numeric`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "lrna_price_adjustment" numeric NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "total_rewards" numeric NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "owner_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD "pool_id" character varying`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "owner_id" character varying`)
        await db.query(`ALTER TABLE "nft_asset" DROP COLUMN "collection_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "trace_ids"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "price"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "owner_account_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "event"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP COLUMN "xykpool_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "owner_account_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "account_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position_event" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "omnipool_asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "omnipool_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "position_nft_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "position_nft_id"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "reward_asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "incentivized_asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "incentivized_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "max_reward_per_period" integer NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "max_reward_per_period"`)
        await db.query(`ALTER TABLE "omnipool_global_farm" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_global_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD "global_farm_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD "asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "position_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "position_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "global_farm_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "yield_farm_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "account_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "reward_asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "deposit_nft_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "deposit_nft_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "global_farm_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "yield_farm_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "asset_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "asset_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "reward_asset_id" character varying`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "incentivized_asset_id" character varying`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "incentivized_asset_id"`)
        await db.query(`ALTER TABLE "xyk_global_farm" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "xyk_global_farm" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "global_farm_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "yield_farm_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "lp_asset_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "lp_asset_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "account_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "reward_asset_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "reward_asset_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "deposit_nft_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "deposit_nft_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "global_farm_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "yield_farm_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "lp_asset_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "lp_asset_id"`)
        await db.query(`DROP INDEX "public"."IDX_4c1b9f9057fad88ea4f82a615d"`)
        await db.query(`ALTER TABLE "nft_asset" DROP CONSTRAINT "FK_4c1b9f9057fad88ea4f82a615dd"`)
        await db.query(`ALTER TABLE "omnipool_asset_liquidity_event" DROP CONSTRAINT "FK_55dd880363c1800cf708e840450"`)
    }
}
