module.exports = class Data1765224811047 {
    name = 'Data1765224811047'

    async up(db) {
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_dae4631f1949d8a3553f1e919d4"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP CONSTRAINT "FK_e9998cb14c035a5279c52ee420b"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP CONSTRAINT "FK_18bf95c5e40a82e1a8133fe2d2e"`)
        await db.query(`DROP INDEX "public"."IDX_dae4631f1949d8a3553f1e919d"`)
        await db.query(`DROP INDEX "public"."IDX_a089edfb95807e5fa9faf2d878"`)
        await db.query(`DROP INDEX "public"."IDX_e9998cb14c035a5279c52ee420"`)
        await db.query(`DROP INDEX "public"."IDX_18bf95c5e40a82e1a8133fe2d2"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "all_involved_asset_ids"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "event_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "shares_amount"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "all_involved_asset_registry_ids"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "para_block_height"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "xykpool_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "initial_amount" numeric NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "amount" numeric NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "entries" jsonb NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "created_at_para_block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "destroyed_at_para_block_height" integer`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ALTER COLUMN "created_at_para_block_height" DROP DEFAULT`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "account_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "deposit_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "deposit_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ALTER COLUMN "global_farm_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ALTER COLUMN "yield_farm_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ALTER COLUMN "event_id" DROP NOT NULL`)
        await db.query(`CREATE INDEX "IDX_4030d18bc74fd6f8808da38b85" ON "xyk_yield_farm_deposit" ("created_at_para_block_height") `)
        await db.query(`CREATE INDEX "IDX_3d22c58f8f8068e4555e8b3ffe" ON "xyk_yield_farm_deposit" ("destroyed_at_para_block_height") `)
    }

    async down(db) {
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_dae4631f1949d8a3553f1e919d4" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD CONSTRAINT "FK_e9998cb14c035a5279c52ee420b" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD CONSTRAINT "FK_18bf95c5e40a82e1a8133fe2d2e" FOREIGN KEY ("deposit_id") REFERENCES "xyk_yield_farm_deposit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`CREATE INDEX "IDX_dae4631f1949d8a3553f1e919d" ON "xyk_yield_farm_deposit" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_a089edfb95807e5fa9faf2d878" ON "xyk_yield_farm_deposit" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_e9998cb14c035a5279c52ee420" ON "xyk_yield_farm_deposit" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_18bf95c5e40a82e1a8133fe2d2" ON "xyk_yield_farm_deposit_event" ("deposit_id") `)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "all_involved_asset_ids" text array NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "event_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "shares_amount" numeric NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "yield_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "all_involved_asset_registry_ids" text array NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "para_block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "xykpool_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "initial_amount"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "amount"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "entries"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "created_at_para_block_height"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "destroyed_at_para_block_height"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" ALTER COLUMN "created_at_para_block_height" SET DEFAULT '0'`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" ADD "account_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ADD "deposit_id" character varying`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" DROP COLUMN "deposit_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ALTER COLUMN "global_farm_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ALTER COLUMN "yield_farm_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit_event" ALTER COLUMN "event_id" SET NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_4030d18bc74fd6f8808da38b85"`)
        await db.query(`DROP INDEX "public"."IDX_3d22c58f8f8068e4555e8b3ffe"`)
    }
}
