module.exports = class Data1765487975791 {
    name = 'Data1765487975791'

    async up(db) {
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_a44ae247ba071997b3849ec5717"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_ac41ce5c2e28effcf644a9cd6d1"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_87594e37d5ad67fcc3cefeaf787"`)
        await db.query(`ALTER TABLE "nft_collection" DROP CONSTRAINT "FK_a48062517a5dbd5c41b32f3fe71"`)
        await db.query(`ALTER TABLE "nft_asset" DROP CONSTRAINT "FK_16a702920b053f7b2413623d3b0"`)
        await db.query(`ALTER TABLE "nft_asset" DROP CONSTRAINT "FK_4c1b9f9057fad88ea4f82a615dd"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_d5f3c8eca4debf29322d84322db"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP CONSTRAINT "FK_12611a74c4fda79d26a2c3cecc0"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP CONSTRAINT "FK_a707ae8f047454dbd57488d1a98"`)
        await db.query(`DROP INDEX "public"."IDX_a44ae247ba071997b3849ec571"`)
        await db.query(`DROP INDEX "public"."IDX_ac41ce5c2e28effcf644a9cd6d"`)
        await db.query(`DROP INDEX "public"."IDX_87594e37d5ad67fcc3cefeaf78"`)
        await db.query(`DROP INDEX "public"."IDX_a48062517a5dbd5c41b32f3fe7"`)
        await db.query(`DROP INDEX "public"."IDX_16a702920b053f7b2413623d3b"`)
        await db.query(`DROP INDEX "public"."IDX_4c1b9f9057fad88ea4f82a615d"`)
        await db.query(`DROP INDEX "public"."IDX_d5f3c8eca4debf29322d84322d"`)
        await db.query(`DROP INDEX "public"."IDX_12611a74c4fda79d26a2c3cecc"`)
        await db.query(`DROP INDEX "public"."IDX_4b51ac4f2442e2e942073b238c"`)
        await db.query(`DROP INDEX "public"."IDX_a707ae8f047454dbd57488d1a9"`)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" RENAME COLUMN "position_nft_id" TO "nft_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" RENAME COLUMN "deposit_nft_id" TO "nft_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "event"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "deposit_nft_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "yield_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "para_block_height"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "global_farm_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "position_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "nft_id" text`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "initial_shares_amount" numeric NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "entries" jsonb NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "created_at_para_block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "destroyed_at_para_block_height" integer`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "owner_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "owner_id" text NOT NULL`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "issuer_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "issuer_id" text NOT NULL`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "admin_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "admin_id" text NOT NULL`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "freezer_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "freezer_id" text NOT NULL`)
        await db.query(`ALTER TABLE "nft_asset" DROP COLUMN "collection_id"`)
        await db.query(`ALTER TABLE "nft_asset" ADD "collection_id" text NOT NULL`)
        await db.query(`ALTER TABLE "nft_asset" DROP COLUMN "owner_id"`)
        await db.query(`ALTER TABLE "nft_asset" ADD "owner_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "position_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "position_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "account_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "deposit_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "deposit_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ALTER COLUMN "global_farm_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ALTER COLUMN "yield_farm_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ALTER COLUMN "event_id" DROP NOT NULL`)
        await db.query(`CREATE INDEX "IDX_66a008d1ad028f85c6d3281613" ON "omnipool_yield_farm_deposit" ("created_at_para_block_height") `)
        await db.query(`CREATE INDEX "IDX_2f177b2ced986efc31c56bedf3" ON "omnipool_yield_farm_deposit" ("destroyed_at_para_block_height") `)
    }

    async down(db) {
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_a44ae247ba071997b3849ec5717" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_ac41ce5c2e28effcf644a9cd6d1" FOREIGN KEY ("issuer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_87594e37d5ad67fcc3cefeaf787" FOREIGN KEY ("admin_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_collection" ADD CONSTRAINT "FK_a48062517a5dbd5c41b32f3fe71" FOREIGN KEY ("freezer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_asset" ADD CONSTRAINT "FK_16a702920b053f7b2413623d3b0" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft_asset" ADD CONSTRAINT "FK_4c1b9f9057fad88ea4f82a615dd" FOREIGN KEY ("collection_id") REFERENCES "nft_collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_d5f3c8eca4debf29322d84322db" FOREIGN KEY ("position_id") REFERENCES "omnipool_liquidity_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD CONSTRAINT "FK_12611a74c4fda79d26a2c3cecc0" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD CONSTRAINT "FK_a707ae8f047454dbd57488d1a98" FOREIGN KEY ("deposit_id") REFERENCES "omnipool_yield_farm_deposit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`CREATE INDEX "IDX_a44ae247ba071997b3849ec571" ON "nft_collection" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_ac41ce5c2e28effcf644a9cd6d" ON "nft_collection" ("issuer_id") `)
        await db.query(`CREATE INDEX "IDX_87594e37d5ad67fcc3cefeaf78" ON "nft_collection" ("admin_id") `)
        await db.query(`CREATE INDEX "IDX_a48062517a5dbd5c41b32f3fe7" ON "nft_collection" ("freezer_id") `)
        await db.query(`CREATE INDEX "IDX_16a702920b053f7b2413623d3b" ON "nft_asset" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_4c1b9f9057fad88ea4f82a615d" ON "nft_asset" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_d5f3c8eca4debf29322d84322d" ON "omnipool_yield_farm_deposit" ("position_id") `)
        await db.query(`CREATE INDEX "IDX_12611a74c4fda79d26a2c3cecc" ON "omnipool_yield_farm_deposit" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_4b51ac4f2442e2e942073b238c" ON "omnipool_yield_farm_deposit" ("para_block_height") `)
        await db.query(`CREATE INDEX "IDX_a707ae8f047454dbd57488d1a9" ON "omnipool_yield_farm_deposit_event" ("deposit_id") `)
        await db.query(`ALTER TABLE "omnipool_liquidity_position" RENAME COLUMN "nft_id" TO "position_nft_id"`)
        await db.query(`ALTER TABLE "xyk_yield_farm_deposit" RENAME COLUMN "nft_id" TO "deposit_nft_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "event" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "deposit_nft_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "yield_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "para_block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "global_farm_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "position_id" text NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "nft_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "initial_shares_amount"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "entries"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "created_at_para_block_height"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "destroyed_at_para_block_height"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "owner_id" character varying`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "owner_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "issuer_id" character varying`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "issuer_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "admin_id" character varying`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "admin_id"`)
        await db.query(`ALTER TABLE "nft_collection" ADD "freezer_id" character varying`)
        await db.query(`ALTER TABLE "nft_collection" DROP COLUMN "freezer_id"`)
        await db.query(`ALTER TABLE "nft_asset" ADD "collection_id" character varying`)
        await db.query(`ALTER TABLE "nft_asset" DROP COLUMN "collection_id"`)
        await db.query(`ALTER TABLE "nft_asset" ADD "owner_id" character varying`)
        await db.query(`ALTER TABLE "nft_asset" DROP COLUMN "owner_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "position_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "position_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" ADD "account_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit" DROP COLUMN "account_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ADD "deposit_id" character varying`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" DROP COLUMN "deposit_id"`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ALTER COLUMN "global_farm_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ALTER COLUMN "yield_farm_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "omnipool_yield_farm_deposit_event" ALTER COLUMN "event_id" SET NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_66a008d1ad028f85c6d3281613"`)
        await db.query(`DROP INDEX "public"."IDX_2f177b2ced986efc31c56bedf3"`)
    }
}
