version: "3.7"

x-chain-name: &chain-name "hydration"
x-postgres-db: &postgres-db "storage_dictionary_db"
x-postgres-user: &postgres-user "postgres"
x-postgres-password: &postgres-password "postgres"

x-storage-dictionary-db-creds: &storage-dictionary-db-creds
  DB_PORT: 5432
  DB_NAME: *postgres-db
  DB_USER: *postgres-user
  DB_PASS: *postgres-password

networks:
  default:
    driver: overlay

volumes:
  storage-dictionary-db:
    driver: local

services:
  storage-dictionary-db:
    image: postgres:15
    environment:
      POSTGRES_DB: *postgres-db
      POSTGRES_USER: *postgres-user
      POSTGRES_PASSWORD: *postgres-password
    volumes:
      - storage-dictionary-db:/var/lib/postgresql/data
    networks:
      - default

  storage-dictionary-processor:
    image: ghcr.io/mckrava/storage-dictionary-indexer:wip-feat-init-monorepo
    depends_on:
      - storage-dictionary-db
    environment:
      #
      # REQUIRED PARAMETERS
      #
      NODE_ENV: "self-hosted"
      CHAIN: *chain-name
      <<: *storage-dictionary-db-creds
      DB_HOST: "storage-dictionary-db"
      RPC_URL: "wss://archive.rpc.hydration.cloud"
      # Set IGNORE_ARCHIVE_DATA_SOURCE to true if indexer has to work without SQD archive.
      IGNORE_ARCHIVE_DATA_SOURCE: false
      GATEWAY_HYDRATION_HTTPS: "https://v2.archive.subsquid.io/network/hydradx"
      OMNIPOOL_ADDRESS: "0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000"

      #
      # OPTIONAL PARAMETERS
      #
      PROCESS_FROM_BLOCK: 0
      PROCESS_TO_BLOCK: -1
      PROCESS_LBP_POOLS: true
      PROCESS_XYK_POOLS: true
      PROCESS_OMNIPOOLS: true
      PROCESS_STABLEPOOLS: true

      STATE_SCHEMA_NAME: "squid_processor"
      ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: "squid_processor"
      INDEXER_MAX_SUB_BATCH_SIZE: 1500
      SUB_BATCH_MAX_TIMEOUT_MS: 500
      INDEXER_SUB_PROCESSORS_NUMBER: 5
      ASSETS_TRACKER_PROCESSOR: true
    networks:
      - default
    command:
      - sh
      - -c
      - "sqd migration:apply && sqd process:prod"

  storage-dictionary-api:
    image: ghcr.io/mckrava/storage-dictionary-indexer:wip-feat-init-monorepo
    depends_on:
      - storage-dictionary-processor
    environment:
      NODE_ENV: "self-hosted"
      CHAIN: *chain-name
      GQL_PORT: 8090
      <<: *storage-dictionary-db-creds
      DB_HOST: "storage-dictionary-db"

      #
      # OPTIONAL PARAMETERS
      #
      SUB_PROCESSORS_RANGES: "squid_processor:0:-1"

    ports:
      - "8090:8090"
    networks:
      - default
    command:
      - sh
      - -c
      - "sqd api:prod"
