# =============================================
# ============== O M N I P O O L ==============
# =============================================

manifestVersion: subsquid.io/v0.1
name: hydration-storage-dictionary
slot: 309
description: Hydration storage dictionary for Omnipool storage
build:
deploy:
  addons:
    postgres:
      config:
        statement_timeout: 1080000
        log_min_duration_statement: 60000
  processor:
    #    - name: omnipool-batch-proc-1
    #      cmd: ['sqd', 'process:prod']
    #      env:
    #        RPC_URL: wss://node.kril.hydration.cloud
    #        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
    #        PROCESS_LBP_POOLS: false
    #        PROCESS_XYK_POOLS: false
    #        PROCESS_OMNIPOOLS: true
    #        PROCESS_STABLEPOOLS: false
    #        PROCESS_GENERIC_HIST_DATA: false
    #        INDEXING_IS_PAUSED: false
    #        GQL_PORT: 8080
    #        NODE_ENV: production
    #        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
    #        PROCESS_FROM_BLOCK: 1708100
    #        PROCESS_TO_BLOCK: 2966000
    #        STATE_SCHEMA_NAME: omnipool__batch_proc_1
    #        SUB_BATCH_SIZE: 300
    #        INDEXER_MAX_SUB_BATCH_SIZE: 200
    #        ASSETS_TRACKER_PROCESSOR: false
    #        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc
    #    - name: omnipool-batch-proc-2
    #      cmd: ['sqd', 'process:prod']
    #      env:
    #        RPC_URL: wss://node.kril.hydration.cloud
    #        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
    #        PROCESS_LBP_POOLS: false
    #        PROCESS_XYK_POOLS: false
    #        PROCESS_OMNIPOOLS: true
    #        PROCESS_STABLEPOOLS: false
    #        PROCESS_GENERIC_HIST_DATA: false
    #        INDEXING_IS_PAUSED: false
    #        GQL_PORT: 8080
    #        NODE_ENV: production
    #        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
    #        PROCESS_FROM_BLOCK: 2966001
    #        PROCESS_TO_BLOCK: 4224000
    #        STATE_SCHEMA_NAME: omnipool__batch_proc_2
    #        SUB_BATCH_SIZE: 300
    #        INDEXER_MAX_SUB_BATCH_SIZE: 200
    #        ASSETS_TRACKER_PROCESSOR: false
    #        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc
    #    - name: omnipool-batch-proc-3
    #      cmd: ['sqd', 'process:prod']
    #      env:
    #        RPC_URL: wss://node.kril.hydration.cloud
    #        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
    #        PROCESS_LBP_POOLS: false
    #        PROCESS_XYK_POOLS: false
    #        PROCESS_OMNIPOOLS: true
    #        PROCESS_STABLEPOOLS: false
    #        PROCESS_GENERIC_HIST_DATA: false
    #        INDEXING_IS_PAUSED: false
    #        GQL_PORT: 8080
    #        NODE_ENV: production
    #        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
    #        PROCESS_FROM_BLOCK: 4224001
    #        PROCESS_TO_BLOCK: 5482000
    #        STATE_SCHEMA_NAME: omnipool__batch_proc_3
    #        SUB_BATCH_SIZE: 300
    #        INDEXER_MAX_SUB_BATCH_SIZE: 200
    #        ASSETS_TRACKER_PROCESSOR: false
    #        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc
    #    - name: omnipool-batch-proc-4
    #      cmd: ['sqd', 'process:prod']
    #      env:
    #        RPC_URL: wss://node.kril.hydration.cloud
    #        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
    #        PROCESS_LBP_POOLS: false
    #        PROCESS_XYK_POOLS: false
    #        PROCESS_OMNIPOOLS: true
    #        PROCESS_STABLEPOOLS: false
    #        PROCESS_GENERIC_HIST_DATA: false
    #        INDEXING_IS_PAUSED: false
    #        GQL_PORT: 8080
    #        NODE_ENV: production
    #        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
    #        PROCESS_FROM_BLOCK: 5482001
    #        PROCESS_TO_BLOCK: 6740000
    #        STATE_SCHEMA_NAME: omnipool__batch_proc_4
    #        SUB_BATCH_SIZE: 300
    #        INDEXER_MAX_SUB_BATCH_SIZE: 200
    #        ASSETS_TRACKER_PROCESSOR: false
    #        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc
    - name: omnipool-batch-proc-5
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://node.kril.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: false
        INDEXING_IS_PAUSED: false
        PROCESS_ONLY_MISSED_BLOCKS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 6740001
        PROCESS_TO_BLOCK: -1
        STATE_SCHEMA_NAME: omnipool__batch_proc_5
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 200
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc

    - name: omnipool-batch-proc-ensure
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://node.kril.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: false
        INDEXING_IS_PAUSED: false
        PROCESS_ONLY_MISSED_BLOCKS: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 1708100
        PROCESS_TO_BLOCK: -1
        STATE_SCHEMA_NAME: omnipool__batch_proc_ensure
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc

    - name: omnipool-assets-tracker-proc
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://node.kril.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: false
        INDEXING_IS_PAUSED: false
        PROCESS_ONLY_MISSED_BLOCKS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 6740001
        PROCESS_TO_BLOCK: -1
        STATE_SCHEMA_NAME: omnipool__assets_tracker_proc
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 200
        ASSETS_TRACKER_PROCESSOR: true
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: omnipool__assets_tracker_proc
  api:
    env:
      GQL_PORT: 8080
      NODE_ENV: production
      SUB_PROCESSORS_RANGES: 'omnipool__batch_proc_1:1708100:2966000;omnipool__batch_proc_2:2966001:4224000;omnipool__batch_proc_3:4224001:5482000;omnipool__batch_proc_4:5482001:6740000;omnipool__batch_proc_5:6740001:-1;omnipool__batch_proc_ensure:1708100:-1;omnipool__assets_tracker_proc:6740001:-1'

    cmd:
      - sqd
      - api:prod
scale:
  dedicated: false
  addons:
    postgres:
      profile: large
      storage: 500G
  processor:
    profile: large
  api:
    profile: large
