# =================================================
# ============ GENERIC HISTORICAL DATA ============
# =================================================

manifestVersion: subsquid.io/v0.1
name: hydration-storage-dictionary
slot: 601
description: Hydration storage dictionary for generic data (AssetData, Oracles, AavePools)
build:
deploy:
  addons:
    postgres:
      config:
        statement_timeout: 1080000
        log_min_duration_statement: 60000
  processor:
    - name: batch-proc-1
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://4.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: true
        INDEXING_IS_PAUSED: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 1439857
        PROCESS_TO_BLOCK: 2752000
        STATE_SCHEMA_NAME: gen_hist_data__batch_proc_1
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
    - name: batch-proc-2
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://4.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: true
        INDEXING_IS_PAUSED: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 2752001
        PROCESS_TO_BLOCK: 4064000
        STATE_SCHEMA_NAME: gen_hist_data__batch_proc_2
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
    - name: batch-proc-3
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://4.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: true
        INDEXING_IS_PAUSED: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 4064001
        PROCESS_TO_BLOCK: 5376000
        STATE_SCHEMA_NAME: gen_hist_data__batch_proc_3
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
    - name: batch-proc-4
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://4.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: true
        INDEXING_IS_PAUSED: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 5376001
        PROCESS_TO_BLOCK: 6688000
        STATE_SCHEMA_NAME: gen_hist_data__batch_proc_4
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
    - name: batch-proc-5
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://4.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: true
        INDEXING_IS_PAUSED: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 6688001
        PROCESS_TO_BLOCK: -1
        STATE_SCHEMA_NAME: gen_hist_data__batch_proc_5
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: false
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
    - name: assets-tracker-proc
      cmd: ['sqd', 'process:prod']
      env:
        RPC_URL: wss://4.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: false
        PROCESS_STABLEPOOLS: false
        PROCESS_GENERIC_HIST_DATA: false
        INDEXING_IS_PAUSED: true
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        PROCESS_FROM_BLOCK: 6688001
        PROCESS_TO_BLOCK: -1
        STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
        SUB_BATCH_SIZE: 300
        INDEXER_MAX_SUB_BATCH_SIZE: 500
        ASSETS_TRACKER_PROCESSOR: true
        ASSETS_ACTUALISATION_PROC_STATE_SCHEMA_NAME: gen_hist_data__assets_tracker_proc
  api:
    env:
      GQL_PORT: 8080
      NODE_ENV: production
      SUB_PROCESSORS_RANGES: 'gen_hist_data__batch_proc_1:1439857:2752000;gen_hist_data__batch_proc_2:2752001:4064000;gen_hist_data__batch_proc_3:4064001:5376000;gen_hist_data__batch_proc_4:5376001:6688000;gen_hist_data__batch_proc_5:6688001:-1;gen_hist_data__assets_tracker_proc:6688001:-1'
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: false
  addons:
    postgres:
      profile: medium
      storage: 700G
  processor:
    profile: medium
  api:
    profile: large
#    replicas: 3
