# ======================================================================================================================
# *** Common entities and types ***
# ======================================================================================================================

type SubProcessorStatus @entity {
  "sub_processor_schema_name"
  id: ID!
  fromBlock: Int!
  toBlock: Int!
  height: Int!
  assetsActualisedAtBlock: Int
}

type Block @entity {
  "block_id"
  id: ID!
  height: Int!
  hash: String!
  timestamp: String!
  relayBlockHeight: Int!
}

type AccountBalances {
  free: BigInt!
  reserved: BigInt!
  miscFrozen: BigInt
  feeFrozen: BigInt
  frozen: BigInt
  flags: BigInt
}

enum DataStructureTypeName {
  AccountBalances
  AssetDynamicFee
  OmnipoolAssetState
}

type DataStructureType @entity {
  "type_name"
  id: ID!
  name: DataStructureTypeName!
  definition: String!
}

type MinifiedDataStructure {
  t: DataStructureTypeName!
  d: [String!]!
}

# ======================================================================================================================
# *** Account ***
# ======================================================================================================================

enum AccountType {
  User
  Omnipool
  Stableswap
  Xykpool
  Lbppool
}

type Account @entity {
  "<address>"
  id: ID!
  accountType: AccountType!
  boundEvmAddress: String
}

type AccountAssetBalanceHistoricalData @entity {
  "<address>-<assetId>-<paraBlockHeight>"
  id: ID!
  accountId: String! @index
  assetId: String! @index

  "free property in storage"
  transferable: String!
  "reserved property in storage"
  totalLocked: String!

  paraBlockHeight: Int! @index
}

type AccountMmPositionHistoricalData @entity {
  "<accountId>-<poolAddress>-<paraBlockHeight>"
  id: ID!
  accountId: String!
  accountBoundEvmAddress: String

  totalCollateralBase: String!
  totalDebtBase: String!
  availableBorrowsBase: String!
  currentLiquidationThreshold: String!
  ltv: String!
  healthFactor: String
  poolAddress: String!

  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Asset ***
# ======================================================================================================================

enum AssetType {
  Bond
  External
  StableSwap
  Token
  XYK
  Erc20
  PoolShare
}

enum AssetResourceType {
  Underlying
  Collateral
  Debt
  aToken
}

type Asset @entity {
  "Asset ID"
  id: ID!
  evmAddress: String

  bondUnderlyingAsset: Asset
  underlyingAsset: Asset
  aToken: Asset
  variableDebtToken: Asset

  assetType: AssetType!
  resourceType: AssetResourceType
  name: String
  symbol: String
  decimals: Int
  xcmRateLimit: BigInt
  isSufficient: Boolean!
  bondMaturity: BigInt
}

type AssetDynamicFee {
  assetFee: Int!
  protocolFee: Int!
  timestamp: Int!
}

type AssetHistoricalData @entity {
  "<assetId>-<paraBlockHeight>"
  id: ID!
  asset: Asset!
  totalIssuance: String!
  "AssetDynamicFee"
  dynamicFee: MinifiedDataStructure
  existentialDeposit: String!
  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** LBP Pool ***
# ======================================================================================================================

type Lbppool @entity {
  "xykPoolAddress-paraBlockHeight"
  id: ID!
  "XYK pool address"
  poolAddress: String!
  assetAId: Int!
  assetBId: Int!
  owner: String!
  start: Int
  end: Int
  initialWeight: Int!
  finalWeight: Int!
  weightCurve: String!
  fee: [Int!]!
  feeCollector: String
  repayTarget: String!

  paraBlockHeight: Int! @index
  assets: [LbppoolAssetsData!]! @derivedFrom(field: "pool")
}
type LbppoolAssetsData @entity {
  "xykPoolAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Lbppool!
  assetId: Int!
  "AccountBalances"
  balances: MinifiedDataStructure!

  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** XYK Pool ***
# ======================================================================================================================

type Xykpool @entity {
  "xykPoolAddress-paraBlockHeight"
  id: ID!
  "XYK pool address"
  poolAddress: String!
  assetAId: Int!
  assetBId: Int!
  shareTokenId: String
  assets: [XykpoolAssetsData!]! @derivedFrom(field: "pool")

  paraBlockHeight: Int! @index
}

type XykpoolAssetsData @entity {
  "xykPoolAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Xykpool!
  assetId: Int!
  "AccountBalances"
  balances: MinifiedDataStructure!

  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Omnipool ***
# ======================================================================================================================

type Tradability {
  bits: Int!
}

type OmnipoolAssetState {
  hubReserve: String!
  shares: String!
  protocolShares: String!
  cap: String!
  tradable: Tradability
}

type Omnipool @entity {
  "omnipoolId-paraBlockHeight"
  id: ID!
  poolAddress: String!
  hubAssetTradability: Tradability!

  assets: [OmnipoolAssetData!]! @derivedFrom(field: "pool")
  paraBlockHeight: Int! @index
}

type OmnipoolAssetData @entity {
  "omnipooAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Omnipool!
  assetId: Int!
  "AccountBalances"
  balances: MinifiedDataStructure!
  "OmnipoolAssetState"
  assetState: MinifiedDataStructure!

  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Stablepool ***
# ======================================================================================================================

type StableswapPegsSource {
  sourceKind: String! # Oracle | Value
  oracleName: String
  oraclePeriod: EmaOraclePeriod
  oracleAsset: String
  valuePoints: [String!]
}

type Stableswap @entity {
  "stablepoolId-paraBlockHeight"
  id: ID!
  poolId: Int!
  poolAddress: String!

  initialAmplification: Int!
  finalAmplification: Int!
  initialBlock: Int!
  finalBlock: Int!
  fee: Int!
  pegs: [[String!]!]!
  maxPegUpdate: Int
  pegSources: [StableswapPegsSource!]

  assets: [StableswapAssetData!]! @derivedFrom(field: "pool")

  paraBlockHeight: Int! @index
}

type StableswapAssetData @entity {
  "stablepoolId-assetId-paraBlockHeight"
  id: ID!
  pool: Stableswap!
  assetId: Int!
  tradable: Tradability
  "AccountBalances"
  balances: MinifiedDataStructure!

  paraBlockHeight: Int! @index
}

type MmAggregatorOracle @entity {
  "<oracle_address>-<paraBlockHeight>"
  id: ID!
  address: String!
  price: String!
  decimals: Int!
  updatedAt: Int!
  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** AAVE Pool ***
# ======================================================================================================================

type Aavepool @entity {
  "<aavepoolId>-<paraBlockHeight>"
  id: ID!
  poolId: String!
  reserveAsset: Asset!
  aToken: Asset!
  liquidityIn: String!
  liquidityOut: String!

  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Ema Oracle ***
# ======================================================================================================================

enum EmaOraclePeriod {
  Day
  Hour
  LastBlock
  Short
  TenMinutes
  Week
}

type EmaOracleEntryPrice {
  n: String!
  d: String!
}
type EmaOracleEntryVolume {
  aIn: String!
  aOut: String!
  bIn: String!
  bOut: String!
}
type EmaOracleEntryLiquidity {
  a: String!
  b: String!
}

type EmaOracleEntry {
  source: String!
  assetIds: [Int!]!
  period: EmaOraclePeriod!

  price: EmaOracleEntryPrice!
  volume: EmaOracleEntryVolume!
  liquidity: EmaOracleEntryLiquidity!

  updatedAt: Int!
}

type EmaOracle @entity {
  "paraBlockHeight"
  id: ID!
  entries: [EmaOracleEntry!]!
  paraBlockHeight: Int! @index
}

type BlockCompressedData @entity {
  "block_number"
  id: ID!
  algo: String!
  compStrFormat: String!
  data: String!
  paraBlockHeight: Int! @index
}

# ======================================================================================================================
# *** E V M ***
# ======================================================================================================================
