# ======================================================================================================================
# *** Common entities and types ***
# ======================================================================================================================

type SubProcessorStatus @entity {
  "sub_processor_schema_name"
  id: ID!
  fromBlock: Int!
  toBlock: Int!
  height: Int!
  assetsActualisedAtBlock: Int
}

type AccountBalances {
  free: BigInt!
  reserved: BigInt!
  miscFrozen: BigInt
  feeFrozen: BigInt
  frozen: BigInt
  flags: BigInt
}

# ======================================================================================================================
# *** Asset ***
# ======================================================================================================================

enum AssetType {
  Bond
  External
  StableSwap
  Token
  XYK
  Erc20
  PoolShare
}

type Asset @entity {
  "Asset ID"
  id: ID!
  assetType: AssetType!
  name: String
  symbol: String
  decimals: Int
  xcmRateLimit: BigInt
  isSufficient: Boolean!
  bondUnderlyingAsset: Asset
  bondMaturity: BigInt
}

type AssetDynamicFee {
  assetFee: Int!
  protocolFee: Int!
  timestamp: Int!
}

type AssetHistoricalData @entity {
  "<assetId>-<paraBlockHeight>"
  id: ID!
  asset: Asset!
  totalIssuance: BigInt!
  dynamicFee: AssetDynamicFee
  existentialDeposit: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}

# ======================================================================================================================
# *** LBP Pool ***
# ======================================================================================================================

type Lbppool @entity {
  "xykPoolAddress-paraBlockHeight"
  id: ID!
  "XYK pool address"
  poolAddress: String! @index
  assetAId: Int! @index
  assetBId: Int! @index
  owner: String!
  start: Int
  end: Int
  initialWeight: Int!
  finalWeight: Int!
  weightCurve: String!
  fee: [Int!]!
  feeCollector: String
  repayTarget: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
  assets: [LbppoolAssetsData!]! @derivedFrom(field: "pool")
}
type LbppoolAssetsData @entity {
  "xykPoolAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Lbppool!
  assetId: Int! @index
  balances: AccountBalances!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}

# ======================================================================================================================
# *** XYK Pool ***
# ======================================================================================================================

type Xykpool @entity {
  "xykPoolAddress-paraBlockHeight"
  id: ID!
  "XYK pool address"
  poolAddress: String! @index
  assetAId: Int! @index
  assetBId: Int! @index
  shareTokenId: String

  assets: [XykpoolAssetsData!]! @derivedFrom(field: "pool")

  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}
type XykpoolAssetsData @entity {
  "xykPoolAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Xykpool!
  assetId: Int! @index
  balances: AccountBalances!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Omnipool ***
# ======================================================================================================================

type Tradability {
  bits: Int!
}

type OmnipoolAssetState {
  hubReserve: BigInt!
  shares: BigInt!
  protocolShares: BigInt!
  cap: BigInt!
  tradable: Tradability
}

type Omnipool @entity {
  "omnipoolId-paraBlockHeight"
  id: ID!
  poolAddress: String! @index
  hubAssetTradability: Tradability!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
  assets: [OmnipoolAssetData!]! @derivedFrom(field: "pool")
}

type OmnipoolAssetData @entity {
  "omnipooAddress-assetId-paraBlockHeight"
  id: ID!
  pool: Omnipool!
  assetId: Int! @index
  balances: AccountBalances!
  assetState: OmnipoolAssetState!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Stablepool ***
# ======================================================================================================================

type StableswapPegsSource {
  sourceKind: String! # Oracle | Value
  oracleName: String
  oraclePeriod: EmaOraclePeriod
  oracleAsset: String
  valuePoints: [String!]
}

type Stableswap @entity {
  "stablepoolId-paraBlockHeight"
  id: ID!
  poolId: Int! @index
  poolAddress: String! @index

  initialAmplification: Int!
  finalAmplification: Int!
  initialBlock: Int!
  finalBlock: Int!
  fee: Int!
  pegs: [[BigInt!]!]!
  maxPegUpdate: Int
  pegSources: [StableswapPegsSource!]

  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
  assets: [StableswapAssetData!]! @derivedFrom(field: "pool")
}

type StableswapAssetData @entity {
  "stablepoolId-assetId-paraBlockHeight"
  id: ID!
  pool: Stableswap!
  assetId: Int!
  tradable: Tradability
  balances: AccountBalances!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}

# ======================================================================================================================
# *** AAVE Pool ***
# ======================================================================================================================

type Aavepool @entity {
  "<aavepoolId>-<paraBlockHeight>"
  id: ID!
  poolId: String!
  reserveAsset: Asset!
  aToken: Asset!
  liquidityIn: BigInt!
  liquidityOut: BigInt!

  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}

# ======================================================================================================================
# *** Ema Oracle ***
# ======================================================================================================================

enum EmaOraclePeriod {
  Day
  Hour
  LastBlock
  Short
  TenMinutes
  Week
}

type EmaOracleEntryPrice {
  n: String!
  d: String!
}
type EmaOracleEntryVolume {
  aIn: String!
  aOut: String!
  bIn: String!
  bOut: String!
}
type EmaOracleEntryLiquidity {
  a: String!
  b: String!
}

type EmaOracleEntry {
  source: String!
  assetIds: [Int!]!
  period: EmaOraclePeriod!

  price: EmaOracleEntryPrice!
  volume: EmaOracleEntryVolume!
  liquidity: EmaOracleEntryLiquidity!

  updatedAt: Int!
}

type EmaOracle @entity {
  "paraBlockHeight"
  id: ID!
  entries: [EmaOracleEntry!]!
  paraBlockHeight: Int! @index
  relayBlockHeight: Int! @index
}
